#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 15, 2020 05:44:38 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import avion_irala_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    avion_irala_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    avion_irala_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family {Yu Gothic UI Semibold} -size 12 -weight bold"  \
            ""
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("705x817+627+98")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.397, rely=0.061, relheight=0.812
                , relwidth=0.133)
        self.Canvas1.configure(background="#d9d9d9")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")

        self.btnPrimeraClase_3 = ttk.Button(top)
        self.btnPrimeraClase_3.place(relx=1.121, rely=0.208, height=30, width=38)

        self.btnPrimeraClase_3.configure(command=avion_irala_support.ocupar)
        self.btnPrimeraClase_3.configure(takefocus="")
        self.btnPrimeraClase_3.configure(text='''1''')

        self.btnPrimeraClase = tk.Button(top)
        self.btnPrimeraClase.place(relx=0.184, rely=0.086, height=33, width=46)
        self.btnPrimeraClase.configure(activebackground="#ececec")
        self.btnPrimeraClase.configure(activeforeground="#ff0000")
        self.btnPrimeraClase.configure(background="#ffff00")
        self.btnPrimeraClase.configure(compound='bottom')
        self.btnPrimeraClase.configure(cursor="fleur")
        self.btnPrimeraClase.configure(disabledforeground="#a3a3a3")
        self.btnPrimeraClase.configure(font=font9)
        self.btnPrimeraClase.configure(foreground="#000000")
        self.btnPrimeraClase.configure(highlightbackground="#d9d9d9")
        self.btnPrimeraClase.configure(highlightcolor="black")
        self.btnPrimeraClase.configure(pady="0")
        self.btnPrimeraClase.configure(text='''1''')

        self.btnPrimeraClase_2 = tk.Button(top)
        self.btnPrimeraClase_2.place(relx=0.284, rely=0.086, height=33, width=46)

        self.btnPrimeraClase_2.configure(activebackground="#ececec")
        self.btnPrimeraClase_2.configure(activeforeground="#ff0000")
        self.btnPrimeraClase_2.configure(background="#ffff00")
        self.btnPrimeraClase_2.configure(compound='bottom')
        self.btnPrimeraClase_2.configure(disabledforeground="#a3a3a3")
        self.btnPrimeraClase_2.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnPrimeraClase_2.configure(foreground="#000000")
        self.btnPrimeraClase_2.configure(highlightbackground="#d9d9d9")
        self.btnPrimeraClase_2.configure(highlightcolor="black")
        self.btnPrimeraClase_2.configure(pady="0")
        self.btnPrimeraClase_2.configure(text='''2''')

        self.btnPrimeraClase_3 = tk.Button(top)
        self.btnPrimeraClase_3.place(relx=0.567, rely=0.086, height=33, width=46)

        self.btnPrimeraClase_3.configure(activebackground="#ececec")
        self.btnPrimeraClase_3.configure(activeforeground="#ff0000")
        self.btnPrimeraClase_3.configure(background="#ffff00")
        self.btnPrimeraClase_3.configure(compound='bottom')
        self.btnPrimeraClase_3.configure(disabledforeground="#a3a3a3")
        self.btnPrimeraClase_3.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnPrimeraClase_3.configure(foreground="#000000")
        self.btnPrimeraClase_3.configure(highlightbackground="#d9d9d9")
        self.btnPrimeraClase_3.configure(highlightcolor="black")
        self.btnPrimeraClase_3.configure(pady="0")
        self.btnPrimeraClase_3.configure(text='''3''')

        self.btnPrimeraClase_4 = tk.Button(top)
        self.btnPrimeraClase_4.place(relx=0.681, rely=0.086, height=33, width=46)

        self.btnPrimeraClase_4.configure(activebackground="#ececec")
        self.btnPrimeraClase_4.configure(activeforeground="#ff0000")
        self.btnPrimeraClase_4.configure(background="#ffff00")
        self.btnPrimeraClase_4.configure(compound='bottom')
        self.btnPrimeraClase_4.configure(disabledforeground="#a3a3a3")
        self.btnPrimeraClase_4.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnPrimeraClase_4.configure(foreground="#000000")
        self.btnPrimeraClase_4.configure(highlightbackground="#d9d9d9")
        self.btnPrimeraClase_4.configure(highlightcolor="black")
        self.btnPrimeraClase_4.configure(pady="0")
        self.btnPrimeraClase_4.configure(text='''4''')

        self.btnPrimeraClase_5 = tk.Button(top)
        self.btnPrimeraClase_5.place(relx=0.184, rely=0.159, height=33, width=46)

        self.btnPrimeraClase_5.configure(activebackground="#ececec")
        self.btnPrimeraClase_5.configure(activeforeground="#ff0000")
        self.btnPrimeraClase_5.configure(background="#ffff00")
        self.btnPrimeraClase_5.configure(compound='bottom')
        self.btnPrimeraClase_5.configure(disabledforeground="#a3a3a3")
        self.btnPrimeraClase_5.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnPrimeraClase_5.configure(foreground="#000000")
        self.btnPrimeraClase_5.configure(highlightbackground="#d9d9d9")
        self.btnPrimeraClase_5.configure(highlightcolor="black")
        self.btnPrimeraClase_5.configure(pady="0")
        self.btnPrimeraClase_5.configure(text='''5''')

        self.btnPrimeraClase_6 = tk.Button(top)
        self.btnPrimeraClase_6.place(relx=0.284, rely=0.159, height=33, width=46)

        self.btnPrimeraClase_6.configure(activebackground="#ececec")
        self.btnPrimeraClase_6.configure(activeforeground="#ff0000")
        self.btnPrimeraClase_6.configure(background="#ffff00")
        self.btnPrimeraClase_6.configure(compound='bottom')
        self.btnPrimeraClase_6.configure(disabledforeground="#a3a3a3")
        self.btnPrimeraClase_6.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnPrimeraClase_6.configure(foreground="#000000")
        self.btnPrimeraClase_6.configure(highlightbackground="#d9d9d9")
        self.btnPrimeraClase_6.configure(highlightcolor="black")
        self.btnPrimeraClase_6.configure(pady="0")
        self.btnPrimeraClase_6.configure(text='''6''')

        self.btnPrimeraClase_7 = tk.Button(top)
        self.btnPrimeraClase_7.place(relx=0.567, rely=0.159, height=33, width=46)

        self.btnPrimeraClase_7.configure(activebackground="#ececec")
        self.btnPrimeraClase_7.configure(activeforeground="#ff0000")
        self.btnPrimeraClase_7.configure(background="#ffff00")
        self.btnPrimeraClase_7.configure(compound='bottom')
        self.btnPrimeraClase_7.configure(disabledforeground="#a3a3a3")
        self.btnPrimeraClase_7.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnPrimeraClase_7.configure(foreground="#000000")
        self.btnPrimeraClase_7.configure(highlightbackground="#d9d9d9")
        self.btnPrimeraClase_7.configure(highlightcolor="black")
        self.btnPrimeraClase_7.configure(overrelief="flat")
        self.btnPrimeraClase_7.configure(pady="0")
        self.btnPrimeraClase_7.configure(text='''7''')

        self.btnPrimeraClase_8 = tk.Button(top)
        self.btnPrimeraClase_8.place(relx=0.681, rely=0.159, height=33, width=46)

        self.btnPrimeraClase_8.configure(activebackground="#ececec")
        self.btnPrimeraClase_8.configure(activeforeground="#ff0000")
        self.btnPrimeraClase_8.configure(background="#ffff00")
        self.btnPrimeraClase_8.configure(compound='bottom')
        self.btnPrimeraClase_8.configure(disabledforeground="#a3a3a3")
        self.btnPrimeraClase_8.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnPrimeraClase_8.configure(foreground="#000000")
        self.btnPrimeraClase_8.configure(highlightbackground="#d9d9d9")
        self.btnPrimeraClase_8.configure(highlightcolor="black")
        self.btnPrimeraClase_8.configure(pady="0")
        self.btnPrimeraClase_8.configure(text='''8''')

        self.btnEconomicaClase_1 = tk.Button(top)
        self.btnEconomicaClase_1.place(relx=0.099, rely=0.245, height=33
                , width=46)
        self.btnEconomicaClase_1.configure(activebackground="#ececec")
        self.btnEconomicaClase_1.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_1.configure(background="#0000ff")
        self.btnEconomicaClase_1.configure(compound='bottom')
        self.btnEconomicaClase_1.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_1.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_1.configure(foreground="#000000")
        self.btnEconomicaClase_1.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_1.configure(highlightcolor="black")
        self.btnEconomicaClase_1.configure(pady="0")
        self.btnEconomicaClase_1.configure(text='''9''')

        self.btnEconomicaClase_2 = tk.Button(top)
        self.btnEconomicaClase_2.place(relx=0.199, rely=0.245, height=33
                , width=46)
        self.btnEconomicaClase_2.configure(activebackground="#ececec")
        self.btnEconomicaClase_2.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_2.configure(background="#0000ff")
        self.btnEconomicaClase_2.configure(compound='bottom')
        self.btnEconomicaClase_2.configure(cursor="fleur")
        self.btnEconomicaClase_2.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_2.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_2.configure(foreground="#000000")
        self.btnEconomicaClase_2.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_2.configure(highlightcolor="black")
        self.btnEconomicaClase_2.configure(pady="0")
        self.btnEconomicaClase_2.configure(text='''10''')

        self.btnEconomicaClase_2 = tk.Button(top)
        self.btnEconomicaClase_2.place(relx=0.298, rely=0.245, height=33
                , width=46)
        self.btnEconomicaClase_2.configure(activebackground="#ececec")
        self.btnEconomicaClase_2.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_2.configure(background="#0000ff")
        self.btnEconomicaClase_2.configure(compound='bottom')
        self.btnEconomicaClase_2.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_2.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_2.configure(foreground="#000000")
        self.btnEconomicaClase_2.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_2.configure(highlightcolor="black")
        self.btnEconomicaClase_2.configure(pady="0")
        self.btnEconomicaClase_2.configure(text='''11''')

        self.btnEconomicaClase_2 = tk.Button(top)
        self.btnEconomicaClase_2.place(relx=0.553, rely=0.245, height=33
                , width=46)
        self.btnEconomicaClase_2.configure(activebackground="#ececec")
        self.btnEconomicaClase_2.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_2.configure(background="#0000ff")
        self.btnEconomicaClase_2.configure(compound='bottom')
        self.btnEconomicaClase_2.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_2.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_2.configure(foreground="#000000")
        self.btnEconomicaClase_2.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_2.configure(highlightcolor="black")
        self.btnEconomicaClase_2.configure(pady="0")
        self.btnEconomicaClase_2.configure(text='''12''')

        self.btnEconomicaClase_2 = tk.Button(top)
        self.btnEconomicaClase_2.place(relx=0.652, rely=0.245, height=33
                , width=46)
        self.btnEconomicaClase_2.configure(activebackground="#ececec")
        self.btnEconomicaClase_2.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_2.configure(background="#0000ff")
        self.btnEconomicaClase_2.configure(compound='bottom')
        self.btnEconomicaClase_2.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_2.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_2.configure(foreground="#000000")
        self.btnEconomicaClase_2.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_2.configure(highlightcolor="black")
        self.btnEconomicaClase_2.configure(pady="0")
        self.btnEconomicaClase_2.configure(text='''13''')

        self.btnEconomicaClase_2 = tk.Button(top)
        self.btnEconomicaClase_2.place(relx=0.752, rely=0.245, height=33
                , width=46)
        self.btnEconomicaClase_2.configure(activebackground="#ececec")
        self.btnEconomicaClase_2.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_2.configure(background="#0000ff")
        self.btnEconomicaClase_2.configure(compound='bottom')
        self.btnEconomicaClase_2.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_2.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_2.configure(foreground="#000000")
        self.btnEconomicaClase_2.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_2.configure(highlightcolor="black")
        self.btnEconomicaClase_2.configure(pady="0")
        self.btnEconomicaClase_2.configure(text='''14''')

        self.btnEconomicaClase_2 = tk.Button(top)
        self.btnEconomicaClase_2.place(relx=0.099, rely=0.306, height=33
                , width=46)
        self.btnEconomicaClase_2.configure(activebackground="#ececec")
        self.btnEconomicaClase_2.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_2.configure(background="#0000ff")
        self.btnEconomicaClase_2.configure(compound='bottom')
        self.btnEconomicaClase_2.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_2.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_2.configure(foreground="#000000")
        self.btnEconomicaClase_2.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_2.configure(highlightcolor="black")
        self.btnEconomicaClase_2.configure(pady="0")
        self.btnEconomicaClase_2.configure(text='''15''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.btnEconomicaClase_2 = tk.Button(top)
        self.btnEconomicaClase_2.place(relx=0.199, rely=0.306, height=33
                , width=46)
        self.btnEconomicaClase_2.configure(activebackground="#ececec")
        self.btnEconomicaClase_2.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_2.configure(background="#0000ff")
        self.btnEconomicaClase_2.configure(compound='bottom')
        self.btnEconomicaClase_2.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_2.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_2.configure(foreground="#000000")
        self.btnEconomicaClase_2.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_2.configure(highlightcolor="black")
        self.btnEconomicaClase_2.configure(pady="0")
        self.btnEconomicaClase_2.configure(text='''16''')

        self.btnEconomicaClase_2 = tk.Button(top)
        self.btnEconomicaClase_2.place(relx=0.298, rely=0.306, height=33
                , width=46)
        self.btnEconomicaClase_2.configure(activebackground="#ececec")
        self.btnEconomicaClase_2.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_2.configure(background="#0000ff")
        self.btnEconomicaClase_2.configure(compound='bottom')
        self.btnEconomicaClase_2.configure(cursor="fleur")
        self.btnEconomicaClase_2.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_2.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_2.configure(foreground="#000000")
        self.btnEconomicaClase_2.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_2.configure(highlightcolor="black")
        self.btnEconomicaClase_2.configure(pady="0")
        self.btnEconomicaClase_2.configure(text='''17''')

        self.btnEconomicaClase_2 = tk.Button(top)
        self.btnEconomicaClase_2.place(relx=0.553, rely=0.306, height=33
                , width=46)
        self.btnEconomicaClase_2.configure(activebackground="#ececec")
        self.btnEconomicaClase_2.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_2.configure(background="#0000ff")
        self.btnEconomicaClase_2.configure(compound='bottom')
        self.btnEconomicaClase_2.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_2.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_2.configure(foreground="#000000")
        self.btnEconomicaClase_2.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_2.configure(highlightcolor="black")
        self.btnEconomicaClase_2.configure(pady="0")
        self.btnEconomicaClase_2.configure(text='''18''')

        self.btnEconomicaClase_2 = tk.Button(top)
        self.btnEconomicaClase_2.place(relx=0.652, rely=0.306, height=33
                , width=46)
        self.btnEconomicaClase_2.configure(activebackground="#ececec")
        self.btnEconomicaClase_2.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_2.configure(background="#0000ff")
        self.btnEconomicaClase_2.configure(compound='bottom')
        self.btnEconomicaClase_2.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_2.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_2.configure(foreground="#000000")
        self.btnEconomicaClase_2.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_2.configure(highlightcolor="black")
        self.btnEconomicaClase_2.configure(pady="0")
        self.btnEconomicaClase_2.configure(text='''19''')

        self.btnEconomicaClase_2 = tk.Button(top)
        self.btnEconomicaClase_2.place(relx=0.752, rely=0.306, height=33
                , width=46)
        self.btnEconomicaClase_2.configure(activebackground="#ececec")
        self.btnEconomicaClase_2.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_2.configure(background="#0000ff")
        self.btnEconomicaClase_2.configure(compound='bottom')
        self.btnEconomicaClase_2.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_2.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_2.configure(foreground="#000000")
        self.btnEconomicaClase_2.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_2.configure(highlightcolor="black")
        self.btnEconomicaClase_2.configure(pady="0")
        self.btnEconomicaClase_2.configure(text='''20''')

        self.btnEconomicaClase_21 = tk.Button(top)
        self.btnEconomicaClase_21.place(relx=0.099, rely=0.367, height=33
                , width=46)
        self.btnEconomicaClase_21.configure(activebackground="#ececec")
        self.btnEconomicaClase_21.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_21.configure(background="#0000ff")
        self.btnEconomicaClase_21.configure(compound='bottom')
        self.btnEconomicaClase_21.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_21.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_21.configure(foreground="#000000")
        self.btnEconomicaClase_21.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_21.configure(highlightcolor="black")
        self.btnEconomicaClase_21.configure(pady="0")
        self.btnEconomicaClase_21.configure(text='''21''')

        self.btnEconomicaClase_22 = tk.Button(top)
        self.btnEconomicaClase_22.place(relx=0.199, rely=0.367, height=33
                , width=46)
        self.btnEconomicaClase_22.configure(activebackground="#ececec")
        self.btnEconomicaClase_22.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_22.configure(background="#0000ff")
        self.btnEconomicaClase_22.configure(compound='bottom')
        self.btnEconomicaClase_22.configure(cursor="fleur")
        self.btnEconomicaClase_22.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_22.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_22.configure(foreground="#000000")
        self.btnEconomicaClase_22.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_22.configure(highlightcolor="black")
        self.btnEconomicaClase_22.configure(pady="0")
        self.btnEconomicaClase_22.configure(text='''22''')

        self.btnEconomicaClase_23 = tk.Button(top)
        self.btnEconomicaClase_23.place(relx=0.298, rely=0.367, height=33
                , width=46)
        self.btnEconomicaClase_23.configure(activebackground="#ececec")
        self.btnEconomicaClase_23.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_23.configure(background="#0000ff")
        self.btnEconomicaClase_23.configure(compound='bottom')
        self.btnEconomicaClase_23.configure(cursor="fleur")
        self.btnEconomicaClase_23.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_23.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_23.configure(foreground="#000000")
        self.btnEconomicaClase_23.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_23.configure(highlightcolor="black")
        self.btnEconomicaClase_23.configure(pady="0")
        self.btnEconomicaClase_23.configure(text='''23''')

        self.btnEconomicaClase_24 = tk.Button(top)
        self.btnEconomicaClase_24.place(relx=0.553, rely=0.367, height=33
                , width=46)
        self.btnEconomicaClase_24.configure(activebackground="#ececec")
        self.btnEconomicaClase_24.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_24.configure(background="#0000ff")
        self.btnEconomicaClase_24.configure(compound='bottom')
        self.btnEconomicaClase_24.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_24.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_24.configure(foreground="#000000")
        self.btnEconomicaClase_24.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_24.configure(highlightcolor="black")
        self.btnEconomicaClase_24.configure(pady="0")
        self.btnEconomicaClase_24.configure(text='''24''')

        self.btnEconomicaClase_25 = tk.Button(top)
        self.btnEconomicaClase_25.place(relx=0.652, rely=0.367, height=33
                , width=46)
        self.btnEconomicaClase_25.configure(activebackground="#ececec")
        self.btnEconomicaClase_25.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_25.configure(background="#0000ff")
        self.btnEconomicaClase_25.configure(compound='bottom')
        self.btnEconomicaClase_25.configure(cursor="fleur")
        self.btnEconomicaClase_25.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_25.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_25.configure(foreground="#000000")
        self.btnEconomicaClase_25.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_25.configure(highlightcolor="black")
        self.btnEconomicaClase_25.configure(pady="0")
        self.btnEconomicaClase_25.configure(text='''25''')

        self.btnEconomicaClase_26 = tk.Button(top)
        self.btnEconomicaClase_26.place(relx=0.752, rely=0.367, height=33
                , width=46)
        self.btnEconomicaClase_26.configure(activebackground="#ececec")
        self.btnEconomicaClase_26.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_26.configure(background="#0000ff")
        self.btnEconomicaClase_26.configure(compound='bottom')
        self.btnEconomicaClase_26.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_26.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_26.configure(foreground="#000000")
        self.btnEconomicaClase_26.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_26.configure(highlightcolor="black")
        self.btnEconomicaClase_26.configure(pady="0")
        self.btnEconomicaClase_26.configure(text='''26''')

if __name__ == '__main__':
    vp_start_gui()





