#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 18, 2020 08:12:38 PM -03  platform: Windows NT
#    Apr 18, 2020 11:38:17 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def init(top, gui, *args, **kwargs):
    global w, top_level, root,lista_ejecutiva,lista_economica
    w = gui
    top_level = top
    root = top
    lista_ejecutiva=[[w.asiento1,w.asiento5,w.asiento4,w.asiento8]
        ,[w.asiento2,w.asiento6,w.asiento3,w.asiento7]]
    lista_economica=[[w.asiento9,w.asiento15,w.asiento14,w.asiento20],
                     [w.asiento10,w.asiento16,w.asiento13,w.asiento19,],[w.asiento11,w.asiento17,w.asiento12,w.asiento18]]


def set_Tk_var():
    global cedulapasajero
    cedulapasajero = tk.StringVar()
    global nombre_pasajero
    nombre_pasajero = tk.StringVar()
    global ventanaU
    ventanaU = tk.IntVar()
    global clasesvuelos
    clasesvuelos = tk.StringVar()
    global selectedButton
    selectedButton = tk.IntVar()
    global centroU
    centroU = tk.IntVar()
    global pasilloU
    pasilloU = tk.IntVar()





def buscar_pasajero():
    print('avionproyecto_support.buscar_pasajero')
    sys.stdout.flush()

def eliminar_pasajero():
    print('avionproyecto_support.eliminar_pasajero')
    sys.stdout.flush()

def porcentaje_ocupacion():
    print('avionproyecto_support.porcentaje_ocupacion')
    sys.stdout.flush()
    print(len(lista_ejecutiva))

def registrar_pasajeros():
    ventana=lista_ejecutiva[0]
    print(len(ventana))
    for ubicacion in ventana:
        print(ubicacion)
        ventana[ubicacion].configure(background="red")

    print(len(lista_ejecutiva))
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import avionproyecto
    avionproyecto.vp_start_gui()





