#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 22, 2020 02:45:16 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import avionIrala_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    avionIrala_support.set_Tk_var()
    top = Toplevel1 (root)
    avionIrala_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    avionIrala_support.set_Tk_var()
    top = Toplevel1 (w)
    avionIrala_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 12 -weight bold -underline "  \
            "1"
        font11 = "-family {Segoe UI} -size 9 -underline 1"
        font9 = "-family {Segoe UI} -size 11 -weight bold"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("868x708+561+153")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.046, rely=0.071, relheight=0.709
                , relwidth=0.868)
        self.Canvas1.configure(background="#000000")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")

        self.Canvas2 = tk.Canvas(self.Canvas1)
        self.Canvas2.place(relx=0.404, rely=0.06, relheight=0.882
                , relwidth=0.166)
        self.Canvas2.configure(background="#808080")
        self.Canvas2.configure(borderwidth="2")
        self.Canvas2.configure(cursor="fleur")
        self.Canvas2.configure(insertbackground="black")
        self.Canvas2.configure(relief="ridge")
        self.Canvas2.configure(selectbackground="#c4c4c4")
        self.Canvas2.configure(selectforeground="black")

        self.lblAsiento2 = tk.Label(self.Canvas1)
        self.lblAsiento2.place(relx=0.228, rely=0.139, height=46, width=61)
        self.lblAsiento2.configure(activebackground="#f9f9f9")
        self.lblAsiento2.configure(activeforeground="black")
        self.lblAsiento2.configure(background="#ffff00")
        self.lblAsiento2.configure(disabledforeground="#a3a3a3")
        self.lblAsiento2.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento2.configure(foreground="#000000")
        self.lblAsiento2.configure(highlightbackground="#d9d9d9")
        self.lblAsiento2.configure(highlightcolor="#646464646464")
        self.lblAsiento2.configure(relief="groove")
        self.lblAsiento2.configure(text='''2''')

        self.lblAsiento3 = tk.Label(self.Canvas1)
        self.lblAsiento3.place(relx=0.606, rely=0.139, height=46, width=61)
        self.lblAsiento3.configure(activebackground="#f9f9f9")
        self.lblAsiento3.configure(activeforeground="black")
        self.lblAsiento3.configure(background="#ffff00")
        self.lblAsiento3.configure(disabledforeground="#a3a3a3")
        self.lblAsiento3.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento3.configure(foreground="#000000")
        self.lblAsiento3.configure(highlightbackground="#d9d9d9")
        self.lblAsiento3.configure(highlightcolor="#646464646464")
        self.lblAsiento3.configure(relief="groove")
        self.lblAsiento3.configure(text='''3''')

        self.lblAsiento4 = tk.Label(self.Canvas1)
        self.lblAsiento4.place(relx=0.726, rely=0.139, height=46, width=61)
        self.lblAsiento4.configure(activebackground="#f9f9f9")
        self.lblAsiento4.configure(activeforeground="black")
        self.lblAsiento4.configure(background="#ffff00")
        self.lblAsiento4.configure(disabledforeground="#a3a3a3")
        self.lblAsiento4.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento4.configure(foreground="#000000")
        self.lblAsiento4.configure(highlightbackground="#d9d9d9")
        self.lblAsiento4.configure(highlightcolor="#646464646464")
        self.lblAsiento4.configure(relief="groove")
        self.lblAsiento4.configure(text='''4''')

        self.lblAsiento5 = tk.Label(self.Canvas1)
        self.lblAsiento5.place(relx=0.108, rely=0.299, height=46, width=62)
        self.lblAsiento5.configure(activebackground="#f9f9f9")
        self.lblAsiento5.configure(activeforeground="black")
        self.lblAsiento5.configure(background="#ffff00")
        self.lblAsiento5.configure(disabledforeground="#a3a3a3")
        self.lblAsiento5.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento5.configure(foreground="#000000")
        self.lblAsiento5.configure(highlightbackground="#d9d9d9")
        self.lblAsiento5.configure(highlightcolor="#646464646464")
        self.lblAsiento5.configure(relief="groove")
        self.lblAsiento5.configure(text='''5''')

        self.lblAsiento6 = tk.Label(self.Canvas1)
        self.lblAsiento6.place(relx=0.228, rely=0.299, height=46, width=62)
        self.lblAsiento6.configure(activebackground="#f9f9f9")
        self.lblAsiento6.configure(activeforeground="black")
        self.lblAsiento6.configure(background="#ffff00")
        self.lblAsiento6.configure(disabledforeground="#a3a3a3")
        self.lblAsiento6.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento6.configure(foreground="#000000")
        self.lblAsiento6.configure(highlightbackground="#d9d9d9")
        self.lblAsiento6.configure(highlightcolor="#646464646464")
        self.lblAsiento6.configure(relief="groove")
        self.lblAsiento6.configure(text='''6''')

        self.lblAsiento7 = tk.Label(self.Canvas1)
        self.lblAsiento7.place(relx=0.606, rely=0.299, height=46, width=62)
        self.lblAsiento7.configure(activebackground="#f9f9f9")
        self.lblAsiento7.configure(activeforeground="black")
        self.lblAsiento7.configure(background="#ffff00")
        self.lblAsiento7.configure(disabledforeground="#a3a3a3")
        self.lblAsiento7.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento7.configure(foreground="#000000")
        self.lblAsiento7.configure(highlightbackground="#d9d9d9")
        self.lblAsiento7.configure(highlightcolor="#646464646464")
        self.lblAsiento7.configure(relief="groove")
        self.lblAsiento7.configure(text='''7''')

        self.lblAsiento8 = tk.Label(self.Canvas1)
        self.lblAsiento8.place(relx=0.726, rely=0.299, height=46, width=62)
        self.lblAsiento8.configure(activebackground="#f9f9f9")
        self.lblAsiento8.configure(activeforeground="black")
        self.lblAsiento8.configure(background="#ffff00")
        self.lblAsiento8.configure(disabledforeground="#a3a3a3")
        self.lblAsiento8.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento8.configure(foreground="#000000")
        self.lblAsiento8.configure(highlightbackground="#d9d9d9")
        self.lblAsiento8.configure(highlightcolor="#646464646464")
        self.lblAsiento8.configure(relief="groove")
        self.lblAsiento8.configure(text='''8''')

        self.lblAsiento9 = tk.Label(self.Canvas1)
        self.lblAsiento9.place(relx=0.066, rely=0.498, height=46, width=62)
        self.lblAsiento9.configure(activebackground="#f9f9f9")
        self.lblAsiento9.configure(activeforeground="black")
        self.lblAsiento9.configure(background="#ffff00")
        self.lblAsiento9.configure(cursor="fleur")
        self.lblAsiento9.configure(disabledforeground="#a3a3a3")
        self.lblAsiento9.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento9.configure(foreground="#000000")
        self.lblAsiento9.configure(highlightbackground="#d9d9d9")
        self.lblAsiento9.configure(highlightcolor="#646464646464")
        self.lblAsiento9.configure(relief="groove")
        self.lblAsiento9.configure(text='''9''')

        self.lblAsiento10 = tk.Label(self.Canvas1)
        self.lblAsiento10.place(relx=0.175, rely=0.498, height=46, width=62)
        self.lblAsiento10.configure(activebackground="#f9f9f9")
        self.lblAsiento10.configure(activeforeground="black")
        self.lblAsiento10.configure(background="#ffff00")
        self.lblAsiento10.configure(disabledforeground="#a3a3a3")
        self.lblAsiento10.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento10.configure(foreground="#000000")
        self.lblAsiento10.configure(highlightbackground="#d9d9d9")
        self.lblAsiento10.configure(highlightcolor="#646464646464")
        self.lblAsiento10.configure(relief="groove")
        self.lblAsiento10.configure(text='''10''')

        self.lblAsiento11 = tk.Label(self.Canvas1)
        self.lblAsiento11.place(relx=0.283, rely=0.498, height=46, width=62)
        self.lblAsiento11.configure(activebackground="#f9f9f9")
        self.lblAsiento11.configure(activeforeground="black")
        self.lblAsiento11.configure(background="#ffff00")
        self.lblAsiento11.configure(disabledforeground="#a3a3a3")
        self.lblAsiento11.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento11.configure(foreground="#000000")
        self.lblAsiento11.configure(highlightbackground="#d9d9d9")
        self.lblAsiento11.configure(highlightcolor="#646464646464")
        self.lblAsiento11.configure(relief="groove")
        self.lblAsiento11.configure(text='''11''')

        self.lblAsiento12 = tk.Label(self.Canvas1)
        self.lblAsiento12.place(relx=0.606, rely=0.518, height=46, width=62)
        self.lblAsiento12.configure(activebackground="#f9f9f9")
        self.lblAsiento12.configure(activeforeground="black")
        self.lblAsiento12.configure(background="#ffff00")
        self.lblAsiento12.configure(disabledforeground="#a3a3a3")
        self.lblAsiento12.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento12.configure(foreground="#000000")
        self.lblAsiento12.configure(highlightbackground="#d9d9d9")
        self.lblAsiento12.configure(highlightcolor="#646464646464")
        self.lblAsiento12.configure(relief="groove")
        self.lblAsiento12.configure(text='''12''')

        self.lblAsiento13 = tk.Label(self.Canvas1)
        self.lblAsiento13.place(relx=0.713, rely=0.518, height=46, width=62)
        self.lblAsiento13.configure(activebackground="#f9f9f9")
        self.lblAsiento13.configure(activeforeground="black")
        self.lblAsiento13.configure(background="#ffff00")
        self.lblAsiento13.configure(disabledforeground="#a3a3a3")
        self.lblAsiento13.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento13.configure(foreground="#000000")
        self.lblAsiento13.configure(highlightbackground="#d9d9d9")
        self.lblAsiento13.configure(highlightcolor="#646464646464")
        self.lblAsiento13.configure(relief="groove")
        self.lblAsiento13.configure(text='''13''')

        self.lblAsiento14 = tk.Label(self.Canvas1)
        self.lblAsiento14.place(relx=0.821, rely=0.518, height=46, width=62)
        self.lblAsiento14.configure(activebackground="#f9f9f9")
        self.lblAsiento14.configure(activeforeground="black")
        self.lblAsiento14.configure(background="#ffff00")
        self.lblAsiento14.configure(disabledforeground="#a3a3a3")
        self.lblAsiento14.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento14.configure(foreground="#000000")
        self.lblAsiento14.configure(highlightbackground="#d9d9d9")
        self.lblAsiento14.configure(highlightcolor="#646464646464")
        self.lblAsiento14.configure(relief="groove")
        self.lblAsiento14.configure(text='''14''')

        self.lblAsiento15 = tk.Label(self.Canvas1)
        self.lblAsiento15.place(relx=0.066, rely=0.657, height=46, width=61)
        self.lblAsiento15.configure(activebackground="#f9f9f9")
        self.lblAsiento15.configure(activeforeground="black")
        self.lblAsiento15.configure(background="#ffff00")
        self.lblAsiento15.configure(disabledforeground="#a3a3a3")
        self.lblAsiento15.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento15.configure(foreground="#000000")
        self.lblAsiento15.configure(highlightbackground="#d9d9d9")
        self.lblAsiento15.configure(highlightcolor="#646464646464")
        self.lblAsiento15.configure(relief="groove")
        self.lblAsiento15.configure(text='''15''')

        self.lblAsiento16 = tk.Label(self.Canvas1)
        self.lblAsiento16.place(relx=0.173, rely=0.657, height=46, width=62)
        self.lblAsiento16.configure(activebackground="#f9f9f9")
        self.lblAsiento16.configure(activeforeground="black")
        self.lblAsiento16.configure(background="#ffff00")
        self.lblAsiento16.configure(disabledforeground="#a3a3a3")
        self.lblAsiento16.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento16.configure(foreground="#000000")
        self.lblAsiento16.configure(highlightbackground="#d9d9d9")
        self.lblAsiento16.configure(highlightcolor="#646464646464")
        self.lblAsiento16.configure(relief="groove")
        self.lblAsiento16.configure(text='''16''')

        self.lblAsiento17 = tk.Label(self.Canvas1)
        self.lblAsiento17.place(relx=0.283, rely=0.657, height=46, width=62)
        self.lblAsiento17.configure(activebackground="#f9f9f9")
        self.lblAsiento17.configure(activeforeground="black")
        self.lblAsiento17.configure(background="#ffff00")
        self.lblAsiento17.configure(disabledforeground="#a3a3a3")
        self.lblAsiento17.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento17.configure(foreground="#000000")
        self.lblAsiento17.configure(highlightbackground="#d9d9d9")
        self.lblAsiento17.configure(highlightcolor="#646464646464")
        self.lblAsiento17.configure(relief="groove")
        self.lblAsiento17.configure(text='''17''')

        self.lblAsiento18 = tk.Label(self.Canvas1)
        self.lblAsiento18.place(relx=0.606, rely=0.657, height=46, width=62)
        self.lblAsiento18.configure(activebackground="#f9f9f9")
        self.lblAsiento18.configure(activeforeground="black")
        self.lblAsiento18.configure(background="#ffff00")
        self.lblAsiento18.configure(disabledforeground="#a3a3a3")
        self.lblAsiento18.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento18.configure(foreground="#000000")
        self.lblAsiento18.configure(highlightbackground="#d9d9d9")
        self.lblAsiento18.configure(highlightcolor="#646464646464")
        self.lblAsiento18.configure(relief="groove")
        self.lblAsiento18.configure(text='''18''')

        self.lblAsiento19 = tk.Label(self.Canvas1)
        self.lblAsiento19.place(relx=0.713, rely=0.657, height=46, width=62)
        self.lblAsiento19.configure(activebackground="#f9f9f9")
        self.lblAsiento19.configure(activeforeground="black")
        self.lblAsiento19.configure(background="#ffff00")
        self.lblAsiento19.configure(disabledforeground="#a3a3a3")
        self.lblAsiento19.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento19.configure(foreground="#000000")
        self.lblAsiento19.configure(highlightbackground="#d9d9d9")
        self.lblAsiento19.configure(highlightcolor="#646464646464")
        self.lblAsiento19.configure(relief="groove")
        self.lblAsiento19.configure(text='''19''')

        self.lblAsiento20 = tk.Label(self.Canvas1)
        self.lblAsiento20.place(relx=0.821, rely=0.657, height=46, width=62)
        self.lblAsiento20.configure(activebackground="#f9f9f9")
        self.lblAsiento20.configure(activeforeground="black")
        self.lblAsiento20.configure(background="#ffff00")
        self.lblAsiento20.configure(disabledforeground="#a3a3a3")
        self.lblAsiento20.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento20.configure(foreground="#000000")
        self.lblAsiento20.configure(highlightbackground="#d9d9d9")
        self.lblAsiento20.configure(highlightcolor="#646464646464")
        self.lblAsiento20.configure(relief="groove")
        self.lblAsiento20.configure(text='''20''')

        self.lblAsiento1 = tk.Label(top)
        self.lblAsiento1.place(relx=0.15, rely=0.169, height=46, width=60)
        self.lblAsiento1.configure(activebackground="#f9f9f9")
        self.lblAsiento1.configure(activeforeground="black")
        self.lblAsiento1.configure(background="#ffff00")
        self.lblAsiento1.configure(disabledforeground="#a3a3a3")
        self.lblAsiento1.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblAsiento1.configure(foreground="#000000")
        self.lblAsiento1.configure(highlightbackground="#d9d9d9")
        self.lblAsiento1.configure(highlightcolor="#646464646464")
        self.lblAsiento1.configure(relief="groove")
        self.lblAsiento1.configure(text='''1''')

        self.lblTitulo = tk.Label(top)
        self.lblTitulo.place(relx=0.046, rely=0.014, height=26, width=212)
        self.lblTitulo.configure(background="#d9d9d9")
        self.lblTitulo.configure(disabledforeground="#a3a3a3")
        self.lblTitulo.configure(font=font10)
        self.lblTitulo.configure(foreground="#000000")
        self.lblTitulo.configure(text='''Venta de Pasajes''')

        self.lblReferencia1 = tk.Label(top)
        self.lblReferencia1.place(relx=0.357, rely=0.014, height=36, width=81)
        self.lblReferencia1.configure(background="#ffff00")
        self.lblReferencia1.configure(disabledforeground="#a3a3a3")
        self.lblReferencia1.configure(font=font9)
        self.lblReferencia1.configure(foreground="#000000")
        self.lblReferencia1.configure(relief="groove")
        self.lblReferencia1.configure(text='''LIBRE''')

        self.lblReferencia2 = tk.Label(top)
        self.lblReferencia2.place(relx=0.507, rely=0.014, height=36, width=101)
        self.lblReferencia2.configure(activebackground="#f9f9f9")
        self.lblReferencia2.configure(activeforeground="black")
        self.lblReferencia2.configure(background="#ff0000")
        self.lblReferencia2.configure(disabledforeground="#a3a3a3")
        self.lblReferencia2.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblReferencia2.configure(foreground="#000000")
        self.lblReferencia2.configure(highlightbackground="#d9d9d9")
        self.lblReferencia2.configure(highlightcolor="black")
        self.lblReferencia2.configure(relief="groove")
        self.lblReferencia2.configure(text='''OCUPADO''')

        self.Canvas3 = tk.Canvas(top)
        self.Canvas3.place(relx=0.0, rely=0.763, relheight=0.23, relwidth=0.994)
        self.Canvas3.configure(background="#d9d9d9")
        self.Canvas3.configure(borderwidth="2")
        self.Canvas3.configure(insertbackground="black")
        self.Canvas3.configure(relief="ridge")
        self.Canvas3.configure(selectbackground="#c4c4c4")
        self.Canvas3.configure(selectforeground="black")

        self.lblNombre = tk.Label(self.Canvas3)
        self.lblNombre.place(relx=0.012, rely=0.067, height=27, width=64)
        self.lblNombre.configure(anchor='s')
        self.lblNombre.configure(background="#d9d9d9")
        self.lblNombre.configure(disabledforeground="#a3a3a3")
        self.lblNombre.configure(font=font11)
        self.lblNombre.configure(foreground="#000000")
        self.lblNombre.configure(text='''Nombre:''')

        self.lblDni = tk.Label(self.Canvas3)
        self.lblDni.place(relx=0.012, rely=0.264, height=27, width=64)
        self.lblDni.configure(activebackground="#f9f9f9")
        self.lblDni.configure(activeforeground="black")
        self.lblDni.configure(anchor='s')
        self.lblDni.configure(background="#d9d9d9")
        self.lblDni.configure(cursor="fleur")
        self.lblDni.configure(disabledforeground="#a3a3a3")
        self.lblDni.configure(font="-family {Segoe UI} -size 9 -underline 1")
        self.lblDni.configure(foreground="#000000")
        self.lblDni.configure(highlightbackground="#d9d9d9")
        self.lblDni.configure(highlightcolor="black")
        self.lblDni.configure(text='''D.N.I:''')

        self.lblClase = tk.Label(self.Canvas3)
        self.lblClase.place(relx=0.012, rely=0.429, height=28, width=63)
        self.lblClase.configure(activebackground="#f9f9f9")
        self.lblClase.configure(activeforeground="black")
        self.lblClase.configure(anchor='s')
        self.lblClase.configure(background="#d9d9d9")
        self.lblClase.configure(disabledforeground="#a3a3a3")
        self.lblClase.configure(font="-family {Segoe UI} -size 9 -underline 1")
        self.lblClase.configure(foreground="#000000")
        self.lblClase.configure(highlightbackground="#d9d9d9")
        self.lblClase.configure(highlightcolor="black")
        self.lblClase.configure(text='''Clase:''')

        self.lblUbicacion = tk.Label(self.Canvas3)
        self.lblUbicacion.place(relx=0.012, rely=0.613, height=28, width=75)
        self.lblUbicacion.configure(activebackground="#f9f9f9")
        self.lblUbicacion.configure(activeforeground="black")
        self.lblUbicacion.configure(anchor='s')
        self.lblUbicacion.configure(background="#d9d9d9")
        self.lblUbicacion.configure(disabledforeground="#a3a3a3")
        self.lblUbicacion.configure(font="-family {Segoe UI} -size 9 -underline 1")
        self.lblUbicacion.configure(foreground="#000000")
        self.lblUbicacion.configure(highlightbackground="#d9d9d9")
        self.lblUbicacion.configure(highlightcolor="black")
        self.lblUbicacion.configure(text='''Ubicacion:''')

        self.EntNombre = tk.Entry(self.Canvas3)
        self.EntNombre.place(relx=0.104, rely=0.067,height=24, relwidth=0.202)
        self.EntNombre.configure(background="white")
        self.EntNombre.configure(disabledforeground="#a3a3a3")
        self.EntNombre.configure(font="TkFixedFont")
        self.EntNombre.configure(foreground="#000000")
        self.EntNombre.configure(insertbackground="black")
        self.EntNombre.configure(textvariable=avionIrala_support.nombre)

        self.EntDni = tk.Entry(self.Canvas3)
        self.EntDni.place(relx=0.104, rely=0.264,height=24, relwidth=0.202)
        self.EntDni.configure(background="white")
        self.EntDni.configure(disabledforeground="#a3a3a3")
        self.EntDni.configure(font="TkFixedFont")
        self.EntDni.configure(foreground="#000000")
        self.EntDni.configure(highlightbackground="#d9d9d9")
        self.EntDni.configure(highlightcolor="black")
        self.EntDni.configure(insertbackground="black")
        self.EntDni.configure(selectbackground="#c4c4c4")
        self.EntDni.configure(selectforeground="black")
        self.EntDni.configure(textvariable=avionIrala_support.dni)

        self.TComboboxClase = ttk.Combobox(self.Canvas3)
        self.TComboboxClase.place(relx=0.105, rely=0.454, relheight=0.129
                , relwidth=0.212)
        self.value_list = ['Ejecutiva','Economica',]
        self.TComboboxClase.configure(values=self.value_list)
        self.TComboboxClase.configure(textvariable=avionIrala_support.clase)
        self.TComboboxClase.configure(takefocus="")

        self.TComboboxUbicacion = ttk.Combobox(self.Canvas3)
        self.TComboboxUbicacion.place(relx=0.104, rely=0.65, relheight=0.129
                , relwidth=0.213)
        self.value_list = ['Ventana','Centro','Pasillo',]
        self.TComboboxUbicacion.configure(values=self.value_list)
        self.TComboboxUbicacion.configure(textvariable=avionIrala_support.ubicacion)
        self.TComboboxUbicacion.configure(takefocus="")

        self.btnRegistrar = ttk.Button(self.Canvas3)
        self.btnRegistrar.place(relx=0.127, rely=0.798, height=30, width=129)
        self.btnRegistrar.configure(command=avionIrala_support.registrarPasajero)
        self.btnRegistrar.configure(takefocus="")
        self.btnRegistrar.configure(text='''Registrar Pasajero''')

        self.lblDniEliminar = tk.Label(self.Canvas3)
        self.lblDniEliminar.place(relx=0.406, rely=0.061, height=27, width=64)
        self.lblDniEliminar.configure(activebackground="#f9f9f9")
        self.lblDniEliminar.configure(activeforeground="black")
        self.lblDniEliminar.configure(anchor='s')
        self.lblDniEliminar.configure(background="#d9d9d9")
        self.lblDniEliminar.configure(disabledforeground="#a3a3a3")
        self.lblDniEliminar.configure(font="-family {Segoe UI} -size 9 -underline 1")
        self.lblDniEliminar.configure(foreground="#000000")
        self.lblDniEliminar.configure(highlightbackground="#d9d9d9")
        self.lblDniEliminar.configure(highlightcolor="black")
        self.lblDniEliminar.configure(text='''D.N.I:''')

        self.EntDniElimBuscar = tk.Entry(self.Canvas3)
        self.EntDniElimBuscar.place(relx=0.487, rely=0.061, height=24
                , relwidth=0.306)
        self.EntDniElimBuscar.configure(background="white")
        self.EntDniElimBuscar.configure(disabledforeground="#a3a3a3")
        self.EntDniElimBuscar.configure(font="TkFixedFont")
        self.EntDniElimBuscar.configure(foreground="#000000")
        self.EntDniElimBuscar.configure(highlightbackground="#d9d9d9")
        self.EntDniElimBuscar.configure(highlightcolor="black")
        self.EntDniElimBuscar.configure(insertbackground="black")
        self.EntDniElimBuscar.configure(selectbackground="#c4c4c4")
        self.EntDniElimBuscar.configure(selectforeground="black")
        self.EntDniElimBuscar.configure(textvariable=avionIrala_support.dniEliminarBuscar)

        self.btnEliminar = ttk.Button(self.Canvas3)
        self.btnEliminar.place(relx=0.487, rely=0.245, height=30, width=129)
        self.btnEliminar.configure(command=avionIrala_support.eliminarPasajero)
        self.btnEliminar.configure(takefocus="")
        self.btnEliminar.configure(text='''Eliminar Pasajero''')

        self.btnBuscarPasajero = ttk.Button(self.Canvas3)
        self.btnBuscarPasajero.place(relx=0.649, rely=0.245, height=30
                , width=129)
        self.btnBuscarPasajero.configure(command=avionIrala_support.buscarPasajero)
        self.btnBuscarPasajero.configure(takefocus="")
        self.btnBuscarPasajero.configure(text='''Buscar Pasajero''')

        self.btnPromedioOcupacion = ttk.Button(self.Canvas3)
        self.btnPromedioOcupacion.place(relx=0.487, rely=0.491, height=30
                , width=169)
        self.btnPromedioOcupacion.configure(command=avionIrala_support.promedioOcupacion)
        self.btnPromedioOcupacion.configure(takefocus="")
        self.btnPromedioOcupacion.configure(text='''Promedio de ocupacion''')

if __name__ == '__main__':
    vp_start_gui()





