#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 15, 2020 06:56:01 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import avion_irala_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = pasajesAvion (root)
    avion_irala_support.init(root, top)
    root.mainloop()

w = None
def create_pasajesAvion(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_pasajesAvion(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = pasajesAvion (w)
    avion_irala_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_pasajesAvion():
    global w
    w.destroy()
    w = None

class pasajesAvion:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family {Yu Gothic UI Semibold} -size 12 -weight bold"  \
            ""
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("721x739+627+98")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Venta de Pasajes")
        top.configure(background="#d9d9d9")

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.397, rely=0.061, relheight=0.311
                , relwidth=0.133)
        self.Canvas1.configure(background="#757575")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#400000")
        self.Canvas1.configure(highlightcolor="#424143")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")

        self.btnPrimeraClase = tk.Button(top)
        self.btnPrimeraClase.place(relx=0.184, rely=0.087, height=33, width=46)
        self.btnPrimeraClase.configure(activebackground="#ececec")
        self.btnPrimeraClase.configure(activeforeground="#ff0000")
        self.btnPrimeraClase.configure(background="#ffff00")
        self.btnPrimeraClase.configure(compound='bottom')
        self.btnPrimeraClase.configure(cursor="fleur")
        self.btnPrimeraClase.configure(disabledforeground="#a3a3a3")
        self.btnPrimeraClase.configure(font=font9)
        self.btnPrimeraClase.configure(foreground="#000000")
        self.btnPrimeraClase.configure(highlightbackground="#d9d9d9")
        self.btnPrimeraClase.configure(highlightcolor="black")
        self.btnPrimeraClase.configure(pady="0")
        self.btnPrimeraClase.configure(text='''1''')

        self.btnPrimeraClase_2 = tk.Button(top)
        self.btnPrimeraClase_2.place(relx=0.284, rely=0.087, height=33, width=46)

        self.btnPrimeraClase_2.configure(activebackground="#ececec")
        self.btnPrimeraClase_2.configure(activeforeground="#ff0000")
        self.btnPrimeraClase_2.configure(background="#ffff00")
        self.btnPrimeraClase_2.configure(compound='bottom')
        self.btnPrimeraClase_2.configure(disabledforeground="#a3a3a3")
        self.btnPrimeraClase_2.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnPrimeraClase_2.configure(foreground="#000000")
        self.btnPrimeraClase_2.configure(highlightbackground="#d9d9d9")
        self.btnPrimeraClase_2.configure(highlightcolor="black")
        self.btnPrimeraClase_2.configure(pady="0")
        self.btnPrimeraClase_2.configure(text='''2''')

        self.btnPrimeraClase_3 = tk.Button(top)
        self.btnPrimeraClase_3.place(relx=0.581, rely=0.087, height=33, width=46)

        self.btnPrimeraClase_3.configure(activebackground="#ececec")
        self.btnPrimeraClase_3.configure(activeforeground="#ff0000")
        self.btnPrimeraClase_3.configure(background="#ffff00")
        self.btnPrimeraClase_3.configure(compound='bottom')
        self.btnPrimeraClase_3.configure(disabledforeground="#a3a3a3")
        self.btnPrimeraClase_3.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnPrimeraClase_3.configure(foreground="#000000")
        self.btnPrimeraClase_3.configure(highlightbackground="#d9d9d9")
        self.btnPrimeraClase_3.configure(highlightcolor="black")
        self.btnPrimeraClase_3.configure(pady="0")
        self.btnPrimeraClase_3.configure(text='''3''')

        self.btnPrimeraClase_4 = tk.Button(top)
        self.btnPrimeraClase_4.place(relx=0.681, rely=0.087, height=33, width=46)

        self.btnPrimeraClase_4.configure(activebackground="#ececec")
        self.btnPrimeraClase_4.configure(activeforeground="#ff0000")
        self.btnPrimeraClase_4.configure(background="#ffff00")
        self.btnPrimeraClase_4.configure(compound='bottom')
        self.btnPrimeraClase_4.configure(disabledforeground="#a3a3a3")
        self.btnPrimeraClase_4.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnPrimeraClase_4.configure(foreground="#000000")
        self.btnPrimeraClase_4.configure(highlightbackground="#d9d9d9")
        self.btnPrimeraClase_4.configure(highlightcolor="black")
        self.btnPrimeraClase_4.configure(pady="0")
        self.btnPrimeraClase_4.configure(text='''4''')

        self.btnPrimeraClase_5 = tk.Button(top)
        self.btnPrimeraClase_5.place(relx=0.184, rely=0.16, height=33, width=46)
        self.btnPrimeraClase_5.configure(activebackground="#ececec")
        self.btnPrimeraClase_5.configure(activeforeground="#ff0000")
        self.btnPrimeraClase_5.configure(background="#ffff00")
        self.btnPrimeraClase_5.configure(compound='bottom')
        self.btnPrimeraClase_5.configure(disabledforeground="#a3a3a3")
        self.btnPrimeraClase_5.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnPrimeraClase_5.configure(foreground="#000000")
        self.btnPrimeraClase_5.configure(highlightbackground="#d9d9d9")
        self.btnPrimeraClase_5.configure(highlightcolor="black")
        self.btnPrimeraClase_5.configure(pady="0")
        self.btnPrimeraClase_5.configure(text='''5''')

        self.btnPrimeraClase_6 = tk.Button(top)
        self.btnPrimeraClase_6.place(relx=0.284, rely=0.16, height=33, width=46)
        self.btnPrimeraClase_6.configure(activebackground="#ececec")
        self.btnPrimeraClase_6.configure(activeforeground="#ff0000")
        self.btnPrimeraClase_6.configure(background="#ffff00")
        self.btnPrimeraClase_6.configure(compound='bottom')
        self.btnPrimeraClase_6.configure(disabledforeground="#a3a3a3")
        self.btnPrimeraClase_6.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnPrimeraClase_6.configure(foreground="#000000")
        self.btnPrimeraClase_6.configure(highlightbackground="#d9d9d9")
        self.btnPrimeraClase_6.configure(highlightcolor="black")
        self.btnPrimeraClase_6.configure(pady="0")
        self.btnPrimeraClase_6.configure(text='''6''')

        self.btnPrimeraClase_8 = tk.Button(top)
        self.btnPrimeraClase_8.place(relx=0.681, rely=0.16, height=33, width=46)
        self.btnPrimeraClase_8.configure(activebackground="#ececec")
        self.btnPrimeraClase_8.configure(activeforeground="#ff0000")
        self.btnPrimeraClase_8.configure(background="#ffff00")
        self.btnPrimeraClase_8.configure(compound='bottom')
        self.btnPrimeraClase_8.configure(disabledforeground="#a3a3a3")
        self.btnPrimeraClase_8.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnPrimeraClase_8.configure(foreground="#000000")
        self.btnPrimeraClase_8.configure(highlightbackground="#d9d9d9")
        self.btnPrimeraClase_8.configure(highlightcolor="black")
        self.btnPrimeraClase_8.configure(pady="0")
        self.btnPrimeraClase_8.configure(text='''8''')

        self.btnEconomicaClase_9 = tk.Button(top)
        self.btnEconomicaClase_9.place(relx=0.098, rely=0.245, height=33
                , width=46)
        self.btnEconomicaClase_9.configure(activebackground="#ececec")
        self.btnEconomicaClase_9.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_9.configure(background="#0000ff")
        self.btnEconomicaClase_9.configure(compound='bottom')
        self.btnEconomicaClase_9.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_9.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_9.configure(foreground="#000000")
        self.btnEconomicaClase_9.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_9.configure(highlightcolor="black")
        self.btnEconomicaClase_9.configure(pady="0")
        self.btnEconomicaClase_9.configure(text='''9''')

        self.btnEconomicaClase_10 = tk.Button(top)
        self.btnEconomicaClase_10.place(relx=0.198, rely=0.245, height=33
                , width=46)
        self.btnEconomicaClase_10.configure(activebackground="#ececec")
        self.btnEconomicaClase_10.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_10.configure(background="#0000ff")
        self.btnEconomicaClase_10.configure(compound='bottom')
        self.btnEconomicaClase_10.configure(cursor="fleur")
        self.btnEconomicaClase_10.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_10.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_10.configure(foreground="#000000")
        self.btnEconomicaClase_10.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_10.configure(highlightcolor="black")
        self.btnEconomicaClase_10.configure(pady="0")
        self.btnEconomicaClase_10.configure(text='''10''')

        self.btnEconomicaClase_11 = tk.Button(top)
        self.btnEconomicaClase_11.place(relx=0.298, rely=0.244, height=33
                , width=46)
        self.btnEconomicaClase_11.configure(activebackground="#ececec")
        self.btnEconomicaClase_11.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_11.configure(background="#0000ff")
        self.btnEconomicaClase_11.configure(compound='bottom')
        self.btnEconomicaClase_11.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_11.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_11.configure(foreground="#000000")
        self.btnEconomicaClase_11.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_11.configure(highlightcolor="black")
        self.btnEconomicaClase_11.configure(pady="0")
        self.btnEconomicaClase_11.configure(text='''11''')

        self.btnEconomicaClase_12 = tk.Button(top)
        self.btnEconomicaClase_12.place(relx=0.555, rely=0.244, height=33
                , width=46)
        self.btnEconomicaClase_12.configure(activebackground="#ececec")
        self.btnEconomicaClase_12.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_12.configure(background="#0000ff")
        self.btnEconomicaClase_12.configure(compound='bottom')
        self.btnEconomicaClase_12.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_12.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_12.configure(foreground="#000000")
        self.btnEconomicaClase_12.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_12.configure(highlightcolor="black")
        self.btnEconomicaClase_12.configure(pady="0")
        self.btnEconomicaClase_12.configure(text='''12''')

        self.btnEconomicaClase_13 = tk.Button(top)
        self.btnEconomicaClase_13.place(relx=0.655, rely=0.244, height=33
                , width=46)
        self.btnEconomicaClase_13.configure(activebackground="#ececec")
        self.btnEconomicaClase_13.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_13.configure(background="#0000ff")
        self.btnEconomicaClase_13.configure(compound='bottom')
        self.btnEconomicaClase_13.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_13.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_13.configure(foreground="#000000")
        self.btnEconomicaClase_13.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_13.configure(highlightcolor="black")
        self.btnEconomicaClase_13.configure(pady="0")
        self.btnEconomicaClase_13.configure(text='''13''')

        self.btnEconomicaClase_14 = tk.Button(top)
        self.btnEconomicaClase_14.place(relx=0.755, rely=0.244, height=33
                , width=46)
        self.btnEconomicaClase_14.configure(activebackground="#ececec")
        self.btnEconomicaClase_14.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_14.configure(background="#0000ff")
        self.btnEconomicaClase_14.configure(compound='bottom')
        self.btnEconomicaClase_14.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_14.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_14.configure(foreground="#000000")
        self.btnEconomicaClase_14.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_14.configure(highlightcolor="black")
        self.btnEconomicaClase_14.configure(pady="0")
        self.btnEconomicaClase_14.configure(text='''14''')

        self.btnEconomicaClase_15 = tk.Button(top)
        self.btnEconomicaClase_15.place(relx=0.097, rely=0.311, height=33
                , width=46)
        self.btnEconomicaClase_15.configure(activebackground="#ececec")
        self.btnEconomicaClase_15.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_15.configure(background="#0000ff")
        self.btnEconomicaClase_15.configure(compound='bottom')
        self.btnEconomicaClase_15.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_15.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_15.configure(foreground="#000000")
        self.btnEconomicaClase_15.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_15.configure(highlightcolor="black")
        self.btnEconomicaClase_15.configure(pady="0")
        self.btnEconomicaClase_15.configure(text='''15''')

        self.btnEconomicaClase_16 = tk.Button(top)
        self.btnEconomicaClase_16.place(relx=0.198, rely=0.311, height=33
                , width=46)
        self.btnEconomicaClase_16.configure(activebackground="#ececec")
        self.btnEconomicaClase_16.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_16.configure(background="#0000ff")
        self.btnEconomicaClase_16.configure(compound='bottom')
        self.btnEconomicaClase_16.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_16.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_16.configure(foreground="#000000")
        self.btnEconomicaClase_16.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_16.configure(highlightcolor="black")
        self.btnEconomicaClase_16.configure(pady="0")
        self.btnEconomicaClase_16.configure(text='''16''')

        self.btnEconomicaClase_17 = tk.Button(top)
        self.btnEconomicaClase_17.place(relx=0.298, rely=0.311, height=33
                , width=46)
        self.btnEconomicaClase_17.configure(activebackground="#ececec")
        self.btnEconomicaClase_17.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_17.configure(background="#0000ff")
        self.btnEconomicaClase_17.configure(compound='bottom')
        self.btnEconomicaClase_17.configure(cursor="fleur")
        self.btnEconomicaClase_17.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_17.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_17.configure(foreground="#000000")
        self.btnEconomicaClase_17.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_17.configure(highlightcolor="black")
        self.btnEconomicaClase_17.configure(pady="0")
        self.btnEconomicaClase_17.configure(text='''17''')

        self.btnEconomicaClase_18 = tk.Button(top)
        self.btnEconomicaClase_18.place(relx=0.556, rely=0.311, height=33
                , width=46)
        self.btnEconomicaClase_18.configure(activebackground="#ececec")
        self.btnEconomicaClase_18.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_18.configure(background="#0000ff")
        self.btnEconomicaClase_18.configure(compound='bottom')
        self.btnEconomicaClase_18.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_18.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_18.configure(foreground="#000000")
        self.btnEconomicaClase_18.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_18.configure(highlightcolor="black")
        self.btnEconomicaClase_18.configure(pady="0")
        self.btnEconomicaClase_18.configure(text='''18''')

        self.btnEconomicaClase_19 = tk.Button(top)
        self.btnEconomicaClase_19.place(relx=0.655, rely=0.311, height=33
                , width=46)
        self.btnEconomicaClase_19.configure(activebackground="#ececec")
        self.btnEconomicaClase_19.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_19.configure(background="#0000ff")
        self.btnEconomicaClase_19.configure(compound='bottom')
        self.btnEconomicaClase_19.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_19.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_19.configure(foreground="#000000")
        self.btnEconomicaClase_19.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_19.configure(highlightcolor="black")
        self.btnEconomicaClase_19.configure(pady="0")
        self.btnEconomicaClase_19.configure(text='''19''')

        self.btnEconomicaClase_20 = tk.Button(top)
        self.btnEconomicaClase_20.place(relx=0.755, rely=0.311, height=33
                , width=46)
        self.btnEconomicaClase_20.configure(activebackground="#ececec")
        self.btnEconomicaClase_20.configure(activeforeground="#ff0000")
        self.btnEconomicaClase_20.configure(background="#0000ff")
        self.btnEconomicaClase_20.configure(compound='bottom')
        self.btnEconomicaClase_20.configure(disabledforeground="#a3a3a3")
        self.btnEconomicaClase_20.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnEconomicaClase_20.configure(foreground="#000000")
        self.btnEconomicaClase_20.configure(highlightbackground="#d9d9d9")
        self.btnEconomicaClase_20.configure(highlightcolor="black")
        self.btnEconomicaClase_20.configure(pady="0")
        self.btnEconomicaClase_20.configure(text='''20''')

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=0.057, rely=0.024, relheight=0.49)
        self.TSeparator1.configure(orient="vertical")

        self.TSeparator1_9 = ttk.Separator(top)
        self.TSeparator1_9.place(relx=0.865, rely=0.024, relheight=0.49)
        self.TSeparator1_9.configure(orient="vertical")

        self.TSeparator2 = ttk.Separator(top)
        self.TSeparator2.place(relx=0.057, rely=0.024, relwidth=0.809)

        self.TSeparator2_10 = ttk.Separator(top)
        self.TSeparator2_10.place(relx=0.055, rely=0.392, relwidth=0.809)

        self.btnPrimeraClase_7 = tk.Button(top)
        self.btnPrimeraClase_7.place(relx=0.583, rely=0.16, height=33, width=46)
        self.btnPrimeraClase_7.configure(activebackground="#ececec")
        self.btnPrimeraClase_7.configure(activeforeground="#ff0000")
        self.btnPrimeraClase_7.configure(background="#ffff00")
        self.btnPrimeraClase_7.configure(compound='bottom')
        self.btnPrimeraClase_7.configure(disabledforeground="#a3a3a3")
        self.btnPrimeraClase_7.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold")
        self.btnPrimeraClase_7.configure(foreground="#000000")
        self.btnPrimeraClase_7.configure(highlightbackground="#d9d9d9")
        self.btnPrimeraClase_7.configure(highlightcolor="black")
        self.btnPrimeraClase_7.configure(pady="0")
        self.btnPrimeraClase_7.configure(text='''7''')

        self.TSeparator2_11 = ttk.Separator(top)
        self.TSeparator2_11.place(relx=0.055, rely=0.514, relwidth=0.809)
        self.TSeparator2_11.configure(cursor="fleur")

        self.btnRegistrarPasajero = ttk.Button(top)
        self.btnRegistrarPasajero.place(relx=0.069, rely=0.419, height=30
                , width=168)
        self.btnRegistrarPasajero.configure(takefocus="")
        self.btnRegistrarPasajero.configure(text='''Registrar pasajero''')
        self.btnRegistrarPasajero.configure(compound='center')

        self.btnEliminarPasajero = ttk.Button(top)
        self.btnEliminarPasajero.place(relx=0.347, rely=0.419, height=30
                , width=168)
        self.btnEliminarPasajero.configure(takefocus="")
        self.btnEliminarPasajero.configure(text='''Eliminar pasajero''')

        self.btnBuscarPasajero = ttk.Button(top)
        self.btnBuscarPasajero.place(relx=0.61, rely=0.419, height=30, width=168)

        self.btnBuscarPasajero.configure(takefocus="")
        self.btnBuscarPasajero.configure(text='''Buscar pasajero''')

        self.btnPorcentajeOcupacion = ttk.Button(top)
        self.btnPorcentajeOcupacion.place(relx=0.069, rely=0.46, height=30
                , width=168)
        self.btnPorcentajeOcupacion.configure(takefocus="")
        self.btnPorcentajeOcupacion.configure(text='''Porcentaje Ocupacion''')

        self.btnOpcion1 = ttk.Button(top)
        self.btnOpcion1.place(relx=0.347, rely=0.46, height=30, width=168)
        self.btnOpcion1.configure(takefocus="")
        self.btnOpcion1.configure(text='''Opcion 1''')

        self.btnOpcion2 = ttk.Button(top)
        self.btnOpcion2.place(relx=0.61, rely=0.46, height=30, width=168)
        self.btnOpcion2.configure(takefocus="")
        self.btnOpcion2.configure(text='''Opcion 2''')

if __name__ == '__main__':
    vp_start_gui()





