#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 14, 2020 11:24:48 AM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global cantidadViajeros
    cantidadViajeros = tk.StringVar()
    global rButton
    rButton = tk.StringVar()
    global distancia
    distancia = tk.StringVar()
    global precio
    precio = tk.StringVar()
    global totalPagar
    totalPagar = tk.StringVar()
    totalPagar.set('')
    global check
    check = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def calculoImporte():
    importe = int(cantidadViajeros.get()) * float(distancia.get()) * float(precio.get())
    importeMasVuelta = round(importe * 1.5,2)
    importePrimeraConVuelta = round(importeMasVuelta * 1.2,2)
    importeLujoConVuelta = round(importeMasVuelta * 2,2)
    importePrimeraIda = round(importe * 1.2,2)
    importeLujoIda = round(importe * 2,2)
    if check.get() and rButton.get() == 'Turista':
        totalPagar.set(str(importeMasVuelta))
    elif check.get() and rButton.get() == 'Primera':
        totalPagar.set(str(importePrimeraConVuelta))
    elif check.get() and rButton.get() == 'Lujo':
        totalPagar.set(str(importeLujoConVuelta))
    elif rButton.get() == 'Turista':
        totalPagar.set(str(importe))
    elif rButton.get() == 'Primera':
        totalPagar.set(str(importePrimeraIda))
    elif rButton.get() == 'Lujo':
        totalPagar.set(str(importeLujoIda))

def salir():
    destroy_window()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import costeDeViaje
    costeDeViaje.vp_start_gui()





