#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Apr 15, 2020 08:34:16 PM -03  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m50" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x602+682+216
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1050
    wm minsize $top 176 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Pasajes"
    vTcl:DefineAlias "$top" "window" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu45 \
        -command registrar -takefocus {} -text {Registrar Pasajero} 
    vTcl:DefineAlias "$top.tBu45" "bt_registrar" vTcl:WidgetProc "window" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu46 \
        -command eliminar -takefocus {} -text {Eliminar Pasajero} 
    vTcl:DefineAlias "$top.tBu46" "bt_eliminar" vTcl:WidgetProc "window" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu47 \
        -command buscar -takefocus {} -text {Buscar Pasajero} 
    vTcl:DefineAlias "$top.tBu47" "bt_buscar" vTcl:WidgetProc "window" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu48 \
        -command porcentaje -takefocus {} -text {Porcentaje Pasajeros} 
    vTcl:DefineAlias "$top.tBu48" "bt_porcentaje" vTcl:WidgetProc "window" 1
    ttk::separator $top.tSe49
    vTcl:DefineAlias "$top.tSe49" "TSeparator1" vTcl:WidgetProc "window" 1
    set site_3_0 $top.m50
    menu $site_3_0 \
        -activebackground SystemHighlight \
        -activeforeground SystemHighlightText \
        -background $vTcl(pr,menubgcolor) -font TkDefaultFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ttk::separator $top.tSe51 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe51" "TSeparator2" vTcl:WidgetProc "window" 1
    ttk::separator $top.tSe52 \
        -orient vertical 
    vTcl:DefineAlias "$top.tSe52" "TSeparator2_4" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa53 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center \
        -text { 1} 
    vTcl:DefineAlias "$top.tLa53" "asiento_1" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa54 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center \
        -text { 2} 
    vTcl:DefineAlias "$top.tLa54" "asiento_2" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa55 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center \
        -text { 3} 
    vTcl:DefineAlias "$top.tLa55" "asiento_3" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa56 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center \
        -text { 4} 
    vTcl:DefineAlias "$top.tLa56" "asiento_4" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa57 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center \
        -text { 5} 
    vTcl:DefineAlias "$top.tLa57" "asiento_5" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa58 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center \
        -text { 6} 
    vTcl:DefineAlias "$top.tLa58" "asiento_6" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa59 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center \
        -text { 7} 
    vTcl:DefineAlias "$top.tLa59" "asiento_7" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa60 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center \
        -text { 8} 
    vTcl:DefineAlias "$top.tLa60" "asiento_8" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa61 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 11 
    vTcl:DefineAlias "$top.tLa61" "asiento_11" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa62 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 10 
    vTcl:DefineAlias "$top.tLa62" "asiento_10" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa63 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center \
        -text { 9} 
    vTcl:DefineAlias "$top.tLa63" "asiento_9" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa64 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 21 
    vTcl:DefineAlias "$top.tLa64" "asiento_21" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa65 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 15 
    vTcl:DefineAlias "$top.tLa65" "asiento_15" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa66 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 17 
    vTcl:DefineAlias "$top.tLa66" "asiento_17" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa68 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 12 
    vTcl:DefineAlias "$top.tLa68" "asiento_12" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa69 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 13 
    vTcl:DefineAlias "$top.tLa69" "asiento_13" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa70 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 14 
    vTcl:DefineAlias "$top.tLa70" "asiento_14" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa71 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 18 
    vTcl:DefineAlias "$top.tLa71" "asiento_18" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa72 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 23 
    vTcl:DefineAlias "$top.tLa72" "asiento_23" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa73 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 22 
    vTcl:DefineAlias "$top.tLa73" "asiento_22" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa74 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 27 
    vTcl:DefineAlias "$top.tLa74" "asiento_27" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa75 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 28 
    vTcl:DefineAlias "$top.tLa75" "asiento_28" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa76 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 29 
    vTcl:DefineAlias "$top.tLa76" "asiento_29" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa77 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 35 
    vTcl:DefineAlias "$top.tLa77" "asiento_35" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa78 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 41 
    vTcl:DefineAlias "$top.tLa78" "asiento_41" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa79 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 47 
    vTcl:DefineAlias "$top.tLa79" "asiento_47" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa80 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 34 
    vTcl:DefineAlias "$top.tLa80" "asiento_34" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa81 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 40 
    vTcl:DefineAlias "$top.tLa81" "asiento_40" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa82 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 46 
    vTcl:DefineAlias "$top.tLa82" "asiento_46" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa83 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 33 
    vTcl:DefineAlias "$top.tLa83" "asiento_33" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa84 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 39 
    vTcl:DefineAlias "$top.tLa84" "asiento_39" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa85 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 45 
    vTcl:DefineAlias "$top.tLa85" "asiento_45" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa86 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 19 
    vTcl:DefineAlias "$top.tLa86" "asiento_19" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa87 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 20 
    vTcl:DefineAlias "$top.tLa87" "asiento_20" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa88 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 24 
    vTcl:DefineAlias "$top.tLa88" "asiento_24" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa89 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 25 
    vTcl:DefineAlias "$top.tLa89" "asiento_25" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa90 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 26 
    vTcl:DefineAlias "$top.tLa90" "asiento_26" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa91 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 30 
    vTcl:DefineAlias "$top.tLa91" "asiento_30" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa92 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 31 
    vTcl:DefineAlias "$top.tLa92" "asiento_31" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa93 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 32 
    vTcl:DefineAlias "$top.tLa93" "asiento_32" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa94 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 36 
    vTcl:DefineAlias "$top.tLa94" "asiento_36" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa95 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 42 
    vTcl:DefineAlias "$top.tLa95" "asiento_42" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa96 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 48 
    vTcl:DefineAlias "$top.tLa96" "asiento_48" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa97 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 37 
    vTcl:DefineAlias "$top.tLa97" "asiento_37" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa98 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 43 
    vTcl:DefineAlias "$top.tLa98" "asiento_43" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa99 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 38 
    vTcl:DefineAlias "$top.tLa99" "asiento_38" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa100 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 44 
    vTcl:DefineAlias "$top.tLa100" "asiento_44" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa101 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 49 
    vTcl:DefineAlias "$top.tLa101" "asiento_49" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa102 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 50 
    vTcl:DefineAlias "$top.tLa102" "asiento_50" vTcl:WidgetProc "window" 1
    ttk::label $top.tLa103 \
        -background #00ff00 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief raised -anchor w -justify center -text 16 
    vTcl:DefineAlias "$top.tLa103" "asiento_16" vTcl:WidgetProc "window" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tBu45 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.8 -width 171 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tBu46 \
        -in $top -x 0 -relx 0.367 -y 0 -rely 0.8 -width 171 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tBu47 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.8 -width 171 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tBu48 \
        -in $top -x 0 -relx 0.367 -y 0 -rely 0.889 -width 171 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tSe49 \
        -in $top -x 0 -relx 0.033 -y 0 -rely 0.756 -width 0 -relwidth 0.95 \
        -height 0 -relheight 0.004 -anchor nw -bordermode inside 
    place $top.tSe51 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.022 -height 0 -relheight 0.689 \
        -anchor nw -bordermode inside 
    place $top.tSe52 \
        -in $top -x 0 -relx 0.567 -y 0 -rely 0.022 -width 0 -relwidth 0.003 \
        -height 0 -relheight 0.689 -anchor nw -bordermode ignore 
    place $top.tLa53 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.033 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa54 \
        -in $top -x 0 -relx 0.317 -y 0 -rely 0.033 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa55 \
        -in $top -x 0 -relx 0.617 -y 0 -rely 0.033 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa56 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.033 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa57 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.133 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa58 \
        -in $top -x 0 -relx 0.317 -y 0 -rely 0.133 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa59 \
        -in $top -x 0 -relx 0.617 -y 0 -rely 0.133 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa60 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.133 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa61 \
        -in $top -x 0 -relx 0.317 -y 0 -rely 0.249 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa62 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.249 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa63 \
        -in $top -x 0 -relx 0.183 -y 0 -rely 0.249 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa64 \
        -in $top -x 0 -relx 0.183 -y 0 -rely 0.382 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa65 \
        -in $top -x 0 -relx 0.183 -y 0 -rely 0.316 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa66 \
        -in $top -x 0 -relx 0.317 -y 0 -rely 0.316 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa68 \
        -in $top -x 0 -relx 0.617 -y 0 -rely 0.249 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa69 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.249 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa70 \
        -in $top -x 0 -relx 0.75 -y 0 -rely 0.249 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa71 \
        -in $top -x 0 -relx 0.617 -y 0 -rely 0.316 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa72 \
        -in $top -x 0 -relx 0.317 -y 0 -rely 0.382 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa73 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.382 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa74 \
        -in $top -x 0 -relx 0.183 -y 0 -rely 0.449 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa75 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.449 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa76 \
        -in $top -x 0 -relx 0.317 -y 0 -rely 0.449 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa77 \
        -in $top -x 0 -relx 0.317 -y 0 -rely 0.515 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa78 \
        -in $top -x 0 -relx 0.317 -y 0 -rely 0.581 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa79 \
        -in $top -x 0 -relx 0.317 -y 0 -rely 0.648 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa80 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.515 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa81 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.581 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa82 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.648 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa83 \
        -in $top -x 0 -relx 0.183 -y 0 -rely 0.515 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa84 \
        -in $top -x 0 -relx 0.183 -y 0 -rely 0.581 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa85 \
        -in $top -x 0 -relx 0.183 -y 0 -rely 0.648 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa86 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.316 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa87 \
        -in $top -x 0 -relx 0.75 -y 0 -rely 0.316 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa88 \
        -in $top -x 0 -relx 0.617 -y 0 -rely 0.382 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa89 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.382 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa90 \
        -in $top -x 0 -relx 0.75 -y 0 -rely 0.382 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa91 \
        -in $top -x 0 -relx 0.617 -y 0 -rely 0.449 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa92 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.449 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa93 \
        -in $top -x 0 -relx 0.75 -y 0 -rely 0.449 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa94 \
        -in $top -x 0 -relx 0.617 -y 0 -rely 0.515 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa95 \
        -in $top -x 0 -relx 0.617 -y 0 -rely 0.581 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa96 \
        -in $top -x 0 -relx 0.617 -y 0 -rely 0.648 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa97 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.515 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa98 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.581 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa99 \
        -in $top -x 0 -relx 0.75 -y 0 -rely 0.515 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa100 \
        -in $top -x 0 -relx 0.75 -y 0 -rely 0.581 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa101 \
        -in $top -x 0 -relx 0.683 -y 0 -rely 0.648 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa102 \
        -in $top -x 0 -relx 0.75 -y 0 -rely 0.648 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tLa103 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.316 -width 0 -relwidth 0.04 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

