#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 16, 2020 11:27:44 AM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def BuscarP():
    print('Pasajerosv2_support.BuscarP')
    sys.stdout.flush()

def EliminarP():
    print('Pasajerosv2_support.EliminarP')
    sys.stdout.flush()

def PorcentajeOcup():
    print('Pasajerosv2_support.PorcentajeOcup')
    sys.stdout.flush()

def RegistroP():
    print('Pasajerosv2_support.RegistroP')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Pasajerosv2
    Pasajerosv2.vp_start_gui()




