#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 16, 2020 02:21:09 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import pasajeavion_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = master (root)
    pasajeavion_support.init(root, top)
    root.mainloop()

w = None
def create_master(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_master(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = master (w)
    pasajeavion_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_master():
    global w
    w.destroy()
    w = None

class master:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("425x469+582+146")
        top.minsize(120, 1)
        top.maxsize(1444, 881)
        top.resizable(0, 0)
        top.title("Asientos de avion")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.btnRegPas = ttk.Button(top)
        self.btnRegPas.place(relx=0.0, rely=0.789, height=45, width=136)
        self.btnRegPas.configure(command=pasajeavion_support.regPas)
        self.btnRegPas.configure(takefocus="")
        self.btnRegPas.configure(text='''Registrar pasajero''')

        self.btnA1 = tk.Button(top)
        self.btnA1.place(relx=0.235, rely=0.235, height=24, width=27)
        self.btnA1.configure(activebackground="#f9f9f9")
        self.btnA1.configure(activeforeground="black")
        self.btnA1.configure(background="#faec87")
        self.btnA1.configure(cursor="fleur")
        self.btnA1.configure(disabledforeground="#a3a3a3")
        self.btnA1.configure(foreground="#000000")
        self.btnA1.configure(highlightbackground="#d9d9d9")
        self.btnA1.configure(highlightcolor="black")
        self.btnA1.configure(pady="0")
        self.btnA1.configure(text='''1''')

        self.btnA2 = tk.Button(top)
        self.btnA2.place(relx=0.306, rely=0.235, height=24, width=27)
        self.btnA2.configure(activebackground="#f9f9f9")
        self.btnA2.configure(activeforeground="black")
        self.btnA2.configure(background="#faec87")
        self.btnA2.configure(disabledforeground="#a3a3a3")
        self.btnA2.configure(foreground="#000000")
        self.btnA2.configure(highlightbackground="#d9d9d9")
        self.btnA2.configure(highlightcolor="black")
        self.btnA2.configure(pady="0")
        self.btnA2.configure(text='''2''')

        self.btnA3 = tk.Button(top)
        self.btnA3.place(relx=0.612, rely=0.235, height=24, width=27)
        self.btnA3.configure(activebackground="#f9f9f9")
        self.btnA3.configure(activeforeground="black")
        self.btnA3.configure(background="#faec87")
        self.btnA3.configure(cursor="fleur")
        self.btnA3.configure(disabledforeground="#a3a3a3")
        self.btnA3.configure(foreground="#000000")
        self.btnA3.configure(highlightbackground="#d9d9d9")
        self.btnA3.configure(highlightcolor="black")
        self.btnA3.configure(pady="0")
        self.btnA3.configure(text='''3''')

        self.btnA4 = tk.Button(top)
        self.btnA4.place(relx=0.682, rely=0.235, height=24, width=27)
        self.btnA4.configure(activebackground="#f9f9f9")
        self.btnA4.configure(activeforeground="black")
        self.btnA4.configure(background="#faec87")
        self.btnA4.configure(disabledforeground="#a3a3a3")
        self.btnA4.configure(foreground="#000000")
        self.btnA4.configure(highlightbackground="#d9d9d9")
        self.btnA4.configure(highlightcolor="black")
        self.btnA4.configure(pady="0")
        self.btnA4.configure(text='''4''')

        self.btnA5 = tk.Button(top)
        self.btnA5.place(relx=0.235, rely=0.299, height=24, width=27)
        self.btnA5.configure(activebackground="#f9f9f9")
        self.btnA5.configure(activeforeground="black")
        self.btnA5.configure(background="#faec87")
        self.btnA5.configure(disabledforeground="#a3a3a3")
        self.btnA5.configure(foreground="#000000")
        self.btnA5.configure(highlightbackground="#d9d9d9")
        self.btnA5.configure(highlightcolor="black")
        self.btnA5.configure(pady="0")
        self.btnA5.configure(text='''5''')

        self.btnA6 = tk.Button(top)
        self.btnA6.place(relx=0.306, rely=0.299, height=24, width=27)
        self.btnA6.configure(activebackground="#f9f9f9")
        self.btnA6.configure(activeforeground="black")
        self.btnA6.configure(background="#faec87")
        self.btnA6.configure(disabledforeground="#a3a3a3")
        self.btnA6.configure(foreground="#000000")
        self.btnA6.configure(highlightbackground="#d9d9d9")
        self.btnA6.configure(highlightcolor="black")
        self.btnA6.configure(pady="0")
        self.btnA6.configure(text='''6''')

        self.btnA7 = tk.Button(top)
        self.btnA7.place(relx=0.612, rely=0.299, height=24, width=27)
        self.btnA7.configure(activebackground="#f9f9f9")
        self.btnA7.configure(activeforeground="black")
        self.btnA7.configure(background="#faec87")
        self.btnA7.configure(disabledforeground="#a3a3a3")
        self.btnA7.configure(foreground="#000000")
        self.btnA7.configure(highlightbackground="#d9d9d9")
        self.btnA7.configure(highlightcolor="black")
        self.btnA7.configure(pady="0")
        self.btnA7.configure(text='''7''')

        self.btnA8 = tk.Button(top)
        self.btnA8.place(relx=0.682, rely=0.299, height=24, width=27)
        self.btnA8.configure(activebackground="#f9f9f9")
        self.btnA8.configure(activeforeground="black")
        self.btnA8.configure(background="#faec87")
        self.btnA8.configure(cursor="fleur")
        self.btnA8.configure(disabledforeground="#a3a3a3")
        self.btnA8.configure(foreground="#000000")
        self.btnA8.configure(highlightbackground="#d9d9d9")
        self.btnA8.configure(highlightcolor="black")
        self.btnA8.configure(pady="0")
        self.btnA8.configure(text='''8''')

        self.btnA9 = tk.Button(top)
        self.btnA9.place(relx=0.212, rely=0.362, height=24, width=27)
        self.btnA9.configure(activebackground="#f9f9f9")
        self.btnA9.configure(activeforeground="black")
        self.btnA9.configure(background="#888bf9")
        self.btnA9.configure(disabledforeground="#a3a3a3")
        self.btnA9.configure(foreground="#000000")
        self.btnA9.configure(highlightbackground="#d9d9d9")
        self.btnA9.configure(highlightcolor="black")
        self.btnA9.configure(pady="0")
        self.btnA9.configure(text='''9''')

        self.btnA10 = tk.Button(top)
        self.btnA10.place(relx=0.282, rely=0.362, height=24, width=27)
        self.btnA10.configure(activebackground="#f9f9f9")
        self.btnA10.configure(activeforeground="black")
        self.btnA10.configure(background="#888bf9")
        self.btnA10.configure(cursor="fleur")
        self.btnA10.configure(disabledforeground="#a3a3a3")
        self.btnA10.configure(foreground="#000000")
        self.btnA10.configure(highlightbackground="#d9d9d9")
        self.btnA10.configure(highlightcolor="black")
        self.btnA10.configure(pady="0")
        self.btnA10.configure(text='''10''')

        self.btnA11 = tk.Button(top)
        self.btnA11.place(relx=0.353, rely=0.362, height=24, width=27)
        self.btnA11.configure(activebackground="#f9f9f9")
        self.btnA11.configure(activeforeground="black")
        self.btnA11.configure(background="#888bf9")
        self.btnA11.configure(cursor="fleur")
        self.btnA11.configure(disabledforeground="#a3a3a3")
        self.btnA11.configure(foreground="#000000")
        self.btnA11.configure(highlightbackground="#d9d9d9")
        self.btnA11.configure(highlightcolor="black")
        self.btnA11.configure(pady="0")
        self.btnA11.configure(text='''11''')

        self.btnA15 = tk.Button(top)
        self.btnA15.place(relx=0.212, rely=0.426, height=24, width=27)
        self.btnA15.configure(activebackground="#f9f9f9")
        self.btnA15.configure(activeforeground="black")
        self.btnA15.configure(background="#888bf9")
        self.btnA15.configure(cursor="fleur")
        self.btnA15.configure(disabledforeground="#a3a3a3")
        self.btnA15.configure(foreground="#000000")
        self.btnA15.configure(highlightbackground="#d9d9d9")
        self.btnA15.configure(highlightcolor="black")
        self.btnA15.configure(pady="0")
        self.btnA15.configure(text='''15''')

        self.btnA16 = tk.Button(top)
        self.btnA16.place(relx=0.282, rely=0.426, height=24, width=27)
        self.btnA16.configure(activebackground="#f9f9f9")
        self.btnA16.configure(activeforeground="black")
        self.btnA16.configure(background="#888bf9")
        self.btnA16.configure(cursor="fleur")
        self.btnA16.configure(disabledforeground="#a3a3a3")
        self.btnA16.configure(foreground="#000000")
        self.btnA16.configure(highlightbackground="#d9d9d9")
        self.btnA16.configure(highlightcolor="black")
        self.btnA16.configure(pady="0")
        self.btnA16.configure(text='''16''')

        self.btnA17 = tk.Button(top)
        self.btnA17.place(relx=0.353, rely=0.426, height=24, width=27)
        self.btnA17.configure(activebackground="#f9f9f9")
        self.btnA17.configure(activeforeground="black")
        self.btnA17.configure(background="#888bf9")
        self.btnA17.configure(cursor="fleur")
        self.btnA17.configure(disabledforeground="#a3a3a3")
        self.btnA17.configure(foreground="#000000")
        self.btnA17.configure(highlightbackground="#d9d9d9")
        self.btnA17.configure(highlightcolor="black")
        self.btnA17.configure(pady="0")
        self.btnA17.configure(text='''17''')

        self.btnA12 = tk.Button(top)
        self.btnA12.place(relx=0.565, rely=0.362, height=24, width=27)
        self.btnA12.configure(activebackground="#f9f9f9")
        self.btnA12.configure(activeforeground="black")
        self.btnA12.configure(background="#888bf9")
        self.btnA12.configure(cursor="fleur")
        self.btnA12.configure(disabledforeground="#a3a3a3")
        self.btnA12.configure(foreground="#000000")
        self.btnA12.configure(highlightbackground="#d9d9d9")
        self.btnA12.configure(highlightcolor="black")
        self.btnA12.configure(pady="0")
        self.btnA12.configure(text='''12''')

        self.btnA18 = tk.Button(top)
        self.btnA18.place(relx=0.565, rely=0.426, height=24, width=27)
        self.btnA18.configure(activebackground="#f9f9f9")
        self.btnA18.configure(activeforeground="black")
        self.btnA18.configure(background="#888bf9")
        self.btnA18.configure(disabledforeground="#a3a3a3")
        self.btnA18.configure(foreground="#000000")
        self.btnA18.configure(highlightbackground="#d9d9d9")
        self.btnA18.configure(highlightcolor="black")
        self.btnA18.configure(pady="0")
        self.btnA18.configure(text='''18''')

        self.btnA13 = tk.Button(top)
        self.btnA13.place(relx=0.635, rely=0.362, height=24, width=27)
        self.btnA13.configure(activebackground="#f9f9f9")
        self.btnA13.configure(activeforeground="black")
        self.btnA13.configure(background="#888bf9")
        self.btnA13.configure(cursor="fleur")
        self.btnA13.configure(disabledforeground="#a3a3a3")
        self.btnA13.configure(foreground="#000000")
        self.btnA13.configure(highlightbackground="#d9d9d9")
        self.btnA13.configure(highlightcolor="black")
        self.btnA13.configure(pady="0")
        self.btnA13.configure(text='''13''')

        self.btnA14 = tk.Button(top)
        self.btnA14.place(relx=0.706, rely=0.362, height=24, width=27)
        self.btnA14.configure(activebackground="#f9f9f9")
        self.btnA14.configure(activeforeground="black")
        self.btnA14.configure(background="#888bf9")
        self.btnA14.configure(cursor="fleur")
        self.btnA14.configure(disabledforeground="#a3a3a3")
        self.btnA14.configure(foreground="#000000")
        self.btnA14.configure(highlightbackground="#d9d9d9")
        self.btnA14.configure(highlightcolor="black")
        self.btnA14.configure(pady="0")
        self.btnA14.configure(text='''14''')

        self.btnA19 = tk.Button(top)
        self.btnA19.place(relx=0.635, rely=0.426, height=24, width=27)
        self.btnA19.configure(activebackground="#f9f9f9")
        self.btnA19.configure(activeforeground="black")
        self.btnA19.configure(background="#888bf9")
        self.btnA19.configure(disabledforeground="#a3a3a3")
        self.btnA19.configure(foreground="#000000")
        self.btnA19.configure(highlightbackground="#d9d9d9")
        self.btnA19.configure(highlightcolor="black")
        self.btnA19.configure(pady="0")
        self.btnA19.configure(text='''19''')

        self.btnA20 = tk.Button(top)
        self.btnA20.place(relx=0.706, rely=0.426, height=24, width=27)
        self.btnA20.configure(activebackground="#f9f9f9")
        self.btnA20.configure(activeforeground="black")
        self.btnA20.configure(background="#888bf9")
        self.btnA20.configure(cursor="fleur")
        self.btnA20.configure(disabledforeground="#a3a3a3")
        self.btnA20.configure(foreground="#000000")
        self.btnA20.configure(highlightbackground="#d9d9d9")
        self.btnA20.configure(highlightcolor="black")
        self.btnA20.configure(pady="0")
        self.btnA20.configure(text='''20''')

        self.btnElimPas = ttk.Button(top)
        self.btnElimPas.place(relx=0.329, rely=0.789, height=45, width=136)
        self.btnElimPas.configure(command=pasajeavion_support.elimPas)
        self.btnElimPas.configure(takefocus="")
        self.btnElimPas.configure(text='''Eliminar Pasajero''')

        self.btnBuscPas = ttk.Button(top)
        self.btnBuscPas.place(relx=0.659, rely=0.789, height=45, width=136)
        self.btnBuscPas.configure(command=pasajeavion_support.busPas)
        self.btnBuscPas.configure(takefocus="")
        self.btnBuscPas.configure(text='''Buscar Pasajero''')

        self.btnPorcOcup = ttk.Button(top)
        self.btnPorcOcup.place(relx=0.329, rely=0.896, height=45, width=136)
        self.btnPorcOcup.configure(command=pasajeavion_support.PorcOcup)
        self.btnPorcOcup.configure(takefocus="")
        self.btnPorcOcup.configure(text='''Porcentaje ocupacion''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

if __name__ == '__main__':
    vp_start_gui()





