#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 16, 2020 11:27:35 AM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Pasajerosv2_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    Pasajerosv2_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    Pasajerosv2_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x450+381+161")
        top.minsize(124, 1)
        top.maxsize(1354, 733)
        top.resizable(1, 1)
        top.title("Registro de Asientos")
        top.configure(background="#d9d9d9")

        self.Frame1_1 = tk.Frame(top)
        self.Frame1_1.place(relx=0.5, rely=0.044, relheight=0.678
                , relwidth=0.275)
        self.Frame1_1.configure(relief='groove')
        self.Frame1_1.configure(borderwidth="2")
        self.Frame1_1.configure(relief="groove")
        self.Frame1_1.configure(background="#d9d9d9")
        self.Frame1_1.configure(highlightbackground="#d9d9d9")
        self.Frame1_1.configure(highlightcolor="black")

        self.txtAsiento3 = tk.Label(self.Frame1_1)
        self.txtAsiento3.place(relx=0.121, rely=0.066, height=20, width=34)
        self.txtAsiento3.configure(activebackground="#f9f9f9")
        self.txtAsiento3.configure(activeforeground="black")
        self.txtAsiento3.configure(background="#f8fdb5")
        self.txtAsiento3.configure(disabledforeground="#a3a3a3")
        self.txtAsiento3.configure(foreground="#000000")
        self.txtAsiento3.configure(highlightbackground="#d9d9d9")
        self.txtAsiento3.configure(highlightcolor="black")
        self.txtAsiento3.configure(text='''A3''')

        self.txtAsiento4 = tk.Label(self.Frame1_1)
        self.txtAsiento4.place(relx=0.667, rely=0.062, height=21, width=34)
        self.txtAsiento4.configure(activebackground="#f9f9f9")
        self.txtAsiento4.configure(activeforeground="black")
        self.txtAsiento4.configure(background="#f8fdb5")
        self.txtAsiento4.configure(disabledforeground="#a3a3a3")
        self.txtAsiento4.configure(foreground="#000000")
        self.txtAsiento4.configure(highlightbackground="#d9d9d9")
        self.txtAsiento4.configure(highlightcolor="black")
        self.txtAsiento4.configure(text='''A4''')

        self.txtAsiento7 = tk.Label(self.Frame1_1)
        self.txtAsiento7.place(relx=0.121, rely=0.19, height=20, width=34)
        self.txtAsiento7.configure(activebackground="#f9f9f9")
        self.txtAsiento7.configure(activeforeground="black")
        self.txtAsiento7.configure(background="#f8fdb5")
        self.txtAsiento7.configure(disabledforeground="#a3a3a3")
        self.txtAsiento7.configure(foreground="#000000")
        self.txtAsiento7.configure(highlightbackground="#d9d9d9")
        self.txtAsiento7.configure(highlightcolor="black")
        self.txtAsiento7.configure(text='''A7''')

        self.txtAsiento8 = tk.Label(self.Frame1_1)
        self.txtAsiento8.place(relx=0.667, rely=0.19, height=20, width=34)
        self.txtAsiento8.configure(activebackground="#f9f9f9")
        self.txtAsiento8.configure(activeforeground="black")
        self.txtAsiento8.configure(background="#f8fdb5")
        self.txtAsiento8.configure(disabledforeground="#a3a3a3")
        self.txtAsiento8.configure(foreground="#000000")
        self.txtAsiento8.configure(highlightbackground="#d9d9d9")
        self.txtAsiento8.configure(highlightcolor="black")
        self.txtAsiento8.configure(text='''A8''')

        self.txtAsiento12 = tk.Label(self.Frame1_1)
        self.txtAsiento12.place(relx=0.061, rely=0.361, height=20, width=34)
        self.txtAsiento12.configure(activebackground="#f9f9f9")
        self.txtAsiento12.configure(activeforeground="black")
        self.txtAsiento12.configure(background="#5539f2")
        self.txtAsiento12.configure(disabledforeground="#a3a3a3")
        self.txtAsiento12.configure(foreground="#000000")
        self.txtAsiento12.configure(highlightbackground="#d9d9d9")
        self.txtAsiento12.configure(highlightcolor="black")
        self.txtAsiento12.configure(text='''A12''')

        self.txtAsiento13 = tk.Label(self.Frame1_1)
        self.txtAsiento13.place(relx=0.364, rely=0.361, height=20, width=34)
        self.txtAsiento13.configure(activebackground="#f9f9f9")
        self.txtAsiento13.configure(activeforeground="black")
        self.txtAsiento13.configure(background="#5539f2")
        self.txtAsiento13.configure(disabledforeground="#a3a3a3")
        self.txtAsiento13.configure(foreground="#000000")
        self.txtAsiento13.configure(highlightbackground="#d9d9d9")
        self.txtAsiento13.configure(highlightcolor="black")
        self.txtAsiento13.configure(text='''A13''')

        self.txtAsiento14 = tk.Label(self.Frame1_1)
        self.txtAsiento14.place(relx=0.667, rely=0.361, height=20, width=34)
        self.txtAsiento14.configure(activebackground="#f9f9f9")
        self.txtAsiento14.configure(activeforeground="black")
        self.txtAsiento14.configure(background="#5539f2")
        self.txtAsiento14.configure(disabledforeground="#a3a3a3")
        self.txtAsiento14.configure(foreground="#000000")
        self.txtAsiento14.configure(highlightbackground="#d9d9d9")
        self.txtAsiento14.configure(highlightcolor="black")
        self.txtAsiento14.configure(text='''A14''')

        self.txtAsiento18 = tk.Label(self.Frame1_1)
        self.txtAsiento18.place(relx=0.061, rely=0.557, height=20, width=34)
        self.txtAsiento18.configure(activebackground="#f9f9f9")
        self.txtAsiento18.configure(activeforeground="black")
        self.txtAsiento18.configure(background="#5539f2")
        self.txtAsiento18.configure(disabledforeground="#a3a3a3")
        self.txtAsiento18.configure(foreground="#000000")
        self.txtAsiento18.configure(highlightbackground="#d9d9d9")
        self.txtAsiento18.configure(highlightcolor="black")
        self.txtAsiento18.configure(text='''A18''')

        self.txtAsiento19 = tk.Label(self.Frame1_1)
        self.txtAsiento19.place(relx=0.364, rely=0.557, height=20, width=34)
        self.txtAsiento19.configure(activebackground="#f9f9f9")
        self.txtAsiento19.configure(activeforeground="black")
        self.txtAsiento19.configure(background="#5539f2")
        self.txtAsiento19.configure(disabledforeground="#a3a3a3")
        self.txtAsiento19.configure(foreground="#000000")
        self.txtAsiento19.configure(highlightbackground="#d9d9d9")
        self.txtAsiento19.configure(highlightcolor="black")
        self.txtAsiento19.configure(text='''A19''')

        self.txtAsiento20 = tk.Label(self.Frame1_1)
        self.txtAsiento20.place(relx=0.667, rely=0.557, height=20, width=34)
        self.txtAsiento20.configure(activebackground="#f9f9f9")
        self.txtAsiento20.configure(activeforeground="black")
        self.txtAsiento20.configure(background="#5539f2")
        self.txtAsiento20.configure(disabledforeground="#a3a3a3")
        self.txtAsiento20.configure(foreground="#000000")
        self.txtAsiento20.configure(highlightbackground="#d9d9d9")
        self.txtAsiento20.configure(highlightcolor="black")
        self.txtAsiento20.configure(text='''A20''')

        self.Frame1_2 = tk.Frame(top)
        self.Frame1_2.place(relx=0.2, rely=0.044, relheight=0.678
                , relwidth=0.275)
        self.Frame1_2.configure(relief='groove')
        self.Frame1_2.configure(borderwidth="2")
        self.Frame1_2.configure(relief="groove")
        self.Frame1_2.configure(background="#d9d9d9")
        self.Frame1_2.configure(highlightbackground="#d9d9d9")
        self.Frame1_2.configure(highlightcolor="black")

        self.txtAsiento1 = tk.Label(self.Frame1_2)
        self.txtAsiento1.place(relx=0.121, rely=0.062, height=21, width=34)
        self.txtAsiento1.configure(activebackground="#f9f9f9")
        self.txtAsiento1.configure(activeforeground="black")
        self.txtAsiento1.configure(background="#f8fdb5")
        self.txtAsiento1.configure(disabledforeground="#a3a3a3")
        self.txtAsiento1.configure(foreground="#000000")
        self.txtAsiento1.configure(highlightbackground="#d9d9d9")
        self.txtAsiento1.configure(highlightcolor="black")
        self.txtAsiento1.configure(text='''A1''')

        self.txtAsiento2 = tk.Label(self.Frame1_2)
        self.txtAsiento2.place(relx=0.667, rely=0.062, height=21, width=34)
        self.txtAsiento2.configure(activebackground="#f9f9f9")
        self.txtAsiento2.configure(activeforeground="black")
        self.txtAsiento2.configure(background="#f8fdb5")
        self.txtAsiento2.configure(disabledforeground="#a3a3a3")
        self.txtAsiento2.configure(foreground="#000000")
        self.txtAsiento2.configure(highlightbackground="#d9d9d9")
        self.txtAsiento2.configure(highlightcolor="black")
        self.txtAsiento2.configure(text='''A2''')

        self.txtAsiento5 = tk.Label(self.Frame1_2)
        self.txtAsiento5.place(relx=0.121, rely=0.19, height=20, width=34)
        self.txtAsiento5.configure(activebackground="#f9f9f9")
        self.txtAsiento5.configure(activeforeground="black")
        self.txtAsiento5.configure(background="#f8fdb5")
        self.txtAsiento5.configure(disabledforeground="#a3a3a3")
        self.txtAsiento5.configure(foreground="#000000")
        self.txtAsiento5.configure(highlightbackground="#d9d9d9")
        self.txtAsiento5.configure(highlightcolor="black")
        self.txtAsiento5.configure(text='''A5''')

        self.txtAsiento6 = tk.Label(self.Frame1_2)
        self.txtAsiento6.place(relx=0.667, rely=0.19, height=20, width=34)
        self.txtAsiento6.configure(activebackground="#f9f9f9")
        self.txtAsiento6.configure(activeforeground="black")
        self.txtAsiento6.configure(background="#f8fdb5")
        self.txtAsiento6.configure(disabledforeground="#a3a3a3")
        self.txtAsiento6.configure(foreground="#000000")
        self.txtAsiento6.configure(highlightbackground="#d9d9d9")
        self.txtAsiento6.configure(highlightcolor="black")
        self.txtAsiento6.configure(text='''A6''')

        self.txtAsiento9 = tk.Label(self.Frame1_2)
        self.txtAsiento9.place(relx=0.061, rely=0.361, height=20, width=34)
        self.txtAsiento9.configure(activebackground="#f9f9f9")
        self.txtAsiento9.configure(activeforeground="black")
        self.txtAsiento9.configure(background="#5539f2")
        self.txtAsiento9.configure(disabledforeground="#a3a3a3")
        self.txtAsiento9.configure(foreground="#000000")
        self.txtAsiento9.configure(highlightbackground="#d9d9d9")
        self.txtAsiento9.configure(highlightcolor="black")
        self.txtAsiento9.configure(text='''A9''')

        self.txtAsiento10 = tk.Label(self.Frame1_2)
        self.txtAsiento10.place(relx=0.364, rely=0.361, height=20, width=34)
        self.txtAsiento10.configure(activebackground="#f9f9f9")
        self.txtAsiento10.configure(activeforeground="black")
        self.txtAsiento10.configure(background="#5539f2")
        self.txtAsiento10.configure(disabledforeground="#a3a3a3")
        self.txtAsiento10.configure(foreground="#000000")
        self.txtAsiento10.configure(highlightbackground="#d9d9d9")
        self.txtAsiento10.configure(highlightcolor="black")
        self.txtAsiento10.configure(text='''A10''')

        self.txtAsiento11 = tk.Label(self.Frame1_2)
        self.txtAsiento11.place(relx=0.667, rely=0.361, height=20, width=34)
        self.txtAsiento11.configure(activebackground="#f9f9f9")
        self.txtAsiento11.configure(activeforeground="black")
        self.txtAsiento11.configure(background="#5539f2")
        self.txtAsiento11.configure(disabledforeground="#a3a3a3")
        self.txtAsiento11.configure(foreground="#000000")
        self.txtAsiento11.configure(highlightbackground="#d9d9d9")
        self.txtAsiento11.configure(highlightcolor="black")
        self.txtAsiento11.configure(text='''A11''')

        self.txtAsiento15 = tk.Label(self.Frame1_2)
        self.txtAsiento15.place(relx=0.061, rely=0.557, height=20, width=34)
        self.txtAsiento15.configure(activebackground="#f9f9f9")
        self.txtAsiento15.configure(activeforeground="black")
        self.txtAsiento15.configure(background="#5539f2")
        self.txtAsiento15.configure(disabledforeground="#a3a3a3")
        self.txtAsiento15.configure(foreground="#000000")
        self.txtAsiento15.configure(highlightbackground="#d9d9d9")
        self.txtAsiento15.configure(highlightcolor="black")
        self.txtAsiento15.configure(text='''A15''')

        self.txtAsiento16 = tk.Label(self.Frame1_2)
        self.txtAsiento16.place(relx=0.364, rely=0.557, height=20, width=34)
        self.txtAsiento16.configure(activebackground="#f9f9f9")
        self.txtAsiento16.configure(activeforeground="black")
        self.txtAsiento16.configure(background="#5539f2")
        self.txtAsiento16.configure(disabledforeground="#a3a3a3")
        self.txtAsiento16.configure(foreground="#000000")
        self.txtAsiento16.configure(highlightbackground="#d9d9d9")
        self.txtAsiento16.configure(highlightcolor="black")
        self.txtAsiento16.configure(text='''A16''')

        self.txtAsiento17 = tk.Label(self.Frame1_2)
        self.txtAsiento17.place(relx=0.667, rely=0.557, height=20, width=34)
        self.txtAsiento17.configure(activebackground="#f9f9f9")
        self.txtAsiento17.configure(activeforeground="black")
        self.txtAsiento17.configure(background="#5539f2")
        self.txtAsiento17.configure(disabledforeground="#a3a3a3")
        self.txtAsiento17.configure(foreground="#000000")
        self.txtAsiento17.configure(highlightbackground="#d9d9d9")
        self.txtAsiento17.configure(highlightcolor="black")
        self.txtAsiento17.configure(text='''A17''')

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.05, rely=0.778, relheight=0.167, relwidth=0.908)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")

        self.btnRegistro = ttk.Button(self.Frame1)
        self.btnRegistro.place(relx=0.037, rely=0.133, height=25, width=150)
        self.btnRegistro.configure(command=Pasajerosv2_support.RegistroP)
        self.btnRegistro.configure(takefocus="")
        self.btnRegistro.configure(text='''Registrar Pasajero''')

        self.btnEliminacion = ttk.Button(self.Frame1)
        self.btnEliminacion.place(relx=0.367, rely=0.133, height=25, width=150)
        self.btnEliminacion.configure(command=Pasajerosv2_support.EliminarP)
        self.btnEliminacion.configure(takefocus="")
        self.btnEliminacion.configure(text='''Eliminar Pasajero''')

        self.btnBusqueda = ttk.Button(self.Frame1)
        self.btnBusqueda.place(relx=0.697, rely=0.133, height=25, width=150)
        self.btnBusqueda.configure(command=Pasajerosv2_support.BuscarP)
        self.btnBusqueda.configure(takefocus="")
        self.btnBusqueda.configure(text='''Buscar Pasajero''')

        self.btnPorcentaje = ttk.Button(self.Frame1)
        self.btnPorcentaje.place(relx=0.037, rely=0.533, height=25, width=150)
        self.btnPorcentaje.configure(command=Pasajerosv2_support.PorcentajeOcup)
        self.btnPorcentaje.configure(takefocus="")
        self.btnPorcentaje.configure(text='''Porcentaje Ocupacion''')

        self.TButton1_12 = ttk.Button(self.Frame1)
        self.TButton1_12.place(relx=0.367, rely=0.533, height=25, width=150)
        self.TButton1_12.configure(takefocus="")
        self.TButton1_12.configure(text='''Opcion 1''')

        self.TButton1_13 = ttk.Button(self.Frame1)
        self.TButton1_13.place(relx=0.697, rely=0.533, height=25, width=150)
        self.TButton1_13.configure(takefocus="")
        self.TButton1_13.configure(text='''Opcion 2''')

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="black")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(font="{Segoe UI} 9")
        Popupmenu1.configure(foreground="black")
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





