#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 16, 2020 04:25:39 PM -03  platform: Windows NT

import sys
import pasajeavion2
from varname import varname
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global combobox
    combobox = tk.StringVar()
    global clase
    clase = tk.IntVar()
    global lugar
    lugar = tk.IntVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def actPorc():
    print('pasajeavion2_support.actPorc')
    sys.stdout.flush()

def borrPas():
    print('pasajeavion2_support.borrPas')
    sys.stdout.flush()

def buscarPasajero():
    print('pasajeavion2_support.buscarPasajero')
    sys.stdout.flush()

def regPas(pasaj,dni,clase,lugar):
    if clase == "1":
        clase="turista"
    else:
        clase="ejecutiva"

    if clase == "turista" and lugar == "ventana":
        i=0
        for silla in asientos[0][0][i][0]:
            if silla == "libre":
                print(asientos[0][0][i])
                asientos[0][0][i]=["ocupado",dni,pasaj]
                print (asientos[0][0][i])




def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import pasajeavion2
    pasajeavion2.vp_start_gui()

# [DISPONIBILIDAD,DNI,NOMBRE]

A1=["libre","",""]
A2=["libre","",""]
A3=["libre","",""]
A4=["libre","",""]
A5=["libre","",""]
A6=["libre","",""]
A7=["libre","",""]
A8=["libre","",""]
A9=["libre","",""]
A10=["libre","",""]
A11=["libre","",""]
A12=["libre","",""]
A13=["libre","",""]
A14=["libre","",""]
A15=["libre","",""]
A16=["libre","",""]
A17=["libre","",""]
A18=["libre","",""]
A19=["libre","",""]
A20=["libre","",""]

vent_tur=[A9,A14,A15,A20]
pas_tur=[A11,A12,A17,A18]
cent=[A10,A13,A16,A19]
tur=[vent_tur,cent,pas_tur]

vent_vip=[A1,A4,A5,A8]
pas_vip=[A2,A3,A6,A7]
vip=[vent_vip,pas_vip]
asientos=[tur,vip]

