#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 16, 2020 04:25:33 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import pasajeavion2_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    pasajeavion2_support.set_Tk_var()
    top = master (root)
    pasajeavion2_support.init(root, top)
    root.mainloop()

w = None
def create_master(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_master(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    pasajeavion2_support.set_Tk_var()
    top = master (w)
    pasajeavion2_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_master():
    global w
    w.destroy()
    w = None

class master:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        style = ttk.Style()
        if sys.platform == "win32":
            style.theme_use('winnative')
        style.configure('.',background=_bgcolor)
        style.configure('.',foreground=_fgcolor)
        style.configure('.',font="TkDefaultFont")
        style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("425x469+582+146")
        top.minsize(120, 1)
        top.maxsize(1444, 881)
        top.resizable(0, 0)
        top.title("Asientos de avion")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        btnA1 = tk.Button(top)
        btnA1.place(relx=0.235, rely=0.043, height=24, width=27)
        btnA1.configure(activebackground="#f9f9f9")
        btnA1.configure(activeforeground="black")
        btnA1.configure(background="#faec87")
        btnA1.configure(disabledforeground="#a3a3a3")
        btnA1.configure(foreground="#000000")
        btnA1.configure(highlightbackground="#d9d9d9")
        btnA1.configure(highlightcolor="black")
        btnA1.configure(pady="0")
        btnA1.configure(text='''1''')

        btnA2 = tk.Button(top)
        btnA2.place(relx=0.306, rely=0.043, height=24, width=27)
        btnA2.configure(activebackground="#f9f9f9")
        btnA2.configure(activeforeground="black")
        btnA2.configure(background="#faec87")
        btnA2.configure(disabledforeground="#a3a3a3")
        btnA2.configure(foreground="#000000")
        btnA2.configure(highlightbackground="#d9d9d9")
        btnA2.configure(highlightcolor="black")
        btnA2.configure(pady="0")
        btnA2.configure(text='''2''')

        btnA3 = tk.Button(top)
        btnA3.place(relx=0.612, rely=0.043, height=24, width=27)
        btnA3.configure(activebackground="#f9f9f9")
        btnA3.configure(activeforeground="black")
        btnA3.configure(background="#faec87")
        btnA3.configure(disabledforeground="#a3a3a3")
        btnA3.configure(foreground="#000000")
        btnA3.configure(highlightbackground="#d9d9d9")
        btnA3.configure(highlightcolor="black")
        btnA3.configure(pady="0")
        btnA3.configure(text='''3''')

        btnA4 = tk.Button(top)
        btnA4.place(relx=0.682, rely=0.043, height=24, width=27)
        btnA4.configure(activebackground="#f9f9f9")
        btnA4.configure(activeforeground="black")
        btnA4.configure(background="#faec87")
        btnA4.configure(disabledforeground="#a3a3a3")
        btnA4.configure(foreground="#000000")
        btnA4.configure(highlightbackground="#d9d9d9")
        btnA4.configure(highlightcolor="black")
        btnA4.configure(pady="0")
        btnA4.configure(text='''4''')

        btnA5 = tk.Button(top)
        btnA5.place(relx=0.235, rely=0.107, height=24, width=27)
        btnA5.configure(activebackground="#f9f9f9")
        btnA5.configure(activeforeground="black")
        btnA5.configure(background="#faec87")
        btnA5.configure(disabledforeground="#a3a3a3")
        btnA5.configure(foreground="#000000")
        btnA5.configure(highlightbackground="#d9d9d9")
        btnA5.configure(highlightcolor="black")
        btnA5.configure(pady="0")
        btnA5.configure(text='''5''')

        btnA6 = tk.Button(top)
        btnA6.place(relx=0.306, rely=0.107, height=24, width=27)
        btnA6.configure(activebackground="#f9f9f9")
        btnA6.configure(activeforeground="black")
        btnA6.configure(background="#faec87")
        btnA6.configure(disabledforeground="#a3a3a3")
        btnA6.configure(foreground="#000000")
        btnA6.configure(highlightbackground="#d9d9d9")
        btnA6.configure(highlightcolor="black")
        btnA6.configure(pady="0")
        btnA6.configure(text='''6''')

        btnA7 = tk.Button(top)
        btnA7.place(relx=0.612, rely=0.107, height=24, width=27)
        btnA7.configure(activebackground="#f9f9f9")
        btnA7.configure(activeforeground="black")
        btnA7.configure(background="#faec87")
        btnA7.configure(disabledforeground="#a3a3a3")
        btnA7.configure(foreground="#000000")
        btnA7.configure(highlightbackground="#d9d9d9")
        btnA7.configure(highlightcolor="black")
        btnA7.configure(pady="0")
        btnA7.configure(text='''7''')

        btnA8 = tk.Button(top)
        btnA8.place(relx=0.682, rely=0.107, height=24, width=27)
        btnA8.configure(activebackground="#f9f9f9")
        btnA8.configure(activeforeground="black")
        btnA8.configure(background="#faec87")
        btnA8.configure(disabledforeground="#a3a3a3")
        btnA8.configure(foreground="#000000")
        btnA8.configure(highlightbackground="#d9d9d9")
        btnA8.configure(highlightcolor="black")
        btnA8.configure(pady="0")
        btnA8.configure(text='''8''')

        btnA9 = tk.Button(top)
        btnA9.place(relx=0.212, rely=0.171, height=24, width=27)
        btnA9.configure(activebackground="#f9f9f9")
        btnA9.configure(activeforeground="black")
        btnA9.configure(background="#888bf9")
        btnA9.configure(disabledforeground="#a3a3a3")
        btnA9.configure(foreground="#000000")
        btnA9.configure(highlightbackground="#d9d9d9")
        btnA9.configure(highlightcolor="black")
        btnA9.configure(pady="0")
        btnA9.configure(text='''9''')

        btnA10 = tk.Button(top)
        btnA10.place(relx=0.282, rely=0.171, height=24, width=27)
        btnA10.configure(activebackground="#f9f9f9")
        btnA10.configure(activeforeground="black")
        btnA10.configure(background="#888bf9")
        btnA10.configure(disabledforeground="#a3a3a3")
        btnA10.configure(foreground="#000000")
        btnA10.configure(highlightbackground="#d9d9d9")
        btnA10.configure(highlightcolor="black")
        btnA10.configure(pady="0")
        btnA10.configure(text='''10''')

        btnA11 = tk.Button(top)
        btnA11.place(relx=0.353, rely=0.171, height=24, width=27)
        btnA11.configure(activebackground="#f9f9f9")
        btnA11.configure(activeforeground="black")
        btnA11.configure(background="#888bf9")
        btnA11.configure(disabledforeground="#a3a3a3")
        btnA11.configure(foreground="#000000")
        btnA11.configure(highlightbackground="#d9d9d9")
        btnA11.configure(highlightcolor="black")
        btnA11.configure(pady="0")
        btnA11.configure(text='''11''')

        btnA15 = tk.Button(top)
        btnA15.place(relx=0.212, rely=0.235, height=24, width=27)
        btnA15.configure(activebackground="#f9f9f9")
        btnA15.configure(activeforeground="black")
        btnA15.configure(background="#888bf9")
        btnA15.configure(disabledforeground="#a3a3a3")
        btnA15.configure(foreground="#000000")
        btnA15.configure(highlightbackground="#d9d9d9")
        btnA15.configure(highlightcolor="black")
        btnA15.configure(pady="0")
        btnA15.configure(text='''15''')

        btnA16 = tk.Button(top)
        btnA16.place(relx=0.282, rely=0.235, height=24, width=27)
        btnA16.configure(activebackground="#f9f9f9")
        btnA16.configure(activeforeground="black")
        btnA16.configure(background="#888bf9")
        btnA16.configure(disabledforeground="#a3a3a3")
        btnA16.configure(foreground="#000000")
        btnA16.configure(highlightbackground="#d9d9d9")
        btnA16.configure(highlightcolor="black")
        btnA16.configure(pady="0")
        btnA16.configure(text='''16''')

        btnA17 = tk.Button(top)
        btnA17.place(relx=0.353, rely=0.235, height=24, width=27)
        btnA17.configure(activebackground="#f9f9f9")
        btnA17.configure(activeforeground="black")
        btnA17.configure(background="#888bf9")
        btnA17.configure(disabledforeground="#a3a3a3")
        btnA17.configure(foreground="#000000")
        btnA17.configure(highlightbackground="#d9d9d9")
        btnA17.configure(highlightcolor="black")
        btnA17.configure(pady="0")
        btnA17.configure(text='''17''')

        btnA12 = tk.Button(top)
        btnA12.place(relx=0.565, rely=0.171, height=24, width=27)
        btnA12.configure(activebackground="#f9f9f9")
        btnA12.configure(activeforeground="black")
        btnA12.configure(background="#888bf9")
        btnA12.configure(disabledforeground="#a3a3a3")
        btnA12.configure(foreground="#000000")
        btnA12.configure(highlightbackground="#d9d9d9")
        btnA12.configure(highlightcolor="black")
        btnA12.configure(pady="0")
        btnA12.configure(text='''12''')

        btnA18 = tk.Button(top)
        btnA18.place(relx=0.565, rely=0.235, height=24, width=27)
        btnA18.configure(activebackground="#f9f9f9")
        btnA18.configure(activeforeground="black")
        btnA18.configure(background="#888bf9")
        btnA18.configure(disabledforeground="#a3a3a3")
        btnA18.configure(foreground="#000000")
        btnA18.configure(highlightbackground="#d9d9d9")
        btnA18.configure(highlightcolor="black")
        btnA18.configure(pady="0")
        btnA18.configure(text='''18''')

        btnA13 = tk.Button(top)
        btnA13.place(relx=0.635, rely=0.171, height=24, width=27)
        btnA13.configure(activebackground="#f9f9f9")
        btnA13.configure(activeforeground="black")
        btnA13.configure(background="#888bf9")
        btnA13.configure(disabledforeground="#a3a3a3")
        btnA13.configure(foreground="#000000")
        btnA13.configure(highlightbackground="#d9d9d9")
        btnA13.configure(highlightcolor="black")
        btnA13.configure(pady="0")
        btnA13.configure(text='''13''')

        btnA14 = tk.Button(top)
        btnA14.place(relx=0.706, rely=0.171, height=24, width=27)
        btnA14.configure(activebackground="#f9f9f9")
        btnA14.configure(activeforeground="black")
        btnA14.configure(background="#888bf9")
        btnA14.configure(disabledforeground="#a3a3a3")
        btnA14.configure(foreground="#000000")
        btnA14.configure(highlightbackground="#d9d9d9")
        btnA14.configure(highlightcolor="black")
        btnA14.configure(pady="0")
        btnA14.configure(text='''14''')

        btnA19 = tk.Button(top)
        btnA19.place(relx=0.635, rely=0.235, height=24, width=27)
        btnA19.configure(activebackground="#f9f9f9")
        btnA19.configure(activeforeground="black")
        btnA19.configure(background="#888bf9")
        btnA19.configure(disabledforeground="#a3a3a3")
        btnA19.configure(foreground="#000000")
        btnA19.configure(highlightbackground="#d9d9d9")
        btnA19.configure(highlightcolor="black")
        btnA19.configure(pady="0")
        btnA19.configure(text='''19''')

        btnA20 = tk.Button(top)
        btnA20.place(relx=0.706, rely=0.235, height=24, width=27)
        btnA20.configure(activebackground="#f9f9f9")
        btnA20.configure(activeforeground="black")
        btnA20.configure(background="#888bf9")
        btnA20.configure(disabledforeground="#a3a3a3")
        btnA20.configure(foreground="#000000")
        btnA20.configure(highlightbackground="#d9d9d9")
        btnA20.configure(highlightcolor="black")
        btnA20.configure(pady="0")
        btnA20.configure(text='''20''')

        menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = menubar)

        Frame1 = tk.Frame(top)
        Frame1.place(relx=0.024, rely=0.299, relheight=0.693
                , relwidth=0.953)
        Frame1.configure(relief="groove")
        Frame1.configure(background="#d9d9d9")
        Frame1.configure(highlightbackground="#d9d9d9")
        Frame1.configure(highlightcolor="black")

        Frame2_16 = tk.Frame(Frame1)
        Frame2_16.place(relx=0.025, rely=0.523, relheight=0.212
                , relwidth=0.469)
        Frame2_16.configure(relief='groove')
        Frame2_16.configure(borderwidth="2")
        Frame2_16.configure(relief="groove")
        Frame2_16.configure(background="#d9d9d9")
        Frame2_16.configure(highlightbackground="#d9d9d9")
        Frame2_16.configure(highlightcolor="black")

        drpbxBorrPas = ttk.Combobox(Frame2_16)
        drpbxBorrPas.place(relx=0.526, rely=0.145, relheight=0.29
                , relwidth=0.437)
        drpbxBorrPas.configure(textvariable=pasajeavion2_support.combobox)
        drpbxBorrPas.configure(takefocus="")
        drpbxBorrPas.configure(cursor="fleur")

        btnBorrPas = ttk.Button(Frame2_16)
        btnBorrPas.place(relx=0.053, rely=0.507, height=25, width=176)
        btnBorrPas.configure(command=pasajeavion2_support.borrPas)
        btnBorrPas.configure(takefocus="")
        btnBorrPas.configure(text='''Borrar''')

        Label5 = tk.Label(Frame2_16)
        Label5.place(relx=0.053, rely=0.116, height=18, width=84)
        Label5.configure(activebackground="#f9f9f9")
        Label5.configure(activeforeground="black")
        Label5.configure(background="#d9d9d9")
        Label5.configure(disabledforeground="#a3a3a3")
        Label5.configure(foreground="#000000")
        Label5.configure(highlightbackground="#d9d9d9")
        Label5.configure(highlightcolor="black")
        Label5.configure(text='''Dni a borrar:''')

        Frame2 = tk.Frame(Frame1)
        Frame2.place(relx=0.025, rely=0.031, relheight=0.477
                , relwidth=0.975)
        Frame2.configure(relief='groove')
        Frame2.configure(borderwidth="2")
        Frame2.configure(relief="groove")
        Frame2.configure(background="#d9d9d9")
        Frame2.configure(highlightbackground="#d9d9d9")
        Frame2.configure(highlightcolor="black")

        Label1 = tk.Label(Frame2)
        Label1.place(relx=0.025, rely=0.065, height=21, width=104)
        Label1.configure(activebackground="#f9f9f9")
        Label1.configure(activeforeground="black")
        Label1.configure(background="#d9d9d9")
        Label1.configure(disabledforeground="#a3a3a3")
        Label1.configure(foreground="#000000")
        Label1.configure(highlightbackground="#d9d9d9")
        Label1.configure(highlightcolor="black")
        Label1.configure(text='''Nombre y apellido:''')

        entPasaj = tk.Entry(Frame2)
        entPasaj.place(relx=0.329, rely=0.065,height=20, relwidth=0.618)
        entPasaj.configure(background="#ffffffffffff")
        entPasaj.configure(disabledforeground="#a3a3a3")
        entPasaj.configure(font="TkFixedFont")
        entPasaj.configure(foreground="#000000")
        entPasaj.configure(highlightbackground="#d9d9d9")
        entPasaj.configure(highlightcolor="black")
        entPasaj.configure(insertbackground="black")
        entPasaj.configure(selectbackground="#c4c4c4")
        entPasaj.configure(selectforeground="black")

        Label2 = tk.Label(Frame2)
        Label2.place(relx=0.101, rely=0.258, height=21, width=34)
        Label2.configure(activebackground="#f9f9f9")
        Label2.configure(activeforeground="black")
        Label2.configure(background="#d9d9d9")
        Label2.configure(disabledforeground="#a3a3a3")
        Label2.configure(foreground="#000000")
        Label2.configure(highlightbackground="#d9d9d9")
        Label2.configure(highlightcolor="black")
        Label2.configure(text='''DNI:''')

        entDni = tk.Entry(Frame2)
        entDni.place(relx=0.329, rely=0.258,height=20, relwidth=0.213)
        entDni.configure(background="white")
        entDni.configure(disabledforeground="#a3a3a3")
        entDni.configure(font="TkFixedFont")
        entDni.configure(foreground="#000000")
        entDni.configure(highlightbackground="#d9d9d9")
        entDni.configure(highlightcolor="black")
        entDni.configure(insertbackground="black")
        entDni.configure(selectbackground="#c4c4c4")
        entDni.configure(selectforeground="black")

        clase=tk.StringVar(Frame2)
        rdbtnClaseTur = tk.Radiobutton(Frame2)
        rdbtnClaseTur.place(relx=0.329, rely=0.387, relheight=0.161
                , relwidth=0.147)
        rdbtnClaseTur.configure(activebackground="#ececec")
        rdbtnClaseTur.configure(activeforeground="#000000")
        rdbtnClaseTur.configure(background="#d9d9d9")
        rdbtnClaseTur.configure(disabledforeground="#a3a3a3")
        rdbtnClaseTur.configure(foreground="#000000")
        rdbtnClaseTur.configure(highlightbackground="#d9d9d9")
        rdbtnClaseTur.configure(highlightcolor="black")
        rdbtnClaseTur.configure(justify='left')
        rdbtnClaseTur.configure(text='''Turista''')
        rdbtnClaseTur.configure(value=1)
        rdbtnClaseTur.configure(variable=clase)

        rdbtnClaseEjec = tk.Radiobutton(Frame2)
        rdbtnClaseEjec.place(relx=0.532, rely=0.387, relheight=0.161
                , relwidth=0.197)
        rdbtnClaseEjec.configure(activebackground="#ececec")
        rdbtnClaseEjec.configure(activeforeground="#000000")
        rdbtnClaseEjec.configure(background="#d9d9d9")
        rdbtnClaseEjec.configure(disabledforeground="#a3a3a3")
        rdbtnClaseEjec.configure(foreground="#000000")
        rdbtnClaseEjec.configure(highlightbackground="#d9d9d9")
        rdbtnClaseEjec.configure(highlightcolor="black")
        rdbtnClaseEjec.configure(justify='left')
        rdbtnClaseEjec.configure(text='''Ejecutivo''')
        rdbtnClaseEjec.configure(value=2)
        rdbtnClaseEjec.configure(variable=clase)

        Label3 = tk.Label(Frame2)
        Label3.place(relx=0.101, rely=0.387, height=21, width=34)
        Label3.configure(activebackground="#f9f9f9")
        Label3.configure(activeforeground="black")
        Label3.configure(background="#d9d9d9")
        Label3.configure(disabledforeground="#a3a3a3")
        Label3.configure(foreground="#000000")
        Label3.configure(highlightbackground="#d9d9d9")
        Label3.configure(highlightcolor="black")
        Label3.configure(text='''Clase:''')

        lugares = {"ventana", "centro", "pasillo"}
        eleccion=tk.StringVar(Frame2)
        eleccion.set("Elija un lugar")
        cmboxLug = tk.OptionMenu(Frame2,eleccion,*lugares)
        cmboxLug.place(relx=0.329, rely=0.516, relheight=0.161
                , relwidth=0.372)
        cmboxLug.configure(background="#d9d9d9")
        cmboxLug.configure(justify='left')





        Label4 = tk.Label(Frame2)
        Label4.place(relx=0.101, rely=0.516, height=21, width=34)
        Label4.configure(activebackground="#f9f9f9")
        Label4.configure(activeforeground="black")
        Label4.configure(background="#d9d9d9")
        Label4.configure(disabledforeground="#a3a3a3")
        Label4.configure(foreground="#000000")
        Label4.configure(highlightbackground="#d9d9d9")
        Label4.configure(highlightcolor="black")
        Label4.configure(text='''Lugar''')

        lblEstado = tk.Label(Frame2)
        lblEstado.place(relx=0.076, rely=0.839, height=21, width=334)
        lblEstado.configure(activebackground="#f9f9f9")
        lblEstado.configure(activeforeground="black")
        lblEstado.configure(background="#d9d9d9")
        lblEstado.configure(disabledforeground="#a3a3a3")
        lblEstado.configure(foreground="#000000")
        lblEstado.configure(highlightbackground="#d9d9d9")
        lblEstado.configure(highlightcolor="black")

        Frame2_17 = tk.Frame(Frame1)
        Frame2_17.place(relx=0.025, rely=0.738, relheight=0.243
                , relwidth=0.469)
        Frame2_17.configure(relief='groove')
        Frame2_17.configure(borderwidth="2")
        Frame2_17.configure(relief="groove")
        Frame2_17.configure(background="#d9d9d9")
        Frame2_17.configure(cursor="fleur")
        Frame2_17.configure(highlightbackground="#d9d9d9")
        Frame2_17.configure(highlightcolor="black")

        btnActPorc = ttk.Button(Frame2_17)
        btnActPorc.place(relx=0.053, rely=0.127, height=25, width=176)
        btnActPorc.configure(command=pasajeavion2_support.actPorc)
        btnActPorc.configure(takefocus="")
        btnActPorc.configure(text='''Porcentaje de ocupacion''')

        lblOcup = tk.Label(Frame2_17)
        lblOcup.place(relx=0.053, rely=0.506, height=30, width=174)
        lblOcup.configure(activebackground="#f9f9f9")
        lblOcup.configure(activeforeground="black")
        lblOcup.configure(background="#d9d9d9")
        lblOcup.configure(disabledforeground="#a3a3a3")
        lblOcup.configure(foreground="#000000")
        lblOcup.configure(highlightbackground="#d9d9d9")
        lblOcup.configure(highlightcolor="black")

        Frame3 = tk.Frame(Frame1)
        Frame3.place(relx=0.519, rely=0.523, relheight=0.446
                , relwidth=0.481)
        Frame3.configure(relief='groove')
        Frame3.configure(borderwidth="2")
        Frame3.configure(relief="groove")
        Frame3.configure(background="#d9d9d9")

        Label6 = tk.Label(Frame3)
        Label6.place(relx=0.051, rely=0.069, height=21, width=84)
        Label6.configure(background="#d9d9d9")
        Label6.configure(disabledforeground="#a3a3a3")
        Label6.configure(foreground="#000000")
        Label6.configure(text='''Buscar por dni''')

        drpbxBorrPas_1 = ttk.Combobox(Frame3)
        drpbxBorrPas_1.place(relx=0.769, rely=-0.207, relheight=0.138
                , relwidth=0.374)
        drpbxBorrPas_1.configure(textvariable=pasajeavion2_support.combobox)
        drpbxBorrPas_1.configure(takefocus="")
        drpbxBorrPas_1.configure(cursor="fleur")

        drpbxBuscDni = ttk.Combobox(Frame3)
        drpbxBuscDni.place(relx=0.513, rely=0.069, relheight=0.138
                , relwidth=0.426)
        drpbxBuscDni.configure(takefocus="")

        Label1_4 = tk.Label(Frame3)
        Label1_4.place(relx=0.051, rely=0.483, height=21, width=174)
        Label1_4.configure(activebackground="#f9f9f9")
        Label1_4.configure(activeforeground="black")
        Label1_4.configure(background="#d9d9d9")
        Label1_4.configure(disabledforeground="#a3a3a3")
        Label1_4.configure(foreground="#000000")
        Label1_4.configure(highlightbackground="#d9d9d9")
        Label1_4.configure(highlightcolor="black")
        Label1_4.configure(text='''Pasajero:''')

        lblPasajBuscar = tk.Label(Frame3)
        lblPasajBuscar.place(relx=0.051, rely=0.621, height=21, width=174)
        lblPasajBuscar.configure(activebackground="#f9f9f9")
        lblPasajBuscar.configure(activeforeground="black")
        lblPasajBuscar.configure(background="#d9d9d9")
        lblPasajBuscar.configure(cursor="fleur")
        lblPasajBuscar.configure(disabledforeground="#a3a3a3")
        lblPasajBuscar.configure(foreground="#000000")
        lblPasajBuscar.configure(highlightbackground="#d9d9d9")
        lblPasajBuscar.configure(highlightcolor="black")

        Label1_5 = tk.Label(Frame3)
        Label1_5.place(relx=0.154, rely=0.759, height=21, width=54)
        Label1_5.configure(activebackground="#f9f9f9")
        Label1_5.configure(activeforeground="black")
        Label1_5.configure(background="#d9d9d9")
        Label1_5.configure(cursor="fleur")
        Label1_5.configure(disabledforeground="#a3a3a3")
        Label1_5.configure(foreground="#000000")
        Label1_5.configure(highlightbackground="#d9d9d9")
        Label1_5.configure(highlightcolor="black")
        Label1_5.configure(text='''Asiento:''')

        lblAsientoBuscar = tk.Label(Frame3)
        lblAsientoBuscar.place(relx=0.513, rely=0.759, height=21, width=59)
        lblAsientoBuscar.configure(background="#d9d9d9")
        lblAsientoBuscar.configure(disabledforeground="#a3a3a3")
        lblAsientoBuscar.configure(foreground="#000000")

        btnBuscar = ttk.Button(Frame3)
        btnBuscar.place(relx=0.051, rely=0.276, height=25, width=176)
        btnBuscar.configure(command=pasajeavion2_support.buscarPasajero)
        btnBuscar.configure(takefocus="")
        btnBuscar.configure(text='''Buscar''')

        btnRegPas = ttk.Button(Frame2)
        btnRegPas.place(relx=0.076, rely=0.685, height=25, width=336)
        btnRegPas.configure(command= lambda :pasajeavion2_support.regPas(entPasaj.get(),entDni.get(),clase.get(),eleccion.get()))
        btnRegPas.configure(takefocus="")
        btnRegPas.configure(text='''Registrar Pasajero''')

if __name__ == '__main__':
    vp_start_gui()





