#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 16, 2020 12:52:03 PM -03  platform: Windows NT

import sys
import pasajeavion
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top








def busPas():
    print('pasajeavion_support.busPas')
    sys.stdout.flush()

def elimPas():
    print('pasajeavion_support.elimPas')
    sys.stdout.flush()

def regPas():
    registro = tk.Toplevel(pasajeavion.master)
    registro.geometry("425x469+582+146")

def PorcOcup():
    print("a")
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import pasajeavion
    pasajeavion.vp_start_gui()




