#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Apr 15, 2020 09:02:48 PM -03  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 800x750+589+83
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "reservasEnUnVuelo" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    canvas $top.can44 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 644 -insertbackground black -relief sunken \
        -selectbackground #c4c4c4 -selectforeground black -width 414 
    vTcl:DefineAlias "$top.can44" "totalidadAvion" vTcl:WidgetProc "reservasEnUnVuelo" 1
    set site_3_0 $top.can44
    canvas $site_3_0.can51 \
        -background #8d9669 -borderwidth 2 -closeenough 1.0 -height 603 \
        -insertbackground black -relief sunken -selectbackground #c4c4c4 \
        -selectforeground black -width 43 
    vTcl:DefineAlias "$site_3_0.can51" "pasillo" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab52 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 9 
    vTcl:DefineAlias "$site_3_0.lab52" "pasajero9" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab53 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 10 
    vTcl:DefineAlias "$site_3_0.lab53" "pasajero10" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab54 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 11 
    vTcl:DefineAlias "$site_3_0.lab54" "pasajero11" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab55 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 12 
    vTcl:DefineAlias "$site_3_0.lab55" "pasajero12" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab56 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 13 
    vTcl:DefineAlias "$site_3_0.lab56" "pasajero13" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab57 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 14 
    vTcl:DefineAlias "$site_3_0.lab57" "pasajero14" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab58 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 15 
    vTcl:DefineAlias "$site_3_0.lab58" "pasajero15" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab59 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 16 
    vTcl:DefineAlias "$site_3_0.lab59" "pasajero16" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab60 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 17 
    vTcl:DefineAlias "$site_3_0.lab60" "pasajero17" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab61 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 18 
    vTcl:DefineAlias "$site_3_0.lab61" "pasajero18" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab62 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 19 
    vTcl:DefineAlias "$site_3_0.lab62" "pasajero19" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab63 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 20 
    vTcl:DefineAlias "$site_3_0.lab63" "pasajero20" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab64 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 21 
    vTcl:DefineAlias "$site_3_0.lab64" "pasajero21" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab65 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 22 
    vTcl:DefineAlias "$site_3_0.lab65" "pasajero22" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab66 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 23 
    vTcl:DefineAlias "$site_3_0.lab66" "pasajero23" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab67 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 24 
    vTcl:DefineAlias "$site_3_0.lab67" "pasajero24" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab68 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 25 
    vTcl:DefineAlias "$site_3_0.lab68" "pasajero25" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab69 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 26 
    vTcl:DefineAlias "$site_3_0.lab69" "pasajero26" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab70 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 27 
    vTcl:DefineAlias "$site_3_0.lab70" "pasajero27" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab71 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 28 
    vTcl:DefineAlias "$site_3_0.lab71" "pasajero28" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab72 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 29 
    vTcl:DefineAlias "$site_3_0.lab72" "pasajero29" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab73 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 30 
    vTcl:DefineAlias "$site_3_0.lab73" "pasajero30" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab74 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 31 
    vTcl:DefineAlias "$site_3_0.lab74" "pasajero31" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab75 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 32 
    vTcl:DefineAlias "$site_3_0.lab75" "pasajero32" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab76 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 33 
    vTcl:DefineAlias "$site_3_0.lab76" "pasajero33" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab77 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 34 
    vTcl:DefineAlias "$site_3_0.lab77" "pasajero34" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab78 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 35 
    vTcl:DefineAlias "$site_3_0.lab78" "pasajero35" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab79 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 36 
    vTcl:DefineAlias "$site_3_0.lab79" "pasajero36" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab80 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 37 
    vTcl:DefineAlias "$site_3_0.lab80" "pasajero37" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab81 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 38 
    vTcl:DefineAlias "$site_3_0.lab81" "pasajero38" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab82 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 39 
    vTcl:DefineAlias "$site_3_0.lab82" "pasajero39" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab83 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 40 
    vTcl:DefineAlias "$site_3_0.lab83" "pasajero40" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab84 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 41 
    vTcl:DefineAlias "$site_3_0.lab84" "pasajero41" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab85 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 42 
    vTcl:DefineAlias "$site_3_0.lab85" "pasajero42" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab86 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 43 
    vTcl:DefineAlias "$site_3_0.lab86" "pasajero43" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab87 \
        -background #00ff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 44 
    vTcl:DefineAlias "$site_3_0.lab87" "pasajero44" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab89 \
        -background #80ffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 1 
    vTcl:DefineAlias "$site_3_0.lab89" "pasajero1" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab90 \
        -background #80ffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 2 
    vTcl:DefineAlias "$site_3_0.lab90" "pasajero2" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab91 \
        -background #80ffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 5 
    vTcl:DefineAlias "$site_3_0.lab91" "pasajero5" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab92 \
        -background #80ffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 6 
    vTcl:DefineAlias "$site_3_0.lab92" "pasajero6" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab93 \
        -background #80ffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 3 
    vTcl:DefineAlias "$site_3_0.lab93" "pasajero3" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab94 \
        -background #80ffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 4 
    vTcl:DefineAlias "$site_3_0.lab94" "pasajero4" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab95 \
        -background #80ffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 7 
    vTcl:DefineAlias "$site_3_0.lab95" "pasajero7" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab96 \
        -background #80ffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -relief raised -text 8 
    vTcl:DefineAlias "$site_3_0.lab96" "pasajero8" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab103 \
        -activebackground #f9f9f9 -activeforeground black -background #00ff00 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief raised -text 46 
    vTcl:DefineAlias "$site_3_0.lab103" "pasajero46" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab104 \
        -activebackground #f9f9f9 -activeforeground black -background #00ff00 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief raised -text 45 
    vTcl:DefineAlias "$site_3_0.lab104" "pasajero45" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab105 \
        -activebackground #f9f9f9 -activeforeground black -background #00ff00 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief raised -text 47 
    vTcl:DefineAlias "$site_3_0.lab105" "pasajero47" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab106 \
        -activebackground #f9f9f9 -activeforeground black -background #00ff00 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief raised -text 48 
    vTcl:DefineAlias "$site_3_0.lab106" "pasajero48" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab107 \
        -activebackground #f9f9f9 -activeforeground black -background #00ff00 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief raised -text 49 
    vTcl:DefineAlias "$site_3_0.lab107" "pasajero49" vTcl:WidgetProc "reservasEnUnVuelo" 1
    label $site_3_0.lab108 \
        -activebackground #f9f9f9 -activeforeground black -background #00ff00 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -relief raised -text 50 
    vTcl:DefineAlias "$site_3_0.lab108" "pasajero50" vTcl:WidgetProc "reservasEnUnVuelo" 1
    place $site_3_0.can51 \
        -in $site_3_0 -x 0 -relx 0.453 -y 0 -width 0 -relwidth 0.095 \
        -height 0 -relheight 0.998 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.043 -y 0 -rely 0.248 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.194 -y 0 -rely 0.248 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.345 -y 0 -rely 0.248 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.56 -y 0 -rely 0.248 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.711 -y 0 -rely 0.248 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.862 -y 0 -rely 0.248 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 0 -relx 0.043 -y 0 -rely 0.315 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -relx 0.194 -y 0 -rely 0.315 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.345 -y 0 -rely 0.315 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.56 -y 0 -rely 0.315 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 0 -relx 0.711 -y 0 -rely 0.315 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -relx 0.862 -y 0 -rely 0.315 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 0 -relx 0.043 -y 0 -rely 0.381 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 0 -relx 0.194 -y 0 -rely 0.381 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 0 -relx 0.345 -y 0 -rely 0.381 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 0 -relx 0.56 -y 0 -rely 0.381 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.711 -y 0 -rely 0.381 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 0 -relx 0.862 -y 0 -rely 0.381 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 0 -relx 0.043 -y 0 -rely 0.447 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 0 -relx 0.194 -y 0 -rely 0.447 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 0 -relx 0.345 -y 0 -rely 0.447 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 0 -relx 0.56 -y 0 -rely 0.447 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 0 -relx 0.711 -y 0 -rely 0.447 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab75 \
        -in $site_3_0 -x 0 -relx 0.862 -y 0 -rely 0.447 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 0 -relx 0.043 -y 0 -rely 0.513 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab77 \
        -in $site_3_0 -x 0 -relx 0.194 -y 0 -rely 0.513 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 0 -relx 0.345 -y 0 -rely 0.513 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab79 \
        -in $site_3_0 -x 0 -relx 0.56 -y 0 -rely 0.513 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab80 \
        -in $site_3_0 -x 0 -relx 0.711 -y 0 -rely 0.513 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 0 -relx 0.862 -y 0 -rely 0.513 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab82 \
        -in $site_3_0 -x 0 -relx 0.043 -y 0 -rely 0.579 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab83 \
        -in $site_3_0 -x 0 -relx 0.194 -y 0 -rely 0.579 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab84 \
        -in $site_3_0 -x 0 -relx 0.345 -y 0 -rely 0.579 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab85 \
        -in $site_3_0 -x 0 -relx 0.56 -y 0 -rely 0.579 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab86 \
        -in $site_3_0 -x 0 -relx 0.711 -y 0 -rely 0.579 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab87 \
        -in $site_3_0 -x 0 -relx 0.862 -y 0 -rely 0.579 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab89 \
        -in $site_3_0 -x 0 -relx 0.096 -y 0 -rely 0.062 -width 0 \
        -relwidth 0.101 -height 0 -relheight 0.04 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab90 \
        -in $site_3_0 -x 0 -relx 0.264 -y 0 -rely 0.062 -width 0 \
        -relwidth 0.101 -height 0 -relheight 0.04 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab91 \
        -in $site_3_0 -x 0 -relx 0.096 -y 0 -rely 0.14 -width 0 \
        -relwidth 0.101 -height 0 -relheight 0.04 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab92 \
        -in $site_3_0 -x 0 -relx 0.264 -y 0 -rely 0.14 -width 0 \
        -relwidth 0.101 -height 0 -relheight 0.04 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab93 \
        -in $site_3_0 -x 0 -relx 0.625 -y 0 -rely 0.062 -width 0 \
        -relwidth 0.101 -height 0 -relheight 0.04 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab94 \
        -in $site_3_0 -x 0 -relx 0.793 -y 0 -rely 0.062 -width 0 \
        -relwidth 0.101 -height 0 -relheight 0.04 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab95 \
        -in $site_3_0 -x 0 -relx 0.625 -y 0 -rely 0.14 -width 0 \
        -relwidth 0.101 -height 0 -relheight 0.04 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab96 \
        -in $site_3_0 -x 0 -relx 0.793 -y 0 -rely 0.14 -width 0 \
        -relwidth 0.101 -height 0 -relheight 0.04 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab103 \
        -in $site_3_0 -x 0 -relx 0.195 -y 0 -rely 0.652 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.042 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab104 \
        -in $site_3_0 -x 0 -relx 0.043 -y 0 -rely 0.652 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab105 \
        -in $site_3_0 -x 0 -relx 0.346 -y 0 -rely 0.652 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab106 \
        -in $site_3_0 -x 0 -relx 0.56 -y 0 -rely 0.652 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab107 \
        -in $site_3_0 -x 0 -relx 0.712 -y 0 -rely 0.652 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab108 \
        -in $site_3_0 -x 0 -relx 0.863 -y 0 -rely 0.652 -width 0 \
        -relwidth 0.091 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu45 \
        -command registroDePasajero -takefocus {} -text {Registrar Pasajero} 
    vTcl:DefineAlias "$top.tBu45" "TButton1" vTcl:WidgetProc "reservasEnUnVuelo" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu46 \
        -command eliminarPasajero -takefocus {} -text {Eliminar Pasajero} 
    vTcl:DefineAlias "$top.tBu46" "TButton2" vTcl:WidgetProc "reservasEnUnVuelo" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu47 \
        -command buscarPasajero -takefocus {} -text {Buscar Pasajero} 
    vTcl:DefineAlias "$top.tBu47" "TButton3" vTcl:WidgetProc "reservasEnUnVuelo" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu48 \
        -command porcentajeOcupacion -takefocus {} \
        -text {Porcentaje Ocupacion} 
    vTcl:DefineAlias "$top.tBu48" "TButton4" vTcl:WidgetProc "reservasEnUnVuelo" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu49 \
        -takefocus {} -text {Opcion 1} 
    vTcl:DefineAlias "$top.tBu49" "TButton5" vTcl:WidgetProc "reservasEnUnVuelo" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $top.tBu50 \
        -takefocus {} -text {Opcion 2} 
    vTcl:DefineAlias "$top.tBu50" "TButton6" vTcl:WidgetProc "reservasEnUnVuelo" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can44 \
        -in $top -x 0 -relx 0.263 -y 0 -rely 0.038 -width 0 -relwidth 0.52 \
        -height 0 -relheight 0.805 -anchor nw -bordermode ignore 
    place $top.tBu45 \
        -in $top -x 0 -relx 0.15 -y 0 -rely 0.863 -width 168 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tBu46 \
        -in $top -x 0 -relx 0.425 -y 0 -rely 0.863 -width 168 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tBu47 \
        -in $top -x 0 -relx 0.7 -y 0 -rely 0.863 -width 168 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tBu48 \
        -in $top -x 0 -relx 0.15 -y 0 -rely 0.938 -width 168 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tBu49 \
        -in $top -x 0 -relx 0.425 -y 0 -rely 0.938 -width 168 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tBu50 \
        -in $top -x 0 -relx 0.7 -y 0 -rely 0.938 -width 168 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

