#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 16, 2020 06:04:27 PM -03  platform: Windows NT

import sys
import re
from tkinter import messagebox

try:
    import Tkinter as tk

except ImportError:
    import tkinter as tk


try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def set_Tk_var():
    global A01
    A01 = tk.StringVar()
    A01.set('A001')
    global A02
    A02 = tk.StringVar()
    A02.set('A002')
    global A03
    A03 = tk.StringVar()
    A03.set('A003')
    global A04
    A04 = tk.StringVar()
    A04.set('A004')
    global A05
    A05 = tk.StringVar()
    A05.set('A005')
    global A06
    A06 = tk.StringVar()
    A06.set('A006')
    global A07
    A07 = tk.StringVar()
    A07.set('A007')
    global A08
    A08 = tk.StringVar()
    A08.set('A008')
    global A09
    A09 = tk.StringVar()
    A09.set('A009')
    global A10
    A10 = tk.StringVar()
    A10.set('A010')
    global A11
    A11 = tk.StringVar()
    A11.set('A011')
    global A12
    A12 = tk.StringVar()
    A12.set('A012')
    global nom
    nom = tk.StringVar()
    global combo_cat
    combo_cat = tk.StringVar()
    global dni
    dni = tk.StringVar()
    global combo_tipo
    combo_tipo = tk.StringVar()
    global A13
    A13 = tk.StringVar()
    A13.set('A013')
    global A14
    A14 = tk.StringVar()
    A14.set('A014')
    global A15
    A15 = tk.StringVar()
    A15.set('A015')
    global A16
    A16 = tk.StringVar()
    A16.set('A016')
    global A17
    A17 = tk.StringVar()
    A17.set('A017')
    global A18
    A18 = tk.StringVar()
    A18.set('A018')
    global A19
    A19 = tk.StringVar()
    A19.set('A019')
    global A20
    A20 = tk.StringVar()
    A20.set('A020')


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

global listaPasajerosPri
listaPasajerosPri = []
global listaPasajerosTur
listaPasajerosTur = []

global listaButacasA1
listaButacasA1 = []
global listaButacasA2
listaButacasA2 = []
global listaButacasB1
listaButacasB1 = []


def crear_lst_butacas():
    nombre = nom.get()
    but01 = A01.get()
    but02 = A02.get()
    but03 = A03.get()
    if but01 == "Ocupado":
        print("count1"+ str(count1))
        lbl77 = tk.Label(root, width=15,text='Datos del ultimo Pasajero:\n' + f'{nombre}\n''Categoria: ' + f'{cat}\n''Ubicacion: ' + f'{tip}\n''Butaca: ''A00' + f'{count1}',background="#d9d9d9", font="Arial")
        lbl77.place(relx=0.032, rely=0.634, height=100, width=200)
    if but02 == "Ocupado":
        print("count2"+ str(count2))
        lbl77 = tk.Label(root, width=15,
                         text='Datos del ultimo Pasajero:\n' + f'{nombre}\n''Categoria: ' + f'{cat}\n''Ubicacion: ' + f'{tip}\n''Butaca: ''A00' + f'{count2}',background="#d9d9d9", font="Arial")
        lbl77.place(relx=0.032, rely=0.634, height=100, width=200)
    if but03 == "Ocupado":
        print("count3"+ str(count3))
        lbl77 = tk.Label(root, width=15,text='Datos del ultimo Pasajero:\n' + f'{nombre}\n''Categoria: ' + f'{cat}\n''Ubicacion: ' + f'{tip}\n''Butaca: ''A00' + f'{count3}',background="#d9d9d9", font="Arial")
        lbl77.place(relx=0.032, rely=0.634, height=100, width=200)


def Registrar():
    global cat
    cat = combo_cat.get()
    global tip
    tip = combo_tipo.get()
    if cat == "Primera" and tip == "Ventanilla":
        listaPasajerosPri.append(nom.get())
        listaPasajerosPri.append(cat)
        listaPasajerosPri.append(tip)
        listaButacasA1.append("A001")
        global count1
        count1 = 0
        global total
        total = + count1
        if count1 < 3:
            for but in listaButacasA1:
                count1 += 1
                if count1 == 1:
                    A01.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.4, rely=0.187, height=51, width=54)
                if count1 == 2:
                    A04.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.867, rely=0.187, height=49, width=55)
                if count1 == 3:
                    A05.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.4, rely=0.299, height=49, width=55)
                if count1 == 4:
                    A08.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.867, rely=0.299, height=49, width=55)
            total += count1
            print("conut1 es:" + str(count1))
            print(listaPasajerosPri)
            print(listaButacasA1)
            if count1 > 3:
                messagebox.showinfo(title='Atencion!!',
                                    message='Ya no quedan asientos disponibles en Ventanilla!!\n\nA partir de ahora debera asignar otro tipo de servicio',
                                    icon='warning')

    if cat == "Primera" and tip == "Pasillo":
        global count2
        count2 = 0
        listaPasajerosPri.append(nom.get())
        listaPasajerosPri.append(cat)
        listaPasajerosPri.append(tip)
        listaButacasA2.append("A002")
        if count2 < 3:
            for but in listaButacasA2:
                count2 += 1
                if count2 == 1:
                    A02.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.517, rely=0.187, height=51, width=54)
                if count2 == 2:
                    A03.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.75, rely=0.187, height=51, width=54)
                if count2 == 3:
                    A06.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.517, rely=0.299, height=49, width=55)
                if count2 == 4:
                    A07.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.75, rely=0.299, height=49, width=55)
            total = + count2
            print("conut2 es:" + str(count2))
            print(listaPasajerosPri)
            print(listaButacasA2)
        if count2 > 3:
            messagebox.showinfo(title='Atencion!!',
                                message='Ya no quedan asientos disponibles en Pasillo!!\n\nA partir de ahora debera asignar otro tipo de servicio',
                                icon='warning')
    if cat == "Turista":
        global count3
        count3 = 0
        listaPasajerosTur.append(nom.get())
        listaPasajerosTur.append(cat)
        listaPasajerosTur.append(tip)
        listaButacasB1.append("A003")
        if count3 < 11:
            for but in listaButacasB1:
                count3 += 1
                if count3 == 1:
                    A09.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.4, rely=0.43, height=49, width=55)
                if count3 == 2:
                    A10.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.517, rely=0.43, height=49, width=55)
                if count3 == 3:
                    A11.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.75, rely=0.43, height=49, width=55)
                if count3 == 4:
                    A12.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.867, rely=0.43, height=49, width=55)
                if count3 == 5:
                    A13.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.4, rely=0.542, height=51, width=54)
                if count3 == 6:
                    A14.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.517, rely=0.542, height=51, width=54)
                if count3 == 7:
                    A15.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.75, rely=0.542, height=51, width=54)
                if count3 == 8:
                    A16.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.867, rely=0.542, height=51, width=54)
                if count3 == 9:
                    A17.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.4, rely=0.654, height=51, width=54)
                if count3 == 10:
                    A18.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.517, rely=0.654, height=51, width=54)
                if count3 == 11:
                    A19.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.75, rely=0.654, height=51, width=54)
                if count3 == 12:
                    A20.set("Ocupado")
                    lbl77 = tk.Label(root, width=5, text='Ocupado',
                                     background="#ff0000")
                    lbl77.place(relx=0.867, rely=0.654, height=51, width=54)
            total += count3
            print("conut3 es:" + str(count3))
            print(listaPasajerosTur)
            print(listaButacasB1)
        if count3 > 11:
            messagebox.showinfo(title='Atencion!!',
                                message='Ya no quedan asientos disponibles en el sector Turistas!!\nDebera asignar otro tipo de servicio',
                                icon='warning')

def Porcentaje():
    total2 = count1 + count2 + count3
    porcent = total2 * 100 / 20
    lbl77 = tk.Label(root, width=20, text='El porcentaje de \nocupacion es de : ' + f"{porcent}"+"%", background="#d9d9d9", font="Arial")
    lbl77.place(relx=0.032, rely=0.634, height=100, width=200)



def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import SistemaAvion
    SistemaAvion.vp_start_gui()




