#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 16, 2020 11:17:15 AM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global nom
    nom = tk.StringVar()
    global combo_cat
    combo_cat = tk.StringVar()
    global combo_tipo
    combo_tipo = tk.StringVar()
    global dni
    dni = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def Registrar():
   listaPasajeros=[]
   listaPasajeros.append(nom.get())
   listaPasajeros.append(dni.get())
   listaPasajeros.append(combo_cat.get())
   listaPasajeros.append(combo_tipo.get())
   listaButacas = []
   if combo_cat == "Primera":
       listaButacas.append["A01"]
   lbl_But01 = tk.Label()
   lbl_But01.place(relx=0.4, rely=0.187, height=51, width=54)
   lbl_But01.configure(activebackground="#f9f9f9")
   lbl_But01.configure(activeforeground="black")
   lbl_But01.configure(background="#ffffff")
   lbl_But01.configure(disabledforeground="#a3a3a3")
   lbl_But01.configure(foreground="#000000")
   lbl_But01.configure(highlightbackground="#d9d9d9")
   lbl_But01.configure(highlightcolor="black")
   lbl_But01.configure(text='''A01''')
   print(listaButacas,listaPasajeros)


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import SistemaAvion
    SistemaAvion.vp_start_gui()




