#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 16, 2020 11:17:01 AM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import SistemaAvion_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    SistemaAvion_support.set_Tk_var()
    top = Sistema (root)
    SistemaAvion_support.init(root, top)
    root.mainloop()

w = None
def create_Sistema(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Sistema(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    SistemaAvion_support.set_Tk_var()
    top = Sistema (w)
    SistemaAvion_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Sistema():
    global w
    w.destroy()
    w = None

class Sistema:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x535+465+59")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1, 1)
        top.title("Sistema de Pasajes de Avion")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.btn_Registrar = ttk.Button(top)
        self.btn_Registrar.place(relx=0.017, rely=0.897, height=35, width=136)
        self.btn_Registrar.configure(command=SistemaAvion_support.Registrar)
        self.btn_Registrar.configure(takefocus="")
        self.btn_Registrar.configure(text='''Registrar Pasajero''')

        self.btn_Eliminar = ttk.Button(top)
        self.btn_Eliminar.place(relx=0.25, rely=0.897, height=35, width=146)
        self.btn_Eliminar.configure(takefocus="")
        self.btn_Eliminar.configure(text='''Eliminar Pasajero''')

        self.btn_Buscar = ttk.Button(top)
        self.btn_Buscar.place(relx=0.5, rely=0.897, height=35, width=136)
        self.btn_Buscar.configure(takefocus="")
        self.btn_Buscar.configure(text='''Buscar Pasajero''')

        self.btn_Procentaje = ttk.Button(top)
        self.btn_Procentaje.place(relx=0.733, rely=0.897, height=35, width=146)
        self.btn_Procentaje.configure(takefocus="")
        self.btn_Procentaje.configure(text='''Procentaje Pasajero''')

        self.lbl_But01 = tk.Label(top)
        self.lbl_But01.place(relx=0.4, rely=0.187, height=51, width=54)
        self.lbl_But01.configure(activebackground="#f9f9f9")
        self.lbl_But01.configure(activeforeground="black")
        self.lbl_But01.configure(background="#ffff00")
        self.lbl_But01.configure(disabledforeground="#a3a3a3")
        self.lbl_But01.configure(foreground="#000000")
        self.lbl_But01.configure(highlightbackground="#d9d9d9")
        self.lbl_But01.configure(highlightcolor="black")
        self.lbl_But01.configure(text='''A01''')

        self.lbl_But02 = tk.Label(top)
        self.lbl_But02.place(relx=0.517, rely=0.187, height=51, width=54)
        self.lbl_But02.configure(activebackground="#f9f9f9")
        self.lbl_But02.configure(activeforeground="black")
        self.lbl_But02.configure(background="#ffff00")
        self.lbl_But02.configure(disabledforeground="#a3a3a3")
        self.lbl_But02.configure(foreground="#000000")
        self.lbl_But02.configure(highlightbackground="#d9d9d9")
        self.lbl_But02.configure(highlightcolor="black")
        self.lbl_But02.configure(text='''A02''')

        self.lbl_But03 = tk.Label(top)
        self.lbl_But03.place(relx=0.75, rely=0.187, height=51, width=54)
        self.lbl_But03.configure(activebackground="#f9f9f9")
        self.lbl_But03.configure(activeforeground="black")
        self.lbl_But03.configure(background="#ffff00")
        self.lbl_But03.configure(disabledforeground="#a3a3a3")
        self.lbl_But03.configure(foreground="#000000")
        self.lbl_But03.configure(highlightbackground="#d9d9d9")
        self.lbl_But03.configure(highlightcolor="black")
        self.lbl_But03.configure(text='''A03''')

        self.lbl_But04 = ttk.Label(top)
        self.lbl_But04.place(relx=0.867, rely=0.187, height=49, width=55)
        self.lbl_But04.configure(background="#ffff00")
        self.lbl_But04.configure(foreground="#000000")
        self.lbl_But04.configure(font="TkDefaultFont")
        self.lbl_But04.configure(relief="flat")
        self.lbl_But04.configure(anchor='center')
        self.lbl_But04.configure(justify='left')
        self.lbl_But04.configure(text='''A04''')

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.633, rely=0.075, relheight=0.794
                , relwidth=0.092)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.lbl_But05 = ttk.Label(top)
        self.lbl_But05.place(relx=0.4, rely=0.299, height=49, width=55)
        self.lbl_But05.configure(background="#ffff00")
        self.lbl_But05.configure(foreground="#000000")
        self.lbl_But05.configure(font="TkDefaultFont")
        self.lbl_But05.configure(relief="flat")
        self.lbl_But05.configure(anchor='center')
        self.lbl_But05.configure(justify='left')
        self.lbl_But05.configure(text='''A05''')

        self.lbl_But06 = ttk.Label(top)
        self.lbl_But06.place(relx=0.517, rely=0.299, height=49, width=55)
        self.lbl_But06.configure(background="#ffff00")
        self.lbl_But06.configure(foreground="#000000")
        self.lbl_But06.configure(font="TkDefaultFont")
        self.lbl_But06.configure(relief="flat")
        self.lbl_But06.configure(anchor='center')
        self.lbl_But06.configure(justify='left')
        self.lbl_But06.configure(text='''A06''')

        self.lbl_But07 = ttk.Label(top)
        self.lbl_But07.place(relx=0.75, rely=0.299, height=49, width=55)
        self.lbl_But07.configure(background="#ffff00")
        self.lbl_But07.configure(foreground="#000000")
        self.lbl_But07.configure(font="TkDefaultFont")
        self.lbl_But07.configure(relief="flat")
        self.lbl_But07.configure(anchor='center')
        self.lbl_But07.configure(justify='left')
        self.lbl_But07.configure(text='''A07''')

        self.lblb_But08 = ttk.Label(top)
        self.lblb_But08.place(relx=0.867, rely=0.299, height=49, width=55)
        self.lblb_But08.configure(background="#ffff00")
        self.lblb_But08.configure(foreground="#000000")
        self.lblb_But08.configure(font="TkDefaultFont")
        self.lblb_But08.configure(relief="flat")
        self.lblb_But08.configure(anchor='center')
        self.lblb_But08.configure(justify='left')
        self.lblb_But08.configure(text='''A08''')

        self.lbl_But09 = ttk.Label(top)
        self.lbl_But09.place(relx=0.4, rely=0.43, height=49, width=55)
        self.lbl_But09.configure(background="#0000ff")
        self.lbl_But09.configure(foreground="#000000")
        self.lbl_But09.configure(font="TkDefaultFont")
        self.lbl_But09.configure(relief="flat")
        self.lbl_But09.configure(anchor='center')
        self.lbl_But09.configure(justify='left')
        self.lbl_But09.configure(text='''A09''')

        self.lbl_But10 = ttk.Label(top)
        self.lbl_But10.place(relx=0.517, rely=0.43, height=49, width=55)
        self.lbl_But10.configure(background="#0000ff")
        self.lbl_But10.configure(foreground="#000000")
        self.lbl_But10.configure(font="TkDefaultFont")
        self.lbl_But10.configure(relief="flat")
        self.lbl_But10.configure(anchor='center')
        self.lbl_But10.configure(justify='left')
        self.lbl_But10.configure(text='''A10''')

        self.lbl_But11 = ttk.Label(top)
        self.lbl_But11.place(relx=0.75, rely=0.43, height=49, width=55)
        self.lbl_But11.configure(background="#0000ff")
        self.lbl_But11.configure(foreground="#000000")
        self.lbl_But11.configure(font="TkDefaultFont")
        self.lbl_But11.configure(relief="flat")
        self.lbl_But11.configure(anchor='center')
        self.lbl_But11.configure(justify='left')
        self.lbl_But11.configure(text='''A11''')

        self.But12 = ttk.Label(top)
        self.But12.place(relx=0.867, rely=0.43, height=49, width=55)
        self.But12.configure(background="#0000ff")
        self.But12.configure(foreground="#000000")
        self.But12.configure(font="TkDefaultFont")
        self.But12.configure(relief="flat")
        self.But12.configure(anchor='center')
        self.But12.configure(justify='left')
        self.But12.configure(text='''A12''')

        self.TFrame1 = ttk.Frame(top)
        self.TFrame1.place(relx=0.017, rely=0.056, relheight=0.813
                , relwidth=0.358)
        self.TFrame1.configure(relief='groove')
        self.TFrame1.configure(borderwidth="2")
        self.TFrame1.configure(relief="groove")

        self.entry_Nom = ttk.Entry(self.TFrame1)
        self.entry_Nom.place(relx=0.093, rely=0.207, relheight=0.048
                , relwidth=0.819)
        self.entry_Nom.configure(textvariable=SistemaAvion_support.nom)
        self.entry_Nom.configure(takefocus="")
        self.entry_Nom.configure(cursor="ibeam")

        self.combo_categ = ttk.Combobox(self.TFrame1)
        self.combo_categ.place(relx=0.093, rely=0.483, relheight=0.048
                , relwidth=0.805)
        self.value_list = ['Primera','Turista',]
        self.combo_categ.configure(values=self.value_list)
        self.combo_categ.configure(textvariable=SistemaAvion_support.combo_cat)
        self.combo_categ.configure(takefocus="")

        self.combo_tipo = ttk.Combobox(self.TFrame1)
        self.combo_tipo.place(relx=0.093, rely=0.621, relheight=0.048
                , relwidth=0.805)
        self.value_list = ['Centro','Pasillo','Ventanilla',]
        self.combo_tipo.configure(values=self.value_list)
        self.combo_tipo.configure(textvariable=SistemaAvion_support.combo_tipo)
        self.combo_tipo.configure(takefocus="")

        self.lbl_Nombre = tk.Label(self.TFrame1)
        self.lbl_Nombre.place(relx=0.047, rely=0.138, height=31, width=104)
        self.lbl_Nombre.configure(activebackground="#f9f9f9")
        self.lbl_Nombre.configure(activeforeground="black")
        self.lbl_Nombre.configure(background="#d9d9d9")
        self.lbl_Nombre.configure(disabledforeground="#a3a3a3")
        self.lbl_Nombre.configure(foreground="#000000")
        self.lbl_Nombre.configure(highlightbackground="#d9d9d9")
        self.lbl_Nombre.configure(highlightcolor="black")
        self.lbl_Nombre.configure(text='''Nombre y Apellido''')

        self.lbl_DNI = tk.Label(self.TFrame1)
        self.lbl_DNI.place(relx=0.047, rely=0.299, height=21, width=26)
        self.lbl_DNI.configure(activebackground="#f9f9f9")
        self.lbl_DNI.configure(activeforeground="black")
        self.lbl_DNI.configure(background="#d9d9d9")
        self.lbl_DNI.configure(disabledforeground="#a3a3a3")
        self.lbl_DNI.configure(foreground="#000000")
        self.lbl_DNI.configure(highlightbackground="#d9d9d9")
        self.lbl_DNI.configure(highlightcolor="black")
        self.lbl_DNI.configure(text='''DNI''')

        self.lbl_Categ = tk.Label(self.TFrame1)
        self.lbl_Categ.place(relx=0.047, rely=0.437, height=21, width=64)
        self.lbl_Categ.configure(activebackground="#f9f9f9")
        self.lbl_Categ.configure(activeforeground="black")
        self.lbl_Categ.configure(background="#d9d9d9")
        self.lbl_Categ.configure(disabledforeground="#a3a3a3")
        self.lbl_Categ.configure(foreground="#000000")
        self.lbl_Categ.configure(highlightbackground="#d9d9d9")
        self.lbl_Categ.configure(highlightcolor="black")
        self.lbl_Categ.configure(text='''Categoria''')

        self.entry_DNI = ttk.Entry(self.TFrame1)
        self.entry_DNI.place(relx=0.093, rely=0.345, relheight=0.048
                , relwidth=0.819)
        self.entry_DNI.configure(textvariable=SistemaAvion_support.dni)
        self.entry_DNI.configure(takefocus="")
        self.entry_DNI.configure(cursor="ibeam")

        self.lbl_Tipo = tk.Label(self.TFrame1)
        self.lbl_Tipo.place(relx=0.047, rely=0.552, height=31, width=29)
        self.lbl_Tipo.configure(activebackground="#f9f9f9")
        self.lbl_Tipo.configure(activeforeground="black")
        self.lbl_Tipo.configure(background="#d9d9d9")
        self.lbl_Tipo.configure(disabledforeground="#a3a3a3")
        self.lbl_Tipo.configure(foreground="#000000")
        self.lbl_Tipo.configure(highlightbackground="#d9d9d9")
        self.lbl_Tipo.configure(highlightcolor="black")
        self.lbl_Tipo.configure(text='''Tipo''')

        self.lbl_But13 = tk.Label(top)
        self.lbl_But13.place(relx=0.4, rely=0.542, height=51, width=54)
        self.lbl_But13.configure(background="#0000ff")
        self.lbl_But13.configure(cursor="fleur")
        self.lbl_But13.configure(disabledforeground="#a3a3a3")
        self.lbl_But13.configure(foreground="#000000")
        self.lbl_But13.configure(text='''A13''')

        self.lbl_But14 = tk.Label(top)
        self.lbl_But14.place(relx=0.517, rely=0.542, height=51, width=54)
        self.lbl_But14.configure(background="#0000ff")
        self.lbl_But14.configure(disabledforeground="#a3a3a3")
        self.lbl_But14.configure(foreground="#000000")
        self.lbl_But14.configure(text='''A14''')

        self.lbl_But15 = tk.Label(top)
        self.lbl_But15.place(relx=0.75, rely=0.542, height=51, width=54)
        self.lbl_But15.configure(background="#0000ff")
        self.lbl_But15.configure(cursor="fleur")
        self.lbl_But15.configure(disabledforeground="#a3a3a3")
        self.lbl_But15.configure(foreground="#000000")
        self.lbl_But15.configure(text='''A15''')

        self.lbl_But16 = tk.Label(top)
        self.lbl_But16.place(relx=0.867, rely=0.542, height=51, width=54)
        self.lbl_But16.configure(background="#0000ff")
        self.lbl_But16.configure(disabledforeground="#a3a3a3")
        self.lbl_But16.configure(foreground="#000000")
        self.lbl_But16.configure(text='''A16''')

        self.lbl_But17 = tk.Label(top)
        self.lbl_But17.place(relx=0.4, rely=0.654, height=51, width=54)
        self.lbl_But17.configure(background="#0000ff")
        self.lbl_But17.configure(disabledforeground="#a3a3a3")
        self.lbl_But17.configure(foreground="#000000")
        self.lbl_But17.configure(text='''A17''')

        self.lbl_But18 = tk.Label(top)
        self.lbl_But18.place(relx=0.517, rely=0.654, height=51, width=54)
        self.lbl_But18.configure(background="#0000ff")
        self.lbl_But18.configure(disabledforeground="#a3a3a3")
        self.lbl_But18.configure(foreground="#000000")
        self.lbl_But18.configure(text='''A18''')

        self.lbl_But19 = tk.Label(top)
        self.lbl_But19.place(relx=0.75, rely=0.654, height=51, width=54)
        self.lbl_But19.configure(background="#0000ff")
        self.lbl_But19.configure(disabledforeground="#a3a3a3")
        self.lbl_But19.configure(foreground="#000000")
        self.lbl_But19.configure(text='''A19''')

        self.lbl_But20 = tk.Label(top)
        self.lbl_But20.place(relx=0.867, rely=0.654, height=51, width=54)
        self.lbl_But20.configure(background="#0000ff")
        self.lbl_But20.configure(disabledforeground="#a3a3a3")
        self.lbl_But20.configure(foreground="#000000")
        self.lbl_But20.configure(text='''A20''')

if __name__ == '__main__':
    vp_start_gui()





