#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 21, 2020 08:16:21 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import STAsientos_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    STAsientos_support.set_Tk_var()
    top = Toplevel1 (root)
    STAsientos_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    STAsientos_support.set_Tk_var()
    top = Toplevel1 (w)
    STAsientos_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("684x450+335+153")
        top.minsize(124, 1)
        top.maxsize(1362, 741)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.015, rely=0.022, relheight=0.611
                , relwidth=0.228)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.lblRegistro = tk.Label(self.Frame1)
        self.lblRegistro.place(relx=0.321, rely=0.036, height=21, width=49)
        self.lblRegistro.configure(activebackground="#f9f9f9")
        self.lblRegistro.configure(activeforeground="black")
        self.lblRegistro.configure(background="#d9d9d9")
        self.lblRegistro.configure(disabledforeground="#a3a3a3")
        self.lblRegistro.configure(foreground="#000000")
        self.lblRegistro.configure(highlightbackground="#d9d9d9")
        self.lblRegistro.configure(highlightcolor="black")
        self.lblRegistro.configure(text='''Registro''')

        self.lblNombre = tk.Label(self.Frame1)
        self.lblNombre.place(relx=0.321, rely=0.145, height=21, width=54)
        self.lblNombre.configure(activebackground="#f9f9f9")
        self.lblNombre.configure(activeforeground="black")
        self.lblNombre.configure(background="#d9d9d9")
        self.lblNombre.configure(disabledforeground="#a3a3a3")
        self.lblNombre.configure(foreground="#000000")
        self.lblNombre.configure(highlightbackground="#d9d9d9")
        self.lblNombre.configure(highlightcolor="black")
        self.lblNombre.configure(text='''Nombre:''')

        self.txtNombre = tk.Entry(self.Frame1)
        self.txtNombre.place(relx=0.256, rely=0.218,height=20, relwidth=0.538)
        self.txtNombre.configure(background="white")
        self.txtNombre.configure(disabledforeground="#a3a3a3")
        self.txtNombre.configure(font="TkFixedFont")
        self.txtNombre.configure(foreground="#000000")
        self.txtNombre.configure(highlightbackground="#d9d9d9")
        self.txtNombre.configure(highlightcolor="black")
        self.txtNombre.configure(insertbackground="black")
        self.txtNombre.configure(selectbackground="#c4c4c4")
        self.txtNombre.configure(selectforeground="black")
        self.txtNombre.configure(textvariable=STAsientos_support.nombre)

        self.lblNombre_13 = tk.Label(self.Frame1)
        self.lblNombre_13.place(relx=0.321, rely=0.291, height=21, width=54)
        self.lblNombre_13.configure(activebackground="#f9f9f9")
        self.lblNombre_13.configure(activeforeground="black")
        self.lblNombre_13.configure(background="#d9d9d9")
        self.lblNombre_13.configure(disabledforeground="#a3a3a3")
        self.lblNombre_13.configure(foreground="#000000")
        self.lblNombre_13.configure(highlightbackground="#d9d9d9")
        self.lblNombre_13.configure(highlightcolor="black")
        self.lblNombre_13.configure(text='''DNI:''')

        self.txtDNI = tk.Entry(self.Frame1)
        self.txtDNI.place(relx=0.256, rely=0.364,height=20, relwidth=0.538)
        self.txtDNI.configure(background="white")
        self.txtDNI.configure(disabledforeground="#a3a3a3")
        self.txtDNI.configure(font="TkFixedFont")
        self.txtDNI.configure(foreground="#000000")
        self.txtDNI.configure(highlightbackground="#d9d9d9")
        self.txtDNI.configure(highlightcolor="black")
        self.txtDNI.configure(insertbackground="black")
        self.txtDNI.configure(selectbackground="#c4c4c4")
        self.txtDNI.configure(selectforeground="black")
        self.txtDNI.configure(textvariable=STAsientos_support.dni)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.385, rely=0.473, height=21, width=34)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Clase:''')

        self.cmbClase = ttk.Combobox(self.Frame1)
        self.cmbClase.place(relx=0.256, rely=0.545, relheight=0.076
                , relwidth=0.532)
        self.value_list = ['EJECUTIVO','ECONOMICO',]
        self.cmbClase.configure(values=self.value_list)
        self.cmbClase.configure(textvariable=STAsientos_support.clase)
        self.cmbClase.configure(takefocus="")

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.256, rely=0.655, height=21, width=74)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Ubicacion:''')

        self.cmbUbicacion = ttk.Combobox(self.Frame1)
        self.cmbUbicacion.place(relx=0.256, rely=0.727, relheight=0.076
                , relwidth=0.532)
        self.value_list = ['VENTANA','CENTRO','PASILLO',]
        self.cmbUbicacion.configure(values=self.value_list)
        self.cmbUbicacion.configure(textvariable=STAsientos_support.ubicacion)
        self.cmbUbicacion.configure(takefocus="")

        self.btnAsignar = ttk.Button(self.Frame1)
        self.btnAsignar.place(relx=0.256, rely=0.873, height=25, width=86)
        self.btnAsignar.configure(command=STAsientos_support.asignar)
        self.btnAsignar.configure(takefocus="")
        self.btnAsignar.configure(text='''Asignar Pasaje''')

        self.Frame1_1 = tk.Frame(top)
        self.Frame1_1.place(relx=0.263, rely=0.022, relheight=0.611
                , relwidth=0.228)
        self.Frame1_1.configure(relief='groove')
        self.Frame1_1.configure(borderwidth="2")
        self.Frame1_1.configure(relief="groove")
        self.Frame1_1.configure(background="#d9d9d9")
        self.Frame1_1.configure(highlightbackground="#d9d9d9")
        self.Frame1_1.configure(highlightcolor="black")

        self.lblAsiento1 = tk.Label(self.Frame1_1)
        self.lblAsiento1.place(relx=0.064, rely=0.109, height=21, width=30)
        self.lblAsiento1.configure(activebackground="#f9f9f9")
        self.lblAsiento1.configure(activeforeground="black")
        self.lblAsiento1.configure(background="#6cf805")
        self.lblAsiento1.configure(disabledforeground="#a3a3a3")
        self.lblAsiento1.configure(foreground="#000000")
        self.lblAsiento1.configure(highlightbackground="#d9d9d9")
        self.lblAsiento1.configure(highlightcolor="black")
        self.lblAsiento1.configure(text='''1''')

        self.lblAsiento2 = tk.Label(self.Frame1_1)
        self.lblAsiento2.place(relx=0.705, rely=0.109, height=21, width=34)
        self.lblAsiento2.configure(activebackground="#f9f9f9")
        self.lblAsiento2.configure(activeforeground="black")
        self.lblAsiento2.configure(background="#6cf805")
        self.lblAsiento2.configure(disabledforeground="#a3a3a3")
        self.lblAsiento2.configure(foreground="#000000")
        self.lblAsiento2.configure(highlightbackground="#d9d9d9")
        self.lblAsiento2.configure(highlightcolor="black")
        self.lblAsiento2.configure(text='''2''')

        self.lblAsiento5 = tk.Label(self.Frame1_1)
        self.lblAsiento5.place(relx=0.064, rely=0.364, height=21, width=34)
        self.lblAsiento5.configure(activebackground="#f9f9f9")
        self.lblAsiento5.configure(activeforeground="black")
        self.lblAsiento5.configure(background="#6cf805")
        self.lblAsiento5.configure(disabledforeground="#a3a3a3")
        self.lblAsiento5.configure(foreground="#000000")
        self.lblAsiento5.configure(highlightbackground="#d9d9d9")
        self.lblAsiento5.configure(highlightcolor="black")
        self.lblAsiento5.configure(text='''5''')

        self.lblAsiento6 = tk.Label(self.Frame1_1)
        self.lblAsiento6.place(relx=0.385, rely=0.364, height=21, width=34)
        self.lblAsiento6.configure(activebackground="#f9f9f9")
        self.lblAsiento6.configure(activeforeground="black")
        self.lblAsiento6.configure(background="#6cf805")
        self.lblAsiento6.configure(disabledforeground="#a3a3a3")
        self.lblAsiento6.configure(foreground="#000000")
        self.lblAsiento6.configure(highlightbackground="#d9d9d9")
        self.lblAsiento6.configure(highlightcolor="black")
        self.lblAsiento6.configure(text='''6''')

        self.lblAsiento7 = tk.Label(self.Frame1_1)
        self.lblAsiento7.place(relx=0.705, rely=0.364, height=21, width=34)
        self.lblAsiento7.configure(activebackground="#f9f9f9")
        self.lblAsiento7.configure(activeforeground="black")
        self.lblAsiento7.configure(background="#6cf805")
        self.lblAsiento7.configure(disabledforeground="#a3a3a3")
        self.lblAsiento7.configure(foreground="#000000")
        self.lblAsiento7.configure(highlightbackground="#d9d9d9")
        self.lblAsiento7.configure(highlightcolor="black")
        self.lblAsiento7.configure(text='''7''')

        self.Frame1_2 = tk.Frame(top)
        self.Frame1_2.place(relx=0.497, rely=0.022, relheight=0.611
                , relwidth=0.228)
        self.Frame1_2.configure(relief='groove')
        self.Frame1_2.configure(borderwidth="2")
        self.Frame1_2.configure(relief="groove")
        self.Frame1_2.configure(background="#d9d9d9")
        self.Frame1_2.configure(highlightbackground="#d9d9d9")
        self.Frame1_2.configure(highlightcolor="black")

        self.lblAsiento3 = tk.Label(self.Frame1_2)
        self.lblAsiento3.place(relx=0.064, rely=0.109, height=21, width=34)
        self.lblAsiento3.configure(activebackground="#f9f9f9")
        self.lblAsiento3.configure(activeforeground="black")
        self.lblAsiento3.configure(background="#6cf805")
        self.lblAsiento3.configure(disabledforeground="#a3a3a3")
        self.lblAsiento3.configure(foreground="#000000")
        self.lblAsiento3.configure(highlightbackground="#d9d9d9")
        self.lblAsiento3.configure(highlightcolor="black")
        self.lblAsiento3.configure(text='''3''')

        self.lblAsiento4 = tk.Label(self.Frame1_2)
        self.lblAsiento4.place(relx=0.705, rely=0.109, height=21, width=34)
        self.lblAsiento4.configure(activebackground="#f9f9f9")
        self.lblAsiento4.configure(activeforeground="black")
        self.lblAsiento4.configure(background="#6cf805")
        self.lblAsiento4.configure(disabledforeground="#a3a3a3")
        self.lblAsiento4.configure(foreground="#000000")
        self.lblAsiento4.configure(highlightbackground="#d9d9d9")
        self.lblAsiento4.configure(highlightcolor="black")
        self.lblAsiento4.configure(text='''4''')

        self.lblAsiento8 = tk.Label(self.Frame1_2)
        self.lblAsiento8.place(relx=0.064, rely=0.364, height=21, width=34)
        self.lblAsiento8.configure(activebackground="#f9f9f9")
        self.lblAsiento8.configure(activeforeground="black")
        self.lblAsiento8.configure(background="#6cf805")
        self.lblAsiento8.configure(disabledforeground="#a3a3a3")
        self.lblAsiento8.configure(foreground="#000000")
        self.lblAsiento8.configure(highlightbackground="#d9d9d9")
        self.lblAsiento8.configure(highlightcolor="black")
        self.lblAsiento8.configure(text='''8''')

        self.lblAsiento9 = tk.Label(self.Frame1_2)
        self.lblAsiento9.place(relx=0.385, rely=0.364, height=21, width=34)
        self.lblAsiento9.configure(activebackground="#f9f9f9")
        self.lblAsiento9.configure(activeforeground="black")
        self.lblAsiento9.configure(background="#6cf805")
        self.lblAsiento9.configure(disabledforeground="#a3a3a3")
        self.lblAsiento9.configure(foreground="#000000")
        self.lblAsiento9.configure(highlightbackground="#d9d9d9")
        self.lblAsiento9.configure(highlightcolor="black")
        self.lblAsiento9.configure(text='''9''')

        self.lblAsiento10 = tk.Label(self.Frame1_2)
        self.lblAsiento10.place(relx=0.705, rely=0.364, height=21, width=34)
        self.lblAsiento10.configure(activebackground="#f9f9f9")
        self.lblAsiento10.configure(activeforeground="black")
        self.lblAsiento10.configure(background="#6cf805")
        self.lblAsiento10.configure(disabledforeground="#a3a3a3")
        self.lblAsiento10.configure(foreground="#000000")
        self.lblAsiento10.configure(highlightbackground="#d9d9d9")
        self.lblAsiento10.configure(highlightcolor="black")
        self.lblAsiento10.configure(text='''10''')

        self.Frame1_3 = tk.Frame(top)
        self.Frame1_3.place(relx=0.746, rely=0.022, relheight=0.611
                , relwidth=0.228)
        self.Frame1_3.configure(relief='groove')
        self.Frame1_3.configure(borderwidth="2")
        self.Frame1_3.configure(relief="groove")
        self.Frame1_3.configure(background="#d9d9d9")
        self.Frame1_3.configure(highlightbackground="#d9d9d9")
        self.Frame1_3.configure(highlightcolor="black")

        self.lblBusqueda = tk.Label(self.Frame1_3)
        self.lblBusqueda.place(relx=0.321, rely=0.036, height=21, width=58)
        self.lblBusqueda.configure(activebackground="#f9f9f9")
        self.lblBusqueda.configure(activeforeground="black")
        self.lblBusqueda.configure(background="#d9d9d9")
        self.lblBusqueda.configure(disabledforeground="#a3a3a3")
        self.lblBusqueda.configure(foreground="#000000")
        self.lblBusqueda.configure(highlightbackground="#d9d9d9")
        self.lblBusqueda.configure(highlightcolor="black")
        self.lblBusqueda.configure(text='''Busqueda''')

        self.Label3 = tk.Label(self.Frame1_3)
        self.Label3.place(relx=0.385, rely=0.145, height=21, width=34)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''DNI:''')

        self.txtDNIBuscar = tk.Entry(self.Frame1_3)
        self.txtDNIBuscar.place(relx=0.256, rely=0.255, height=20
                , relwidth=0.538)
        self.txtDNIBuscar.configure(background="white")
        self.txtDNIBuscar.configure(disabledforeground="#a3a3a3")
        self.txtDNIBuscar.configure(font="TkFixedFont")
        self.txtDNIBuscar.configure(foreground="#000000")
        self.txtDNIBuscar.configure(highlightbackground="#d9d9d9")
        self.txtDNIBuscar.configure(highlightcolor="black")
        self.txtDNIBuscar.configure(insertbackground="black")
        self.txtDNIBuscar.configure(selectbackground="#c4c4c4")
        self.txtDNIBuscar.configure(selectforeground="black")
        self.txtDNIBuscar.configure(textvariable=STAsientos_support.dniBuscar)

        self.btnBuscar = ttk.Button(self.Frame1_3)
        self.btnBuscar.place(relx=0.256, rely=0.4, height=25, width=86)
        self.btnBuscar.configure(command=STAsientos_support.buscar)
        self.btnBuscar.configure(takefocus="")
        self.btnBuscar.configure(text='''Buscar''')

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.015, rely=0.644, relheight=0.322
                , relwidth=0.418)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#d9d9d9")

        self.lblEliminar = tk.Label(self.Frame2)
        self.lblEliminar.place(relx=0.315, rely=0.069, height=21, width=96)
        self.lblEliminar.configure(background="#d9d9d9")
        self.lblEliminar.configure(disabledforeground="#a3a3a3")
        self.lblEliminar.configure(foreground="#000000")
        self.lblEliminar.configure(text='''Eliminar Pasajero''')

        self.lblDniEliminar = tk.Label(self.Frame2)
        self.lblDniEliminar.place(relx=0.035, rely=0.276, height=21, width=29)
        self.lblDniEliminar.configure(background="#d9d9d9")
        self.lblDniEliminar.configure(disabledforeground="#a3a3a3")
        self.lblDniEliminar.configure(foreground="#000000")
        self.lblDniEliminar.configure(text='''DNI:''')

        self.txtDNIEliminar = tk.Entry(self.Frame2)
        self.txtDNIEliminar.place(relx=0.245, rely=0.276, height=20
                , relwidth=0.294)
        self.txtDNIEliminar.configure(background="white")
        self.txtDNIEliminar.configure(disabledforeground="#a3a3a3")
        self.txtDNIEliminar.configure(font="TkFixedFont")
        self.txtDNIEliminar.configure(foreground="#000000")
        self.txtDNIEliminar.configure(insertbackground="black")
        self.txtDNIEliminar.configure(textvariable=STAsientos_support.dniEliminar)

        self.btnEliminar = ttk.Button(self.Frame2)
        self.btnEliminar.place(relx=0.245, rely=0.483, height=25, width=100)
        self.btnEliminar.configure(command=STAsientos_support.eliminar)
        self.btnEliminar.configure(takefocus="")
        self.btnEliminar.configure(text='''Eliminar Pasajero''')

if __name__ == '__main__':
    vp_start_gui()





