#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 15, 2020 05:54:38 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def buscarPasajero():
    print('TPPasajeros_support.buscarPasajero')
    sys.stdout.flush()

def eliminarPasajero():
    print('TPPasajeros_support.eliminarPasajero')
    sys.stdout.flush()

def porcentajeOcup():
    print('TPPasajeros_support.porcentajeOcup')
    sys.stdout.flush()

def registrarPasajero():
    print('TPPasajeros_support.registrarPasajero')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import TPPasajeros
    TPPasajeros.vp_start_gui()