#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 15, 2020 09:16:11 PM -03  platform: Windows NT
#    Apr 15, 2020 10:02:53 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global asiento1
    asiento1 = tk.IntVar()
    global asiento2
    asiento2 = tk.IntVar()
    global asiento3
    asiento3 = tk.IntVar()
    global asiento4
    asiento4 = tk.IntVar()
    global asiento5
    asiento5 = tk.IntVar()
    global asiento6
    asiento6 = tk.IntVar()
    global asiento7
    asiento7 = tk.IntVar()
    global asiento8
    asiento8 = tk.IntVar()
    global asiento9
    asiento9 = tk.IntVar()
    global asiento10
    asiento10 = tk.IntVar()
    global asiento11
    asiento11 = tk.IntVar()
    global asiento12
    asiento12 = tk.IntVar()
    global asiento13
    asiento13 = tk.IntVar()
    global asiento14
    asiento14 = tk.IntVar()
    global asiento15
    asiento15 = tk.IntVar()
    global asiento16
    asiento16 = tk.IntVar()
    global asiento17
    asiento17 = tk.IntVar()
    global asiento18
    asiento18 = tk.IntVar()
    global asiento19
    asiento19 = tk.IntVar()
    global asiento20
    asiento20 = tk.IntVar()
    global che52
    che52 = tk.IntVar()
    global che55
    che55 = tk.IntVar()
    global che56
    che56 = tk.IntVar()
    global che57
    che57 = tk.IntVar()
    global che61
    che61 = tk.IntVar()
    global che62
    che62 = tk.IntVar()
    global che63
    che63 = tk.IntVar()
    global che64
    che64 = tk.IntVar()
    global che65
    che65 = tk.IntVar()
    global che66
    che66 = tk.IntVar()
    global che68
    che68 = tk.IntVar()
    global che71
    che71 = tk.IntVar()
    global che72
    che72 = tk.IntVar()
    global che73
    che73 = tk.IntVar()
    global che74
    che74 = tk.IntVar()
    global che75
    che75 = tk.IntVar()
    global che76
    che76 = tk.IntVar()
    global che77
    che77 = tk.IntVar()
    global che78
    che78 = tk.IntVar()
    global che79
    che79 = tk.IntVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Vuelos
    Vuelos.vp_start_gui()





