#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 15, 2020 10:02:46 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Vuelos_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    Vuelos_support.set_Tk_var()
    top = Toplevel1 (root)
    Vuelos_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    Vuelos_support.set_Tk_var()
    top = Toplevel1 (w)
    Vuelos_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font11 = "-family {Arial Black} -size 24 -weight bold"
        font13 = "-family {Arial Black} -size 12 -weight bold"
        font14 = "-family {Arial Black} -size 10 -weight bold"

        top.geometry("578x448+446+133")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.txtPrimeraClase = tk.LabelFrame(top)
        self.txtPrimeraClase.place(relx=0.104, rely=0.112, relheight=0.156
                , relwidth=0.779)
        self.txtPrimeraClase.configure(relief='groove')
        self.txtPrimeraClase.configure(font=font13)
        self.txtPrimeraClase.configure(foreground="#ff0000")
        self.txtPrimeraClase.configure(text='''Primera Clase''')
        self.txtPrimeraClase.configure(background="#d9d9d9")

        self.btnAsiento1 = tk.Checkbutton(self.txtPrimeraClase)
        self.btnAsiento1.place(relx=0.022, rely=0.429, relheight=0.357
                , relwidth=0.202, bordermode='ignore')
        self.btnAsiento1.configure(activebackground="#ececec")
        self.btnAsiento1.configure(activeforeground="#000000")
        self.btnAsiento1.configure(background="#d9d9d9")
        self.btnAsiento1.configure(cursor="fleur")
        self.btnAsiento1.configure(disabledforeground="#a3a3a3")
        self.btnAsiento1.configure(font=font14)
        self.btnAsiento1.configure(foreground="#ffff22")
        self.btnAsiento1.configure(highlightbackground="#000000")
        self.btnAsiento1.configure(highlightcolor="#000000")
        self.btnAsiento1.configure(justify='left')
        self.btnAsiento1.configure(text='''Asiento 1''')
        self.btnAsiento1.configure(variable=Vuelos_support.asiento1)

        self.btnAsiento2 = tk.Checkbutton(self.txtPrimeraClase)
        self.btnAsiento2.place(relx=0.244, rely=0.429, relheight=0.414
                , relwidth=0.218, bordermode='ignore')
        self.btnAsiento2.configure(activebackground="#ececec")
        self.btnAsiento2.configure(activeforeground="#000000")
        self.btnAsiento2.configure(background="#d9d9d9")
        self.btnAsiento2.configure(disabledforeground="#a3a3a3")
        self.btnAsiento2.configure(font=font14)
        self.btnAsiento2.configure(foreground="#ffff17")
        self.btnAsiento2.configure(highlightbackground="#d9d9d9")
        self.btnAsiento2.configure(highlightcolor="black")
        self.btnAsiento2.configure(justify='left')
        self.btnAsiento2.configure(text='''Asiento 2''')
        self.btnAsiento2.configure(variable=Vuelos_support.asiento2)

        self.btnAsiento3 = tk.Checkbutton(self.txtPrimeraClase)
        self.btnAsiento3.place(relx=0.511, rely=0.429, relheight=0.357
                , relwidth=0.216, bordermode='ignore')
        self.btnAsiento3.configure(activebackground="#ececec")
        self.btnAsiento3.configure(activeforeground="#000000")
        self.btnAsiento3.configure(background="#d9d9d9")
        self.btnAsiento3.configure(disabledforeground="#a3a3a3")
        self.btnAsiento3.configure(font=font14)
        self.btnAsiento3.configure(foreground="#ffff20")
        self.btnAsiento3.configure(highlightbackground="#d9d9d9")
        self.btnAsiento3.configure(highlightcolor="black")
        self.btnAsiento3.configure(justify='left')
        self.btnAsiento3.configure(text='''Asiento 3''')
        self.btnAsiento3.configure(variable=Vuelos_support.asiento3)

        self.btnAsiento4 = tk.Checkbutton(self.txtPrimeraClase)
        self.btnAsiento4.place(relx=0.756, rely=0.429, relheight=0.414
                , relwidth=0.218, bordermode='ignore')
        self.btnAsiento4.configure(activebackground="#ececec")
        self.btnAsiento4.configure(activeforeground="#000000")
        self.btnAsiento4.configure(background="#d9d9d9")
        self.btnAsiento4.configure(disabledforeground="#a3a3a3")
        self.btnAsiento4.configure(font=font14)
        self.btnAsiento4.configure(foreground="#ffff33")
        self.btnAsiento4.configure(highlightbackground="#d9d9d9")
        self.btnAsiento4.configure(highlightcolor="black")
        self.btnAsiento4.configure(justify='left')
        self.btnAsiento4.configure(text='''Asiento 4''')
        self.btnAsiento4.configure(variable=Vuelos_support.asiento4)

        self.txtSegundaClase = tk.LabelFrame(top)
        self.txtSegundaClase.place(relx=0.104, rely=0.29, relheight=0.491
                , relwidth=0.779)
        self.txtSegundaClase.configure(relief='groove')
        self.txtSegundaClase.configure(font=font13)
        self.txtSegundaClase.configure(foreground="#ff8000")
        self.txtSegundaClase.configure(text='''Segunda Clase''')
        self.txtSegundaClase.configure(background="#d9d9d9")
        self.txtSegundaClase.configure(cursor="fleur")
        self.txtSegundaClase.configure(highlightbackground="#f0f0f0")
        self.txtSegundaClase.configure(highlightcolor="#646464646464")

        self.btnAsiento5 = tk.Checkbutton(self.txtSegundaClase)
        self.btnAsiento5.place(relx=0.022, rely=0.273, relheight=0.132
                , relwidth=0.218, bordermode='ignore')
        self.btnAsiento5.configure(activebackground="#ececec")
        self.btnAsiento5.configure(activeforeground="#000000")
        self.btnAsiento5.configure(background="#d9d9d9")
        self.btnAsiento5.configure(disabledforeground="#a3a3a3")
        self.btnAsiento5.configure(font=font14)
        self.btnAsiento5.configure(foreground="#0000ff")
        self.btnAsiento5.configure(highlightbackground="#d9d9d9")
        self.btnAsiento5.configure(highlightcolor="black")
        self.btnAsiento5.configure(justify='left')
        self.btnAsiento5.configure(text='''Asiento 5''')
        self.btnAsiento5.configure(variable=Vuelos_support.asiento5)

        self.btnAsiento6 = tk.Checkbutton(self.txtSegundaClase)
        self.btnAsiento6.place(relx=0.267, rely=0.273, relheight=0.132
                , relwidth=0.218, bordermode='ignore')
        self.btnAsiento6.configure(activebackground="#ececec")
        self.btnAsiento6.configure(activeforeground="#000000")
        self.btnAsiento6.configure(background="#d9d9d9")
        self.btnAsiento6.configure(disabledforeground="#a3a3a3")
        self.btnAsiento6.configure(font=font14)
        self.btnAsiento6.configure(foreground="#0000ff")
        self.btnAsiento6.configure(highlightbackground="#d9d9d9")
        self.btnAsiento6.configure(highlightcolor="black")
        self.btnAsiento6.configure(justify='left')
        self.btnAsiento6.configure(text='''Asiento 6''')
        self.btnAsiento6.configure(variable=Vuelos_support.asiento6)

        self.btnAsiento7 = tk.Checkbutton(self.txtSegundaClase)
        self.btnAsiento7.place(relx=0.518, rely=0.273, relheight=0.132
                , relwidth=0.218, bordermode='ignore')
        self.btnAsiento7.configure(activebackground="#ececec")
        self.btnAsiento7.configure(activeforeground="#000000")
        self.btnAsiento7.configure(background="#d9d9d9")
        self.btnAsiento7.configure(disabledforeground="#a3a3a3")
        self.btnAsiento7.configure(font=font14)
        self.btnAsiento7.configure(foreground="#0000ff")
        self.btnAsiento7.configure(highlightbackground="#d9d9d9")
        self.btnAsiento7.configure(highlightcolor="black")
        self.btnAsiento7.configure(justify='left')
        self.btnAsiento7.configure(text='''Asiento 7''')
        self.btnAsiento7.configure(variable=Vuelos_support.asiento7)

        self.btnAsiento8 = tk.Checkbutton(self.txtSegundaClase)
        self.btnAsiento8.place(relx=0.756, rely=0.273, relheight=0.132
                , relwidth=0.218, bordermode='ignore')
        self.btnAsiento8.configure(activebackground="#ececec")
        self.btnAsiento8.configure(activeforeground="#000000")
        self.btnAsiento8.configure(background="#d9d9d9")
        self.btnAsiento8.configure(cursor="fleur")
        self.btnAsiento8.configure(disabledforeground="#a3a3a3")
        self.btnAsiento8.configure(font=font14)
        self.btnAsiento8.configure(foreground="#0000ff")
        self.btnAsiento8.configure(highlightbackground="#d9d9d9")
        self.btnAsiento8.configure(highlightcolor="black")
        self.btnAsiento8.configure(justify='left')
        self.btnAsiento8.configure(text='''Asiento 8''')
        self.btnAsiento8.configure(variable=Vuelos_support.asiento8)

        self.btnAsiento9 = tk.Checkbutton(self.txtSegundaClase)
        self.btnAsiento9.place(relx=0.022, rely=0.455, relheight=0.132
                , relwidth=0.218, bordermode='ignore')
        self.btnAsiento9.configure(activebackground="#ececec")
        self.btnAsiento9.configure(activeforeground="#000000")
        self.btnAsiento9.configure(background="#d9d9d9")
        self.btnAsiento9.configure(disabledforeground="#a3a3a3")
        self.btnAsiento9.configure(font=font14)
        self.btnAsiento9.configure(foreground="#0000ff")
        self.btnAsiento9.configure(highlightbackground="#d9d9d9")
        self.btnAsiento9.configure(highlightcolor="black")
        self.btnAsiento9.configure(justify='left')
        self.btnAsiento9.configure(text='''Asiento 9''')
        self.btnAsiento9.configure(variable=Vuelos_support.asiento9)

        self.btnAsiento10 = tk.Checkbutton(self.txtSegundaClase)
        self.btnAsiento10.place(relx=0.269, rely=0.455, relheight=0.132
                , relwidth=0.238, bordermode='ignore')
        self.btnAsiento10.configure(activebackground="#ececec")
        self.btnAsiento10.configure(activeforeground="#000000")
        self.btnAsiento10.configure(background="#d9d9d9")
        self.btnAsiento10.configure(disabledforeground="#a3a3a3")
        self.btnAsiento10.configure(font=font14)
        self.btnAsiento10.configure(foreground="#0000ff")
        self.btnAsiento10.configure(highlightbackground="#d9d9d9")
        self.btnAsiento10.configure(highlightcolor="black")
        self.btnAsiento10.configure(justify='left')
        self.btnAsiento10.configure(text='''Asiento 10''')
        self.btnAsiento10.configure(variable=Vuelos_support.asiento10)

        self.btnAsiento11 = tk.Checkbutton(self.txtSegundaClase)
        self.btnAsiento11.place(relx=0.511, rely=0.455, relheight=0.095
                , relwidth=0.251, bordermode='ignore')
        self.btnAsiento11.configure(activebackground="#ececec")
        self.btnAsiento11.configure(activeforeground="#000000")
        self.btnAsiento11.configure(background="#d9d9d9")
        self.btnAsiento11.configure(disabledforeground="#a3a3a3")
        self.btnAsiento11.configure(font=font14)
        self.btnAsiento11.configure(foreground="#0000ff")
        self.btnAsiento11.configure(highlightbackground="#d9d9d9")
        self.btnAsiento11.configure(highlightcolor="black")
        self.btnAsiento11.configure(justify='left')
        self.btnAsiento11.configure(text='''Asiento 11''')
        self.btnAsiento11.configure(variable=Vuelos_support.asiento11)

        self.btnAsiento12 = tk.Checkbutton(self.txtSegundaClase)
        self.btnAsiento12.place(relx=0.76, rely=0.455, relheight=0.114
                , relwidth=0.224, bordermode='ignore')
        self.btnAsiento12.configure(activebackground="#ececec")
        self.btnAsiento12.configure(activeforeground="#000000")
        self.btnAsiento12.configure(background="#d9d9d9")
        self.btnAsiento12.configure(disabledforeground="#a3a3a3")
        self.btnAsiento12.configure(font=font14)
        self.btnAsiento12.configure(foreground="#0000ff")
        self.btnAsiento12.configure(highlightbackground="#d9d9d9")
        self.btnAsiento12.configure(highlightcolor="black")
        self.btnAsiento12.configure(justify='left')
        self.btnAsiento12.configure(text='''Asiento 12''')
        self.btnAsiento12.configure(variable=Vuelos_support.asiento12)

        self.btnAsiento13 = tk.Checkbutton(self.txtSegundaClase)
        self.btnAsiento13.place(relx=0.022, rely=0.636, relheight=0.132
                , relwidth=0.238, bordermode='ignore')
        self.btnAsiento13.configure(activebackground="#ececec")
        self.btnAsiento13.configure(activeforeground="#000000")
        self.btnAsiento13.configure(background="#d9d9d9")
        self.btnAsiento13.configure(disabledforeground="#a3a3a3")
        self.btnAsiento13.configure(font=font14)
        self.btnAsiento13.configure(foreground="#0000ff")
        self.btnAsiento13.configure(highlightbackground="#d9d9d9")
        self.btnAsiento13.configure(highlightcolor="black")
        self.btnAsiento13.configure(justify='left')
        self.btnAsiento13.configure(text='''Asiento 13''')
        self.btnAsiento13.configure(variable=Vuelos_support.asiento13)

        self.btnAsiento14 = tk.Checkbutton(self.txtSegundaClase)
        self.btnAsiento14.place(relx=0.271, rely=0.636, relheight=0.159
                , relwidth=0.229, bordermode='ignore')
        self.btnAsiento14.configure(activebackground="#ececec")
        self.btnAsiento14.configure(activeforeground="#000000")
        self.btnAsiento14.configure(background="#d9d9d9")
        self.btnAsiento14.configure(disabledforeground="#a3a3a3")
        self.btnAsiento14.configure(font=font14)
        self.btnAsiento14.configure(foreground="#0000ff")
        self.btnAsiento14.configure(highlightbackground="#d9d9d9")
        self.btnAsiento14.configure(highlightcolor="black")
        self.btnAsiento14.configure(justify='left')
        self.btnAsiento14.configure(text='''Asiento 14''')
        self.btnAsiento14.configure(variable=Vuelos_support.asiento14)

        self.btnAsiento15 = tk.Checkbutton(self.txtSegundaClase)
        self.btnAsiento15.place(relx=0.518, rely=0.636, relheight=0.132
                , relwidth=0.238, bordermode='ignore')
        self.btnAsiento15.configure(activebackground="#ececec")
        self.btnAsiento15.configure(activeforeground="#000000")
        self.btnAsiento15.configure(background="#d9d9d9")
        self.btnAsiento15.configure(disabledforeground="#a3a3a3")
        self.btnAsiento15.configure(font=font14)
        self.btnAsiento15.configure(foreground="#0000ff")
        self.btnAsiento15.configure(highlightbackground="#d9d9d9")
        self.btnAsiento15.configure(highlightcolor="black")
        self.btnAsiento15.configure(justify='left')
        self.btnAsiento15.configure(text='''Asiento 15''')
        self.btnAsiento15.configure(variable=Vuelos_support.asiento15)

        self.btnAsiento16 = tk.Checkbutton(self.txtSegundaClase)
        self.btnAsiento16.place(relx=0.756, rely=0.636, relheight=0.132
                , relwidth=0.238, bordermode='ignore')
        self.btnAsiento16.configure(activebackground="#ececec")
        self.btnAsiento16.configure(activeforeground="#000000")
        self.btnAsiento16.configure(background="#d9d9d9")
        self.btnAsiento16.configure(disabledforeground="#a3a3a3")
        self.btnAsiento16.configure(font=font14)
        self.btnAsiento16.configure(foreground="#0000ff")
        self.btnAsiento16.configure(highlightbackground="#d9d9d9")
        self.btnAsiento16.configure(highlightcolor="black")
        self.btnAsiento16.configure(justify='left')
        self.btnAsiento16.configure(text='''Asiento 16''')
        self.btnAsiento16.configure(variable=Vuelos_support.asiento16)

        self.btnAsiento17 = tk.Checkbutton(self.txtSegundaClase)
        self.btnAsiento17.place(relx=0.022, rely=0.818, relheight=0.132
                , relwidth=0.238, bordermode='ignore')
        self.btnAsiento17.configure(activebackground="#ececec")
        self.btnAsiento17.configure(activeforeground="#000000")
        self.btnAsiento17.configure(background="#d9d9d9")
        self.btnAsiento17.configure(disabledforeground="#a3a3a3")
        self.btnAsiento17.configure(font=font14)
        self.btnAsiento17.configure(foreground="#0000ff")
        self.btnAsiento17.configure(highlightbackground="#d9d9d9")
        self.btnAsiento17.configure(highlightcolor="black")
        self.btnAsiento17.configure(justify='left')
        self.btnAsiento17.configure(text='''Asiento 17''')
        self.btnAsiento17.configure(variable=Vuelos_support.asiento17)

        self.btnAsiento18 = tk.Checkbutton(self.txtSegundaClase)
        self.btnAsiento18.place(relx=0.267, rely=0.818, relheight=0.132
                , relwidth=0.238, bordermode='ignore')
        self.btnAsiento18.configure(activebackground="#ececec")
        self.btnAsiento18.configure(activeforeground="#000000")
        self.btnAsiento18.configure(background="#d9d9d9")
        self.btnAsiento18.configure(disabledforeground="#a3a3a3")
        self.btnAsiento18.configure(font=font14)
        self.btnAsiento18.configure(foreground="#0000ff")
        self.btnAsiento18.configure(highlightbackground="#d9d9d9")
        self.btnAsiento18.configure(highlightcolor="black")
        self.btnAsiento18.configure(justify='left')
        self.btnAsiento18.configure(text='''Asiento 18''')
        self.btnAsiento18.configure(variable=Vuelos_support.asiento18)

        self.btnAsiento19 = tk.Checkbutton(self.txtSegundaClase)
        self.btnAsiento19.place(relx=0.518, rely=0.818, relheight=0.132
                , relwidth=0.238, bordermode='ignore')
        self.btnAsiento19.configure(activebackground="#ececec")
        self.btnAsiento19.configure(activeforeground="#000000")
        self.btnAsiento19.configure(background="#d9d9d9")
        self.btnAsiento19.configure(disabledforeground="#a3a3a3")
        self.btnAsiento19.configure(font=font14)
        self.btnAsiento19.configure(foreground="#0000ff")
        self.btnAsiento19.configure(highlightbackground="#d9d9d9")
        self.btnAsiento19.configure(highlightcolor="black")
        self.btnAsiento19.configure(justify='left')
        self.btnAsiento19.configure(text='''Asiento 19''')
        self.btnAsiento19.configure(variable=Vuelos_support.asiento19)

        self.btnAsiento20 = tk.Checkbutton(self.txtSegundaClase)
        self.btnAsiento20.place(relx=0.756, rely=0.818, relheight=0.132
                , relwidth=0.238, bordermode='ignore')
        self.btnAsiento20.configure(activebackground="#ececec")
        self.btnAsiento20.configure(activeforeground="#000000")
        self.btnAsiento20.configure(background="#d9d9d9")
        self.btnAsiento20.configure(disabledforeground="#a3a3a3")
        self.btnAsiento20.configure(font=font14)
        self.btnAsiento20.configure(foreground="#0000ff")
        self.btnAsiento20.configure(highlightbackground="#d9d9d9")
        self.btnAsiento20.configure(highlightcolor="black")
        self.btnAsiento20.configure(justify='left')
        self.btnAsiento20.configure(text='''Asiento 20''')
        self.btnAsiento20.configure(variable=Vuelos_support.asiento20)

        self.txtAdicionales = tk.LabelFrame(top)
        self.txtAdicionales.place(relx=0.104, rely=0.781, relheight=0.212
                , relwidth=0.779)
        self.txtAdicionales.configure(relief='groove')
        self.txtAdicionales.configure(font=font13)
        self.txtAdicionales.configure(foreground="#5ebb00")
        self.txtAdicionales.configure(text='''Adicionales''')
        self.txtAdicionales.configure(background="#d9d9d9")

        self.btnRegistrar = tk.Button(self.txtAdicionales)
        self.btnRegistrar.place(relx=0.022, rely=0.316, height=24, width=147
                , bordermode='ignore')
        self.btnRegistrar.configure(activebackground="#ececec")
        self.btnRegistrar.configure(activeforeground="#000000")
        self.btnRegistrar.configure(background="#d9d9d9")
        self.btnRegistrar.configure(disabledforeground="#a3a3a3")
        self.btnRegistrar.configure(font=font14)
        self.btnRegistrar.configure(foreground="#000000")
        self.btnRegistrar.configure(highlightbackground="#d9d9d9")
        self.btnRegistrar.configure(highlightcolor="black")
        self.btnRegistrar.configure(pady="0")
        self.btnRegistrar.configure(text='''Registrar Pasajeros''')

        self.btnPorcentaje = tk.Button(self.txtAdicionales)
        self.btnPorcentaje.place(relx=0.022, rely=0.632, height=24, width=177
                , bordermode='ignore')
        self.btnPorcentaje.configure(activebackground="#ececec")
        self.btnPorcentaje.configure(activeforeground="#000000")
        self.btnPorcentaje.configure(background="#d9d9d9")
        self.btnPorcentaje.configure(disabledforeground="#a3a3a3")
        self.btnPorcentaje.configure(font=font14)
        self.btnPorcentaje.configure(foreground="#000000")
        self.btnPorcentaje.configure(highlightbackground="#d9d9d9")
        self.btnPorcentaje.configure(highlightcolor="black")
        self.btnPorcentaje.configure(pady="0")
        self.btnPorcentaje.configure(text='''Porcentaje Ocupación''')

        self.btnEliminar = tk.Button(self.txtAdicionales)
        self.btnEliminar.place(relx=0.4, rely=0.316, height=24, width=131
                , bordermode='ignore')
        self.btnEliminar.configure(activebackground="#ececec")
        self.btnEliminar.configure(activeforeground="#000000")
        self.btnEliminar.configure(background="#d9d9d9")
        self.btnEliminar.configure(disabledforeground="#a3a3a3")
        self.btnEliminar.configure(font=font14)
        self.btnEliminar.configure(foreground="#000000")
        self.btnEliminar.configure(highlightbackground="#d9d9d9")
        self.btnEliminar.configure(highlightcolor="black")
        self.btnEliminar.configure(pady="0")
        self.btnEliminar.configure(text='''Eliminar Pasajero''')

        self.btnOpcion1 = tk.Button(self.txtAdicionales)
        self.btnOpcion1.place(relx=0.467, rely=0.632, height=24, width=89
                , bordermode='ignore')
        self.btnOpcion1.configure(activebackground="#ececec")
        self.btnOpcion1.configure(activeforeground="#000000")
        self.btnOpcion1.configure(background="#d9d9d9")
        self.btnOpcion1.configure(disabledforeground="#a3a3a3")
        self.btnOpcion1.configure(font=font14)
        self.btnOpcion1.configure(foreground="#000000")
        self.btnOpcion1.configure(highlightbackground="#d9d9d9")
        self.btnOpcion1.configure(highlightcolor="black")
        self.btnOpcion1.configure(pady="0")
        self.btnOpcion1.configure(text='''Opción 1''')

        self.btnBuscar = tk.Button(self.txtAdicionales)
        self.btnBuscar.place(relx=0.711, rely=0.316, height=24, width=123
                , bordermode='ignore')
        self.btnBuscar.configure(activebackground="#ececec")
        self.btnBuscar.configure(activeforeground="#000000")
        self.btnBuscar.configure(background="#d9d9d9")
        self.btnBuscar.configure(cursor="fleur")
        self.btnBuscar.configure(disabledforeground="#a3a3a3")
        self.btnBuscar.configure(font=font14)
        self.btnBuscar.configure(foreground="#000000")
        self.btnBuscar.configure(highlightbackground="#d9d9d9")
        self.btnBuscar.configure(highlightcolor="black")
        self.btnBuscar.configure(pady="0")
        self.btnBuscar.configure(text='''Buscar Pasajero''')

        self.btnOpcion2 = tk.Button(self.txtAdicionales)
        self.btnOpcion2.place(relx=0.756, rely=0.632, height=24, width=97
                , bordermode='ignore')
        self.btnOpcion2.configure(activebackground="#ececec")
        self.btnOpcion2.configure(activeforeground="#000000")
        self.btnOpcion2.configure(background="#d9d9d9")
        self.btnOpcion2.configure(disabledforeground="#a3a3a3")
        self.btnOpcion2.configure(font=font14)
        self.btnOpcion2.configure(foreground="#000000")
        self.btnOpcion2.configure(highlightbackground="#d9d9d9")
        self.btnOpcion2.configure(highlightcolor="black")
        self.btnOpcion2.configure(pady="0")
        self.btnOpcion2.configure(text='''Opción 2''')

        self.txtVuelos = tk.Label(top)
        self.txtVuelos.place(relx=0.277, rely=0.022, height=31, width=244)
        self.txtVuelos.configure(background="#d9d9d9")
        self.txtVuelos.configure(disabledforeground="#a3a3a3")
        self.txtVuelos.configure(font=font11)
        self.txtVuelos.configure(foreground="#808000")
        self.txtVuelos.configure(text='''Vuelos''')

if __name__ == '__main__':
    vp_start_gui()
